### ISSUE TITLE
订阅功能无限卡loading....

### ISSUE THREAD

**Issue by BlueSkyClouds** [qd-today/qd#10]
已尝试 关闭谷歌浏览器所有插件 以及添加管理员账号，均无效 手动替换
链接也是  log 无任何有用信息  手动替换har链接无效        
![TIM截图20200701143615](https://user-images.githubusercontent.com/39831773/86211074-54cf6800-bba8-11ea-8406-3754cdc20686.png)

附log

[I 200701 14:32:33 web:2064] 304 GET /har/edit?tplurl=https%3A//raw.githubusercontent.com/qiandao-today/templates/master/%25E8%2581%2594%25E6%2583%25B3%25E7%25AD%25BE%25E5%2588%25B0%25E5%25BB%25B6%25E4%25BF%259D%28jointask%29.har&name=%E8%81%94%E6%83%B3%E7%AD%BE%E5%88%B0%E5%BB%B6%E4%BF%9D%28jointask%29.har (172.17.0.1) 1.31ms

**Comment by BlueSkyClouds** [comment]
使用的最新版本  2020.6.22

**Comment by asdaragon** [comment]
@BlueskyClouds 使用Chrome,给github扶梯后在试试

**Comment by BlueskyClouds** [comment]
已尝试 无效， 而且我本身是路由器 代理 已尝试给docker使用扶梯  依旧不行

**Comment by BlueSkyClouds** [comment]
已尝试 无效， 而且我本身是路由器 代理 尝试过给docker使用扶梯 依旧不行   几种方法都尝试过

**Comment by asdaragon** [comment]
@BlueskyClouds 看了一下，raw.githubusercontent.com的dns被严重污染，可以用 nslookup raw.githubusercontent.com 查看有没有解析到IP，如果返回是0.0.0.0，表示已经被污染了。如果是污染，你需要专门给raw.githubusercontent.com 添加到梯子列表里，不是给docker 扶梯。

**Comment by BlueSkyClouds** [comment]
均无问题  能正常解析=_=

**Comment by asdaragon** [comment]
@BlueskyClouds  点击订阅，按f12，刷新一下打开console那个页面，看看报什么错了

**Comment by BlueskyClouds** [comment]
DevTools failed to load SourceMap: Could not load content for chrome-extension://ncennffkjdiamlpmcbajkmaiiiddgioo/js/xl-content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
angular.js:10023 TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at c.<anonymous> (upload_ctrl.js:211)
    at d (angular.js:3940)
    at Object.instantiate (angular.js:3951)
    at angular.js:7244
    at angular.js:6635
    at q (angular.js:332)
    at M (angular.js:6622)
    at g (angular.js:6070)
    at g (angular.js:6073)
    at g (angular.js:6073)




/static/components/angularjs/angular.min.js

**Comment by BlueSkyClouds** [comment]
![TIM截图20200703002203](https://user-images.githubusercontent.com/39831773/86385696-43c74980-bcc3-11ea-9c30-ea7bc5214f6c.png)


angular.js:10023 TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.

**Comment by asdaragon** [comment]
@BlueskyClouds  你这是JS文件没有更新，20200606版本中已经readAsText 这个函数删除了,对比链接（https://github.com/AragonSnow/qiandao/commit/15f95b18ae979ccfd7a22946f26cd2fcbbb26588#diff-844b73f939a7086db1e3a474e8659eb1）。
可以在f12-sources-static-har-查看upload_ctrl.js，如果是旧版本的，尝试： 
f12 - network-勾选disable cache，重启chrome,打开网页，查看upload_ctrl.js
