### ISSUE TITLE
failed at 1/3 request, error:HTTP 599: Timeout while connecting, https://chdbits.co/bakatest.php，请问这是什么问题

### ISSUE THREAD

**Issue by hecarli555** [qd-today/qd#100]
最近docker版签到很不稳定，很多站点的签到都提示“failed at 1/3 request, error:HTTP 599: Timeout while connecting, https://chdbits.co/bakatest.php”这个而签到失败，请问大佬这是什么问题呢？nas网络是好的，上传下载都是正常的，带宽也没占完，但就是提示这个而失败

**Comment by asdaragon** [comment]
@hecarli555 599一般是网络问题，如果是在路由上部署的，要改一下防火墙规则。
