### ISSUE TITLE
优化重试及失败的通知策略

### ISSUE THREAD

**Issue by shuosiw** [qd-today/qd#101]
### 现状

目前是有签到重试机制，也有失败通知：

1. 每次失败都会进行推送通知
2. 但是大部分失败情况是因为网络问题，等待重试即可
3. 而因为重试失败的通知，会降低通知的有效性

### 需求

希望支持设置：

1. 重试的间隔及最大重试次数
2. 重试达到最大次数才发通知，中间的失败，就等重试即可

这样能达到效果，提高通知的有效性，就是收到失败通知就一定进行处理或者确认

**Comment by asdaragon** [comment]
![image](https://user-images.githubusercontent.com/22835918/129506362-fe421463-639c-451c-b9f8-7b796db2e1aa.png)
@shuosiw 工具箱-推送设置里有

**Comment by shuosiw** [comment]
谢谢大佬，之前没看到不好意思哇~这个能满足需求了
