### ISSUE TITLE
请问如果忘记登录密码，又没有设置邮箱服务，如何找回？或者替换修改？

### ISSUE THREAD

**Issue by ap6689** [qd-today/qd#102]

**Comment by ap6689** [comment]
自己研究出来了，新注册一个账号，SSH下设立为管理员登陆即可修改。  请记好自己的账号密码，不然签到多了，丢了在重新做 很烦人

**Comment by jasonchio-cn** [comment]
> 自己研究出来了，新注册一个账号，SSH下设立为管理员登陆即可修改。 请记好自己的账号密码，不然签到多了，丢了在重新做 很烦人

可以详细说一下吗，谢谢

**Comment by ap6689** [comment]
> > 自己研究出来了，新注册一个账号，SSH下设立为管理员登陆即可修改。 请记好自己的账号密码，不然签到多了，丢了在重新做 很烦人
> 
> 可以详细说一下吗，谢谢

新注册一个新的账号，然后把其设定为管理员级别的。这时候就可以看到之前的脚本了

**Comment by ap6689** [comment]
> > 自己研究出来了，新注册一个账号，SSH下设立为管理员登陆即可修改。 请记好自己的账号密码，不然签到多了，丢了在重新做 很烦人
> 
> 可以详细说一下吗，谢谢

因为太久了，已经有些忘记了。可以百度下，或者说我用的版本比较低了，当时教程是有一个步骤，设定管理员权限的账号的。只需要把新账号建立成管理员，即可看到以前设定的脚本了（无法找回修账号，删除掉在重新建立即可）

**Comment by jasonchio-cn** [comment]
> > > 自己研究出来了，新注册一个账号，SSH下设立为管理员登陆即可修改。 请记好自己的账号密码，不然签到多了，丢了在重新做 很烦人
> > 
> > 
> > 可以详细说一下吗，谢谢
> 
> 因为太久了，已经有些忘记了。可以百度下，或者说我用的版本比较低了，当时教程是有一个步骤，设定管理员权限的账号的。只需要把新账号建立成管理员，即可看到以前设定的脚本了（无法找回修账号，删除掉在重新建立即可）

注册了一个新账号，进入容器，把新账号设置成管理员 `python ./chrole.py 注册邮箱(该用户必须已经注册) admin`，然后登录站点可以找到用户管理，修改密码即可。
