### ISSUE TITLE
使用邮箱服务网站会崩溃

### ISSUE THREAD

**Issue by WUTOM123** [qd-today/qd#104]
小水管的网站上使用了cloudflare cdn'服务 证书为那网站那个免费的。  其他服务基本没问题（有的不知道是不是我签到过了会报错)，   输入邮箱 重置密码  网站直接崩溃连不上了 524 504 502等也无法ip+端口连接，注册需要验证邮箱也会，自己也无法收到签到成功/失败邮件。 要等一段时间才会正常

配置邮箱方式为docker run -d --name qiandao -p 9845:80 -v $(pwd)/qiandao/config:/usr/src/app/config --env MAIL_SMTP=smtp.office365.com --env MAIL_PORT=587 --env MAIL_USER=adada@outlook.com --env MAIL_PASSWORD=123456 --env DOMAIN=www.域名.com asdaragon/qiandao
日志为
![错误1](https://user-images.githubusercontent.com/80189267/128020666-0d6e402a-7092-4a5d-a229-0bb3cadf7775.png)
进入容器修改那个配置那个conxxx.py 重启容器也这样 
上面那个为自己域名 下面同配置方式修改 下面的mail.qiandao.today 未改
![修改后](https://user-images.githubusercontent.com/80189267/128021846-291830e9-2af9-4543-8646-2db205b8cfaf.png)
错误同上
nginx 配置如下  专业无关 不知道是不是配错了 或者需要加个转发？
![nginx](https://user-images.githubusercontent.com/80189267/128022846-168e1a51-c30b-4c13-8301-29cb84b5ba6c.png)
最后用SQLiteStudio把数据库文件的管理员邮箱的邮箱验证改成1 并且勾上必须验证邮箱
尝试忘记密码和注册新账号 仍然出现该问题，日志差不多

**Comment by wrb233** [comment]
可以增加对有赞商城开得店铺的签到功能吗？？

**Comment by a76yyyy** [comment]
请问更新至最新镜像后还出现这个问题么？

**Comment by a76yyyy** [comment]
已查明，发送邮件函数之前版本为阻塞函数，当邮箱配置错误时发送邮件会导致卡死，现已修复该bug，已在最新源码上部署，docker镜像几日后发布。
请更新版本并检查邮箱配置问题

**Comment by lazureice** [comment]
@a76yyyy 
使用最新版，我依然会崩溃。
```
[I 220331 17:48:47 utils:251] send mail to fazureki@gmail.com
[E 220331 17:57:29 utils:258] send mail error [Errno 99] Address not available
```

**Comment by lazureice** [comment]
@a76yyyy 
使用最新版，我依然会崩溃。

使用 **outlook** 邮箱。
![image](https://user-images.githubusercontent.com/12579737/161030724-1cb5c818-55b7-483c-b7f6-071937c2f529.png)

日志：
```
[I 220331 17:48:47 utils:251] send mail to xxx@gmail.com
[E 220331 17:57:29 utils:258] send mail error [Errno 99] Address not available
```
但我确定邮箱是存在的。

**Comment by MrLiuGangQiang** [comment]
我这也是 一直报SSL错误 确定邮箱都是没问题的
