### ISSUE TITLE
请问会支持ipv6吗？（后续：ipv6反代后访问会出现500错误）

### ISSUE THREAD

**Issue by ckx000** [qd-today/qd#109]
一开始在群晖docker下无法通过ipv6访问qiandao，还以为是群晖docker的锅，最后解决了群晖docker的v6问题发现还是不能访问，
然后突然发现参数里有Bind ipv4格式的设定，作死改成了v6的 发现能使用ipv6访问了。但是登录和注册页面会出现500错误，且v4地址也无法登陆了。
请问后续会添加v6的完整支持吗？

**Comment by ckx000** [comment]
ipv6外网无法访问docker内容器qiandao的问题 直接用群晖开个反代就解决了，就可以实现外网ipv6访问ipv4的容器的服务。
也就是说不需要考虑qiandao改成bind ipv6地址。。这样至少在内网里用ipv4访问qiandao是没有任何问题的

但是ipv6的外网访问 出500的问题依旧 即使外网使用绑定了域名的ipv6来访问，也会同样报错
[asdaragon-qiandao1.zip](https://github.com/AragonSnow/qiandao/files/7026031/asdaragon-qiandao1.zip)
传了下报错log 供大佬有空看看

**Comment by asdaragon** [comment]
@ckx000  应该不会，我没有ipv6的环境

**Comment by ckx000** [comment]
> @ckx000 应该不会，我没有ipv6的环境

幸苦大佬了，期待大佬以后有ipv6用。
另外借地问下 大佬有相关的模板编写教程吗？网上搜了一堆没搜到，或者大佬能推荐一个相关讨论的地方吗？

**Comment by a76yyyy** [comment]
在docker的shell中，执行`pip install ipaddress`
修改docker环境内/usr/src/app/libs/utils.py
将如下函数：
```
def ip2int(addr):
    return struct.unpack("!I", socket.inet_aton(addr))[0]

def int2ip(addr):
    return socket.inet_ntoa(struct.pack("!I", addr))
```
修改为：
```
def ip2int(addr):
    try:
        return struct.unpack("!I", socket.inet_aton(addr))[0]
    except:
        import ipaddress
        return int(ipaddress.ip_address(addr))

def int2ip(addr):
    try:
        return socket.inet_ntoa(struct.pack("!I", addr))
    except:
        import ipaddress
        return str(ipaddress.ip_address(addr))
```

**Comment by ckx000** [comment]
> 在docker的shell中，执行`pip install ipaddress`
> 修改docker环境内/usr/src/app/libs/utils.py
> 将如下函数：
> 
> ```
> def ip2int(addr):
>     return struct.unpack("!I", socket.inet_aton(addr))[0]
> 
> def int2ip(addr):
>     return socket.inet_ntoa(struct.pack("!I", addr))
> ```
> 
> 修改为：
> 
> ```
> def ip2int(addr):
>     try:
>         return struct.unpack("!I", socket.inet_aton(addr))[0]
>     except:
>         import ipaddress
>         return int(ipaddress.ip_address(addr))
> 
> def int2ip(addr):
>     try:
>         return socket.inet_ntoa(struct.pack("!I", addr))
>     except:
>         import ipaddress
>         return str(ipaddress.ip_address(addr))
> ```

先谢大佬的指点
使用大佬后续提供的命令pip install --index https://pypi.tuna.tsinghua.edu.cn/simple ipaddress
（原本命令超时链接错误了）
同时后续被指导使用改进的代码。修改为
def ip2int(addr):
    try:
        return struct.unpack("!I", socket.inet_aton(addr))[0]
    except:
        import ipaddress
        return int(ipaddress.ip_address(unicode(addr)))

def int2ip(addr):
    try:
        return socket.inet_ntoa(struct.pack("!I", addr))
    except:
        import ipaddress
        return str(ipaddress.ip_address(addr))


重启了nas与docker。。问题还是依旧 报错还是有。只不过报错问题指向数据库了。
“OverflowError: Python int too large to convert to SQLite INTEGER ”
再次提供日志供大佬们参考
[qiandao.zip](https://github.com/AragonSnow/qiandao/files/7078009/qiandao.zip)
最后 运行环境是DSM 6.2.3-25426 Update 3
Docker为套件中心的20.10.3-0554
qiandao为20210628

**Comment by a76yyyy** [comment]
最新版本框架已支持
