### ISSUE TITLE
管理员没法验证邮箱。

### ISSUE THREAD

**Issue by yeyinghai** [qd-today/qd#110]
![image](https://user-images.githubusercontent.com/15318670/130941454-4cbacebf-e409-4c2c-988e-7a2bf996779c.png)

**Comment by a76yyyy** [comment]
可以通过数据库设置或者在第一次注册用户前先配置好local_config.py文件中的邮箱配置，手动点击验证按钮开发ing

**Comment by a76yyyy** [comment]
可以通过数据库设置或者在第一次注册用户前先配置好local_config.py文件中的邮箱配置，手动点击验证按钮开发ing

**Comment by yeyinghai** [comment]
我用的docker容器，里面只有一个数据库文件，没有py文件。

**Comment by a76yyyy** [comment]
docker容器启动时使用该命令
`docker run -d --name qiandao -p 8923:80 -v $(pwd)/qiandao/config:/usr/src/app/config --env MAIL_SMTP=STMP服务器 --env MAIL_PORT=邮箱服务器端口 --env MAIL_USER=用户名 --env MAIL_PASSWORD=密码 --env DOMAIN=域名 a76yyyy/qiandao`

**Comment by a76yyyy** [comment]
在开启邮箱验证服务后，新注册一个账号，并设置为管理员账号，打开网站设置必须验证邮箱，再用旧账号登录就会给你邮箱发验证码，点击后通过即可
