### ISSUE TITLE
Error 111 connecting to localhost:6379. Connection refused.这个有影响吗？

### ISSUE THREAD

**Issue by ddd-zero** [qd-today/qd#115]
WEB部署的 跟着教程走，也没该什么配置文件，装完环境直接python ./run.py 运行。
现在8923已经能在外网访问了，但是有一条黄色的提示，数据库好像被拒绝了，不知道是否有影响。但现在注册用户什么的都是正常的。。不知道这条是干嘛意思的
![QQ截图20210903171850](https://user-images.githubusercontent.com/57771987/131982408-7671a517-1bf7-413f-a1d8-1f3b6fb4eea3.png)

**Comment by a76yyyy** [comment]
这个是连接redis产生的报错，如不需要redis请忽略
