### ISSUE TITLE
问两个问题：代理与docker镜像

### ISSUE THREAD

**Issue by billypon** [qd-today/qd#118]
1、代理

代理需要依赖pycurl，否则会报错的，所以之前我提交关于代理的代码，其实会检测是否有pycurl，如果找不到pycurl就不应用代理，避免报错。原来的镜像中是不包含pycurl的，是否在新版镜像中集成pycurl？

2、docker镜像

现在好像不发新版镜像了，改由a76yyyy发镜像？？？

**Comment by a76yyyy** [comment]
1.新版镜像已经预装了pycurl所需的curl环境，由于代理功能目前还不完善，因此默认不启用代理功能，需要使用请手动安装pycurl

2.asdaragon/qiandao为python2版，
a76yyyy/qiandao为python3版，目前python3版由我维护

**Comment by billypon** [comment]
@a76yyyy 
1. 代理功能现在还有什么问题吗？我使用代理没有什么问题呀，是需要进一步调整代理功能的实现？
2. 发现你更新镜像很频繁，asdaragon都很久没更新了

**Comment by a76yyyy** [comment]
1. 主要是因为存在功能上的不完善——任务设置代理后，任务内全部连接均通过代理通道，导致部分环境下localhost的链接失败或签到失败，目前考虑做以下功能：

- 任务级黑白名单: 在新建和修改任务界面，添加两个文本框以允许用户设置哪些域名或链接走代理，哪些不走

- 在模板界面: 每个链接内添加一个选项开关以允许用户设置是否通过代理，同时允许通过复选框来控制多个链接的开关

上面两个功能在考虑做哪个合适，或者两个都做的话，优先级怎么设置；

你可以发表一下你的看法，或者直接帮忙开发一下o(￣▽￣)ｄ 

2. 目前主要是一些细节上优化和逻辑梳理，以及反馈bug的修复，所以更新比较频繁

**Comment by billypon** [comment]
@a76yyyy 

对于localhost的问题，这个好解决，只要判断如果是localhost，就默认都不走代理就可以了，不过这个方法对于那些要走内网的请求无解。不过走内网毕竟是少数，所以默认localhost不走代理可以解决大部分的问题。

黑白名单可以解决走内网的问题，不过仍然解决不了哪个链接走哪个代理，就是配置多代理，不同链接走不同的代理。

对于这个问题，我建议不需要考虑太多，先解决localhost的问题，之后如果有更多的需求，然后再考虑黑白名单或多代理。

But，仍然觉得奇怪，默认大家也没启用代理，应该不影响localhost，不至于镜像里要取消pycurl呀。应该是不启用代理pycurl也会有影响，那才需要取消吧？？

**Comment by a76yyyy** [comment]
目前只是一个策略，pycurl所需的curl环境在docker中已经构建好了，因此在docker中只需执行`pip install pycurl`即可正常使用；

但是通过源码使用框架的用户，会因为比如pycurl在windows环境下没有curl或无法编译等各种问题安装失败，或者用户自行构建的curl环境没有支持gzip解压等原因导致框架产生500或599等错误，因此综合考虑源码构建和镜像的一致性才默认不预装pycurl；

后续会在dockerfile中另行添加`pip install pycurl`来在镜像中预装pycurl模组。
