### ISSUE TITLE
签到出现错误 无法正常使用

### ISSUE THREAD

**Issue by rangerwill** [qd-today/qd#12]
使用如下命令在openwrt x64上运行了您的docker
docker run -d --name qiandao -p 86:80 -v /opt/qiandao/config:/usr/src/app/config  asdaragon/qiandao

无法正常使用

百度贴吧签到报错
failed at 2/2 request, , http://tieba.baidu.com/tbmall/onekeySignin1
顺丰签到报错
failed at 1/1 request, error:error(111, 'Connection refused'), https://i.sf-express.com/service/new/member/checkin
b站主站签到报错
failed at 1/2 request, error:error(111, 'Connection refused'), https://account.bilibili.com/site/home.html

大佬辛苦了！
谢谢

**Comment by asdaragon** [comment]
@rangerwill Connection refused 一般是网络问题，是否防火墙没有放行之类的。贴吧一键那个，重复签到会报错。
