### ISSUE TITLE
希望能加入失败后尝试次数和是否自动禁用任务开关

### ISSUE THREAD

**Issue by DoonyL** [qd-today/qd#123]
我现在有个任务是关键词监测通知，每天检查一个网页，如果出现关键词，判断为成功，然后发推送通知。问题是没有监测到就判断失败，尝试几次之后就自动禁用任务了。希望能加入失败后尝试次数，尝试次数结束后不自动禁用任务。

**Comment by a76yyyy** [comment]
功能已添加至a76yyyy/qiandao仓库，请通过源码更新后试用，如有bug请及时反馈
