### ISSUE TITLE
请问怎么自定义Telegram推送呢

### ISSUE THREAD

**Issue by ghost** [qd-today/qd#124]

**Comment by a76yyyy** [comment]
![image](https://user-images.githubusercontent.com/56478790/133618456-890dd5f9-9885-430c-9028-13a3bb7d1792.png)

**Comment by ghost** [comment]
请问代码应该怎么写呢 尝试了一晚上也没研究明白

**Comment by a76yyyy** [comment]
最新源码已支持tg推送，请通过源码更新方式更新至最新版尝试

**Comment by hunter8605** [comment]
> 最新源码已支持tg推送，请通过源码更新方式更新至最新版尝试

12854XXX5:XXXXX1qNFaWm1aTwwU4zxNM-3xoRA;XXX;http://192.168.2.110:XXXX
分别对应TG_TOKEN,TG_USERID,代理地址
你好，这样设置无法成功完成TG推送。请问是哪里设置错了吗？

**Comment by a76yyyy** [comment]
> > 最新源码已支持tg推送，请通过源码更新方式更新至最新版尝试
> 
> 12854XXX5:XXXXX1qNFaWm1aTwwU4zxNM-3xoRA;XXX;http://192.168.2.110:XXXX 分别对应TG_TOKEN,TG_USERID,代理地址 你好，这样设置无法成功完成TG推送。请问是哪里设置错了吗？

12854XXX5:XXXXX1qNFaWm1aTwwU4zxNM-3xoRA;XXX;;http://192.168.2.110:XXXX

代理地址前要两个分号，表示tg host那个参数为空

**Comment by hunter8605** [comment]
感谢。测试成功！另外请问在模版编辑页面，如何使用代理呢？

**Comment by a76yyyy** [comment]
> 感谢。测试成功！另外请问在模版编辑页面，如何使用代理呢？

可以考虑先设置全局代理，后期再添加模板编辑页面代理功能

**Comment by hunter8605** [comment]
请问docker版本在哪里设置全局代理啊？是要把所有文件下载到对应的目录里面，然后修改配置py文件？

a76yyyyy ***@***.***> 于2022年3月2日周三 08:36写道：
