### ISSUE TITLE
url 转码解码的时候怎么能用gb2312而不是utf8呢

### ISSUE THREAD

**Issue by ddd-zero** [qd-today/qd#127]
有一个网站登陆的用户名转码的时候用的就是gb2312，utf8会乱码。就是公共模板里那个 漫画补档

**Comment by a76yyyy** [comment]
在headers中尝试使用

Content-Type:text/html;charset=gbk

或者

content-type:text/html;charset=gb2312

看一下效果

**Comment by a76yyyy** [comment]
该编码api已加入，请更新至最新源码后使用
