### ISSUE TITLE
{{}}识别有点问题

### ISSUE THREAD

**Issue by ddd-zero** [qd-today/qd#128]
{{md5("salt=b253c83ab2609b1b600eddfe974df47b&t={{ts}}&r=3Q6PHi")}}

![MGV) MIZGI5GT1{ N25%PJ](https://user-images.githubusercontent.com/57771987/133865685-c86b78eb-c2d7-49ef-9379-f84d3bd2aeb3.png)

后边的直接不识别了。

**Comment by asdaragon** [comment]
@ddd-zero  jinja2不识别嵌套，变量里调用变量好像是直接使用就行了

**Comment by ddd-zero** [comment]
> @ddd-zero jinja2不识别嵌套，变量里调用变量好像是直接使用就行了

能举个例子吗？
你的意思是
{{md5("salt=b253c83ab2609b1b600eddfe974df47b&t=ts&r=3Q6PHi")}}
这样么

测试了一下好像不行

**Comment by asdaragon** [comment]
![image](https://user-images.githubusercontent.com/22835918/133868683-1d2dda12-2f89-4528-8050-79d9a57d56cc.png)
这个结果符合预期吗

**Comment by AragonSnow** [comment]
ts=123

**Comment by asdaragon** [comment]
ts=789

**Comment by ddd-zero** [comment]
> ![image](https://user-images.githubusercontent.com/22835918/133868683-1d2dda12-2f89-4528-8050-79d9a57d56cc.png)
> 这个结果符合预期吗

能算出来应该就是对的，你这个是一部就算出来的吗？。我现在是分两步算的，先把里面要加md5的用别的xmd5变量表示，然后再去除{{}}和"" 也能出结果
![1AX0 Z16QB24M~DRVHG@L85](https://user-images.githubusercontent.com/57771987/133868759-ba04504e-0ff0-4595-b799-f09cd18ddfe0.png)
![6GK%{BEWLIF2043T`MU(D48](https://user-images.githubusercontent.com/57771987/133868762-24474f4c-5c23-49cd-b84c-0d5e2f5382b1.png)

**Comment by asdaragon** [comment]
![image](https://user-images.githubusercontent.com/22835918/133868822-f88f7d4e-b03a-4648-bc98-0c944bca5b6d.png)

**Comment by ddd-zero** [comment]
没太懂这样，倒一手到底是干嘛的- -这样替换之后不是没变吗

**Comment by a76yyyy** [comment]
双引号内是字符串，当然不可能被识别为变量

可以尝试使用replace来将字符串中的"ts"替换为ts变量值，
```
{{md5("salt=b253c83ab2609b1b600eddfe974df47b&t=ts&r=3Q6PHi"|replace("ts",ts))}}
```

![image](https://user-images.githubusercontent.com/56478790/135057006-a8e004a8-a4df-487a-a27d-7657f411a789.png)

或者直接这样
```
{{md5("salt=b253c83ab2609b1b600eddfe974df47b&t="+ts+"&r=3Q6PHi")}}
```

![image](https://user-images.githubusercontent.com/56478790/135059869-fd27ee30-d214-4861-9a83-b8b16d6fa533.png)
