### ISSUE TITLE
请问企业微信推送，如何自定推送图片？

### ISSUE THREAD

**Issue by captcao** [qd-today/qd#130]
我按照下列说明操作：

企业微信，用;来分割，##企业ID;应用ID;应用密钥;**自定推送图片(非必需)**##

自定推送图片我用的是企业微信图库中得media_id

可以得到推送文字，但是图片收不到。

请教正确得推送图片方法。

**Comment by a76yyyy** [comment]
图片要填url，尝试用上传图床

**Comment by captcao** [comment]
已成功，感谢！

**Comment by CC342** [comment]
> 已成功，谢谢！

你好，请问下怎么成功的，我还是失败。就算是把文件上传容器，然后更改原文件的名称，还是失败。
用企业微信图片的地址也是错误，请求帮助。

**Comment by captcao** [comment]
要其他网站做图床给个URL链接地址





------------------ 原始邮件 ------------------
发件人: CC342 ***@***.***&gt;
发送时间: 2022年3月27日 11:22
收件人: qiandao-today/qiandao ***@***.***&gt;
抄送: captcao ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [qiandao-today/qiandao] 请问企业微信推送，如何自定推送图片？ (#130)





  
已成功，谢谢！
  
你好，请问下怎么成功的，我还是失败。就算是把文件上传容器，然后更改原文件的名称，还是失败。
 用企业微信图片的地址也是错误，请求帮助。
