### ISSUE TITLE
用的群晖Docker，签到版本20211010，公共模板点击订阅后内容为空及AES KEY问题

### ISSUE THREAD

**Issue by jerrell851** [qd-today/qd#132]
问题一：配置AES KEY及COOKIE KEY参数后，签到页面首页能打开，但点击登陆后，会出现500服务器错误。删除这两个参数即是正常的。

问题二：公共模板处，点击模板旁边的订阅按钮，弹出链接http://xxx.xxx/har/edit?reponame=default&name=%E6%8E%98%E9%87%91.har，这个页面里面无任何内容。如图：

![2021-10-15_094632](https://user-images.githubusercontent.com/61078121/137419250-58a2fedc-3d87-4b99-bfba-0c13f76059dc.jpg)

日志提取如下：

[logs.txt](https://github.com/qiandao-today/qiandao/files/7350316/logs.txt)

**Comment by a76yyyy** [comment]
问题一:AES_KEY 和 COOKIE_KEY参数必须在全新安装框架前配置，当框架初始化后修改值均会报错

问题二: 该问题已修复，请等待发布新镜像，或使用源码方式更新

**Comment by a76yyyy** [comment]
已发布docker
