### ISSUE TITLE
无法将签到任务的重试次数设为0

### ISSUE THREAD

**Issue by gelidrain** [qd-today/qd#133]
![image](https://user-images.githubusercontent.com/40741783/137636496-2322c5f7-61dd-465d-810b-2b81022e1270.png)
作者大大，我想设置签到任务失败时不重试，尝试将“重试次数”设为0，点击“提交”，但再次点击“修改”按钮时，“重试次数”的前值还是原来的值。在新建任务时设置重试次数也会出现这样的问题。

**Comment by a76yyyy** [comment]
已修复，请通过源码更新或等待过段时间发布docker镜像
