### ISSUE TITLE
[Bug]自定义推送有BUG

### ISSUE THREAD

**Issue by maplejaw** [qd-today/qd#134]
自定义推送使用POST-x-www-form-urlencoded方式时，标准的表单内容格式应该为：k1=v1&k2=v2 这种。但是我看源码直接当作json来处理了，导致没法使用这种方式自定义推送。
```python
            if (diypusher['mode'] == 'POST'):
                postDatatmp = diypusher['postData'].replace('{log}', log).replace("{t}", t).replace("\\r\\n","\r\n" )
                if (postDatatmp != ''):
                    postDatatmp = json.loads(postDatatmp)
```

**Comment by a76yyyy** [comment]
![20211026105137](https://user-images.githubusercontent.com/56478790/138800864-469b44e2-9de7-48b0-9f0a-c784f57a9186.png)
![image](https://user-images.githubusercontent.com/56478790/138801088-f62450c4-d691-461c-8339-81aeca574f94.png)

**Comment by a76yyyy** [comment]
自定义推送无法使用请展示推送格式及内容

**Comment by maplejaw** [comment]
> 自定义推送无法使用请展示推送格式及内容
找到问题了，json格式换成双引号就可以了，我按照提示 `使用json格式，如{'a':'{log}','c':'{t}'}`，输入的单引号会报错。

**Comment by a76yyyy** [comment]
请更新至最新版镜像或源码，该错误提示在早期版本已修复

**Comment by maplejaw** [comment]
> 请更新至最新版镜像或源码，该错误提示在早期版本已修复

晕，docker拉错版本了，拉了asdaragon/qiandao，指向的是同一个GitHub，但版本不是最新的。
