### ISSUE TITLE
[Bug]win10 下使用docker启动出错

### ISSUE THREAD

**Issue by creboy** [qd-today/qd#139]
**Describe the bug**
启动时提示python: can't open file '/usr/src/app/run.py': [Errno 2] No such file or directory

**Comment by a76yyyy** [comment]
这边测试正常，请展示你的docker镜像相关配置信息

**Comment by creboy** [comment]
docker run -d --name qiandao -p 8923:80 -v f:/docker/qiandao/config:/usr/src/app/config a76yyyy/qiandao sh -c "redis-server --daemonize yes && python /usr/src/app/run.py"
![image](https://user-images.githubusercontent.com/27350646/139819620-e7c06873-27df-4f97-8c43-2da4879a119b.png)

**Comment by a76yyyy** [comment]
可能误删除容器卷，请删除容器后重新拉取镜像尝试

**Comment by a76yyyy** [comment]
我这边确实没有复现出来，请检查是否和wsl2或hyperV等组件不完整、docker环境问题等有关
