### ISSUE TITLE
能否使用变量设置 smtp？

### ISSUE THREAD

**Issue by loveqianool** [qd-today/qd#14]
像端口可以用 -e PORT='8080' 修改。

那 mail_smtp 甚至 管理员账户 能不能使用变量提前设置呢？

因为我把 qiandao，部署在 https://app.kintohub.com/ 平台，而在这里我无法进入容器内修改 mail_smtp。

**Comment by asdaragon** [comment]
设置管理员账户因为需要权限的问题，不会支持web设置。邮箱可以，不过最近没空，预计下个月更新。
@loveqianool 这种平台你可以fork项目设置为私人项目，修改变量即可
