### ISSUE TITLE
[Bug][linux/arm32]docker镜像无法成功启动

### ISSUE THREAD

**Issue by Stone-Crown** [qd-today/qd#142]
**Describe the bug**
原来用的是asdaragon/qiandao的镜像，一直到20210626版本都是可以正常启用的
尝试更新你的版本不论是最早的20210905版本还是20211102 or latest 均无法启动
**Expected behavior**

希望能够适配一下
硬件主体是玩客云
软件信息如下
Docker version 18.09.1, build 4c52b90
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Sun, 14 Jun 2020 22:12:29 +0200
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Sun Jun 14 20:12:29 2020
  OS/Arch:          linux/arm
  Experimental:     false

Python 3.7.3

Welcome to Debian GNU/Linux 10 (buster) with Linux 5.9.0-rc7-aml-s812
参见 https://www.right.com.cn/forum/thread-4057492-1-1.html

启动信息如下

CONTAINER ID        IMAGE                         COMMAND                  CREATED              STATUS                      PORTS                  NAMES
83058bbf5587        a76yyyy/qiandao:20211102      "sh -c 'redis-server…"   About a minute ago   Exited (1) 24 seconds ago                          qiandao2

Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6f52390 (most recent call first):
<no Python frame>

不知道是因为cpu是32位不支持还是因为python版本不够高又或者是docker版本问题，使用的应该是docker io。

**Comment by a76yyyy** [comment]
Please See linuxserver/docker-domoticz#88
> [BUG] Fatal Python Error: pyinit_main: can't initialize time
> ```
> This issue is SOLVED by an issue on a different container, but I've placed it here for any googlers ending up here. The solution can be found on https://docs.linuxserver.io/faq
> 
> ISSUE
> Running crisp new instance on an RPi 4 (Debian), 2GB.
> 
> After starting the container, the logs show: domoticz | Fatal Python error: pyinit_main: can't initialize time domoticz | Python runtime state: core initialized domoticz | PermissionError: [Errno 1] Operation not permitted
> 
> SOLUTION
> https://docs.linuxserver.io/faq
> 
> REFERENCE
> https://github.com/linuxserver/docker-papermerge/issues/4
> 
> CONCLUSION
> This error has been fixed and now I get a different one (500 internal server error), but I'll analyze this one before opening a new issue.
> ```

这个是docker与系统依赖的问题，详细解决办法请参考[https://docs.linuxserver.io/faq](https://docs.linuxserver.io/faq)

或许升级docker至最新版本可能会解决你的问题

**Comment by Stone-Crown** [comment]
已经参照[ ](https://docs.linuxserver.io/faq)更新了 
libseccomp2 is already the newest version (2.5.1-1~bpo10+1).
但是没有任何效果报错信息相同Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6f24390 (most recent call first):
<no Python frame>

想尝试更新docker版本却不知从何途径！

**Comment by a76yyyy** [comment]
> 已经参照[ ](https://docs.linuxserver.io/faq)更新了 libseccomp2 is already the newest version (2.5.1-1~bpo10+1). 但是没有任何效果报错信息相同Fatal Python error: pyinit_main: can't initialize time Python runtime state: core initialized PermissionError: [Errno 1] Operation not permitted
> 
> Current thread 0xb6f24390 (most recent call first):
> 
> 想尝试更新docker版本却不知从何途径！

https://www.runoob.com/docker/debian-docker-install.html 可能会对你有所帮助

**Comment by Stone-Crown** [comment]
通过更新docker版本libseccomp2 已解决问题，谢谢！
