### ISSUE TITLE
[Bug]公共模板添加错误的分支会无限2更新

### ISSUE THREAD

**Issue by lqbby** [qd-today/qd#143]
公共模板添加错误的分支会无限更新
http://tk.lqbby.host/20211113/431ce52089ac4.png

**Comment by a76yyyy** [comment]
最新源码已更新该问题，暂未发布docker，请先进入容器后台后执行
`sh update.sh -f`强制更新至最新源码以解决此问题

**Comment by lqbby** [comment]
> 最新源码已更新该问题，暂未发布docker，请先进入容器后台后执行
> `sh update.sh -f`强制更新至最新源码以解决此问题

感谢已经恢复
