### ISSUE TITLE
[Bug]无法通过adguardhome解析url

### ISSUE THREAD

**Issue by Stone-Crown** [qd-today/qd#144]
**Describe the bug**
我在dokcer中部署了qiandao和adguardhome，在配置后adguardhome也正常工作，但似乎qiandao就无法正常解析网址了。
当我将主路由的DNS指向从adguardhome改回主路由，并重启docker宿主后，qiandao可以正常解析了。
adguardhome启动命令如下
docker run --name adguardhome\
    --restart unless-stopped\
    -v /root/AdguardHome/workdir:/opt/adguardhome/work\
    -v /root/AdguardHome/confdir:/opt/adguardhome/conf\
    -p 53:53/tcp -p 53:53/udp\
    -p 67:67/udp \
    -p 80:80/tcp -p 443:443/tcp -p 443:443/udp -p 3000:3000/tcp\
    -p 853:853/tcp\
    -p 784:784/udp -p 853:853/udp -p 8853:8853/udp\
    -p 5443:5443/tcp -p 5443:5443/udp\
    -d adguard/adguardhome
qiandao
启动命令如下
docker run -d --name qiandao -p 3067:80 -v $(pwd)/qiandao/config:/usr/src/app/config a76yyyy/qiandao:20211102

docker宿主机可以在指向adg后可以正常ping通域名，但qiandao就是没法ping通域名，只能ping通ip。

![ping](https://user-images.githubusercontent.com/16874655/141825325-f489d190-14f2-4516-8893-42700b314504.png)

宿主机和qiandao的dns 指向都是 adg,也就是docker的宿主机的ip 

![dns 指向](https://user-images.githubusercontent.com/16874655/141825355-a907c9bf-4383-4b10-8bdf-1cc174ab2e94.png)
路由器和docker的网络信息如下

![docker 网络信息](https://user-images.githubusercontent.com/16874655/141825391-82964367-b29c-4da1-b23c-ec48579080d6.png)

![路由器配置](https://user-images.githubusercontent.com/16874655/141825433-08f91eb3-1a96-4479-822e-a0261d6b0a1c.png)
签到任务报错如下
![签到](https://user-images.githubusercontent.com/16874655/141825449-632fc25e-eaa2-4667-8637-df9904709e33.png)

在 adg中查看日志，发现是正常解析
![解析](https://user-images.githubusercontent.com/16874655/141825466-f915f0b2-873c-44fc-b208-b1659a994cc9.png)

我的理解是adguardhome通过dns解析完成广告拦截的，但在拦截记录中并没有签到的拦截记录。
实在是搞不清楚原因，求助各位大佬！

**Comment by a76yyyy** [comment]
签到内可以ping通adguardhome的ip地址么？

**Comment by Stone-Crown** [comment]
无回应。
经过以下步骤
打开网卡混杂模式 :ip link set eth0 promisc on
创建网络: network create -d macvlan --subnet=192.168.2.0/24 --gateway=192.168.2.1 -o parent=eth0 macnet
给adguardhome 指定ip: docker run --name adguardhome --restart unless-stopped --network macnet --ip x.x.x.x .......
然后参考下面的帖子
https://www.right.com.cn/forum/thread-1066223-1-1.html

armbian的动态macvlan设置，同时打通armbian宿主机对adguardhome的访问
#iface eth0 inet dhcp
auto eth0
iface eth0 inet manual

auto macvlan
iface macvlan inet dhcp
  pre-up ip link add macvlan link eth0 type macvlan mode bridge
  post-down ip link del macvlan link eth0 type macvlan mode bridge
