### ISSUE TITLE
[Bug]钉钉推送无效么？

### ISSUE THREAD

**Issue by chenyz1984** [qd-today/qd#147]
**Describe the bug**
对Bug本身清晰而简洁的描述.

**To Reproduce**
复现此Bug的步骤:

**Expected behavior**
对预期修复后情况的清晰明了的描述.

**Screenshots**
添加屏幕截图以帮助解释您的问题.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
添加有关此问题的任何描述.

**Comment by a76yyyy** [comment]
请清晰描述你的问题

**Comment by a76yyyy** [comment]
当前测试正常
![image](https://user-images.githubusercontent.com/56478790/143826817-4fc02c53-dde2-4b58-b89d-3a3654908420.png)


![image](https://user-images.githubusercontent.com/56478790/143826775-280432a4-60cf-424b-ac49-cdbd3d51b488.png)

**Comment by chenyz1984** [comment]
DINGDING_TOKEN需要填写哪个值？access_toke？还是完整的webhook地址？

**Comment by pengkaiwei** [comment]
> DINGDING_TOKEN需要填写哪个值？access_toke？还是完整的webhook地址？

关键词不能填签到，因为测试的消息里 没有“签到”

**Comment by a76yyyy** [comment]
> DINGDING_TOKEN需要填写哪个值？access_toke？还是完整的webhook地址？

字面意思，accesstoken

**Comment by a76yyyy** [comment]
> 关键词不能填签到，因为测试的消息里 没有“签到”

日志推送里是包括"签到"关键词的，你可以同时添加"签到"，"测试"两个关键词
