### ISSUE TITLE
[Feature] 支援gotify推送

### ISSUE THREAD

**Issue by cc9014** [qd-today/qd#148]
**Is your feature request related to a problem? Please describe.**
目前使用的腾讯云不支持TG

**Describe the solution you'd like**
希望增加Gotify的推送，“自定义推送”不会配置……
[https://gotify.net/docs/more-pushmsg](url)

**Comment by a76yyyy** [comment]
请先在容器内执行 `sh update.sh -f` 强制更新签到框架源码后，按照如下操作
![image](https://user-images.githubusercontent.com/56478790/144204358-f9d09b0b-882a-4b9c-99c4-5f3878ae88ed.png)
```
URL= http://你的Gotify地址:端口号/message?token=<apptoken>
POST_DATA= {"message": "{log}","priority": 2,"title": "{t}"}
```
