### ISSUE TITLE
推送能否增加 alertover 以及 企业微信

### ISSUE THREAD

**Issue by loveqianool** [qd-today/qd#15]
https://www.alertover.com/pages/api

https://work.weixin.qq.com/api/doc/90001/90143/90372

**Comment by asdaragon** [comment]
我都没账号，后续会加个自定义推送的接口，自己根据api说明添加就行了

**Comment by if1y** [comment]
自定义 GET / POST 应该是最灵活的，我想加 Telegram Bot 推送

**Comment by hecarli555** [comment]
跪求大佬开发企业微信的推送，这样就可以放弃bark了

**Comment by asdaragon** [comment]
已经添加自定义推送的接口，自己研究怎么添加对应的API吧

**Comment by loveqianool** [comment]
> 已经添加自定义推送的接口，自己研究怎么添加对应的API吧

docker hub 需要更新。

**Comment by hecarli555** [comment]
> > 已经添加自定义推送的接口，自己研究怎么添加对应的API吧
> 
> docker hub 需要更新。

我重新拉取镜像并清除了，但是版本还是1222版本。。。要如何更新？

**Comment by if1y** [comment]
> > > 已经添加自定义推送的接口，自己研究怎么添加对应的API吧
> > 
> > 
> > docker hub 需要更新。
> 
> 我重新拉取镜像并清除了，但是版本还是1222版本。。。要如何更新？

容器要移除，旧的镜像也要删除。
不过目前作者仓库还是1222版，所以重 pull 也没有用。

**Comment by shange1993** [comment]
@AragonSnow 希望增加钉钉推送
