### ISSUE TITLE
[Bug]任务结果邮件通知无法正常收到邮件

### ISSUE THREAD

**Issue by lixh00** [qd-today/qd#151]
**Describe the bug**
```
[I 211207 11:40:00 worker:106] Success push batch log for xxxxxxx
```
系统日志显示邮件已经发出去了，但是实际上并没有收到邮件，检查发信的邮箱的发件箱，也没看到有发信记录，测试邮件发送是正常的，因为能收到重置密码的邮件。
如图所示，全部邮件都收不到。
![微信截图_20211207115505](https://user-images.githubusercontent.com/72033265/144963403-d3b9d5be-155c-4609-8b31-c24f252108ad.png)

**To Reproduce**
复现此Bug的步骤:

**Expected behavior**
对预期修复后情况的清晰明了的描述.

**Screenshots**
添加屏幕截图以帮助解释您的问题.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
添加有关此问题的任何描述.

**Comment by a76yyyy** [comment]
请提供包含send mail的日志信息

**Comment by a76yyyy** [comment]
注意隐藏隐私信息

**Comment by li-xunhuan** [comment]
看了一下，没有，只找到了一段重置密码的时候有

**Comment by a76yyyy** [comment]
正常情况下在
```
[I 211207 11:40:00 worker:106] Success push batch log for xxxxxxx
```
日志之前会先显示
```
send mail to xxx
```
类似的日志以表明正在发送邮件至xxx用户，请检查容器版本是否最新，前端推送设置重新设置一下

**Comment by li-xunhuan** [comment]
> 正常情况下在
> 
> ```
> [I 211207 11:40:00 worker:106] Success push batch log for xxxxxxx
> ```
> 
> 日志之前会先显示
> 
> ```
> send mail to xxx
> ```
> 
> 类似的日志以表明正在发送邮件至xxx用户，请检查容器版本是否最新，前端推送设置重新设置一下

容器确定是最新的，也设置过，但是在 `Success push xxxxx`之前确实没有 `sned mail to xxx`

**Comment by a76yyyy** [comment]
![image](https://user-images.githubusercontent.com/56478790/145328346-3583b9d6-ce02-4e81-961f-a1b349100448.png)
这是正常结果，如果没有的话请重启容器，清空浏览器缓存并重新设置前端界面推送设置后尝试

**Comment by a76yyyy** [comment]
请问可以了么，不可以的话请尝试重新配置邮箱，备份数据库后并重建容器尝试。
我先close这个issue，如果还是不可以的话请再reopen，

**Comment by li-xunhuan** [comment]
> 请问可以了么，不可以的话请尝试重新配置邮箱，备份数据库后并重建容器尝试。 我先close这个issue，如果还是不可以的话请再reopen，

不行，我放弃了

**Comment by a76yyyy** [comment]
想问一下你的邮箱验证了么？

**Comment by lixh00** [comment]
> 想问一下你的邮箱验证了么？

emmmmm
怎么验证啊，是很早之前创建的账号了，怎么验证啊
