### ISSUE TITLE
手动新增模板，上传HAR后，测试提示网络连接失败 net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by caixlcq** [qd-today/qd#152]
手动新增模板，上传HAR后，测试提示网络连接失败 ， net::ERR_CONNECTION_REFUSED
尝试了把公共模板下载下来，再上传，一样的提示网络连接失败

测试版本：20211204
搭建方案：Docker

**Comment by a76yyyy** [comment]
请提供
测试har
后台日志
以帮助复现bug

**Comment by a76yyyy** [comment]
请问可以了么，不可以的话请尝试备份数据库后重建容器尝试。
我先close这个issue，如果还是不可以的话请再reopen，

**Comment by caixlcq** [comment]
已经好了，感谢
