### ISSUE TITLE
不应该存储用户密码的 md5

### ISSUE THREAD

**Issue by binux** [qd-today/qd#155]
https://github.com/qiandao-today/qiandao/blob/cfedccafa6398843c42ccd6fc358f4055902c52c/db/user.py#L56

md5 的强度太低了，而且也没有加盐，这密码就和明文没什么区别。导致 PBKDF2 的计算成本变得没有意义。

**Comment by a76yyyy** [comment]
事实上，在用户注册的时候原始代码甚至是明文传输的，这里需要考虑的还有如何在保证向下兼容的情况下对当前数据库以及注册登录等相关的密文处理有一个妥善而合适的改进。
PS：项目仓库也对binux大佬您发起了邀请，现在还在pending中，如果大佬有想法的话可以同意一下邀请然后提交一个合适的commit

**Comment by binux** [comment]
HTTP传输安全不是应用需要考虑的问题，前面套个HTTPS就可以了。
你可以参考下 crypt util 的实现，那是当年的best practice（以我的了解）。整个数据库设计是数据库泄露不会导致用户tpl和task中的密码泄露。

我不是很有时间，只是看到这个问题就提了下。

**Comment by a76yyyy** [comment]
可以先加入，有空了方便随时提交自己改进的commit

**Comment by a76yyyy** [comment]
已尝试解决
