### ISSUE TITLE
[Bug]签到后，获取的日志不完整。

### ISSUE THREAD

**Issue by Troray** [qd-today/qd#164]
嗯，这个严格来说应该不算bug，应该是字符截取数太少了。能否增加一下。
例如什么值得买，后面还有一部分被截断了。
_日志_
![日志](https://i.imgur.com/pojbGxc.png)

_值得买消息_
![smzdm](https://i.imgur.com/7904Ear.png)

**Comment by a76yyyy** [comment]
这个是模板的问题，不是框架的问题
请前往模板库“[什么值得买 评论区](https://github.com/qiandao-today/templates/issues/20)” 提交问题
