### ISSUE TITLE
插入api带网址

### ISSUE THREAD

**Issue by ghost** [qd-today/qd#165]
新版插入api转换带了类似http://192.168.10.200:8823/util这样的地址，老版本是http://localhost/util/。每次都要去改成localhost，很不方便

**Comment by a76yyyy** [comment]
已修改api策略，采用api:// 作为签到API默认scheme 参见 qiandao-today/qiandao#168
请等待发布新版本或者使用`sh ./update.sh -f && pip install -r requirements.txt`强制更新源码并清空浏览器缓存后使用
