### ISSUE TITLE
 关于签到日志

### ISSUE THREAD

**Issue by ddd-zero** [qd-today/qd#172]
### Verify steps

- [x] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

![QQ截图20211227202459](https://user-images.githubusercontent.com/57771987/147471637-88442bf7-d64d-4fcb-99fd-90283f653457.png)
比如签到完成返回"{"status":0,"message":"signed","reward_type":2,"reward_value":15,"reward_name":"天使币"}"
我可否在这些返回值中直接提取“15” “天使币” 这两个参数，然后再加上一句我自定义的话，比如“签到完成”，进而凑出“签到完成,15天使币”这个日志直接进行输出呢？
目前我都是通过自己再另加一行字符串替换的API，凑成一个日志再输出。以后能否省略这个过程，直接在签到的那个请求后面直接输出呢。。

### Describe the solution

..

**Comment by a76yyyy** [comment]
直接用`插入unicode`API就可以

**Comment by a76yyyy** [comment]
请问还有什么问题么？如果还有的话请re-open这个issue，我先关闭了
