### ISSUE TITLE
mysql8连接问题

### ISSUE THREAD

**Issue by hugodel93** [qd-today/qd#173]
### Verify steps

- [X] #182
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

latest

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

使用提供的mysql启动方式

### Describe the Bug

我使用mysql 8,将连接用户加密方式改为“mysql_native_password”并且确保已生效
但是启动报错mysql.connector.errors.NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported

### QianDao log

```shell
mysql.connector.errors.NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported
```

### Expected behavior

希望可以说明对mysql 8的连接配置

**Comment by a76yyyy** [comment]
请更新源码，并在需要使用MySQL时,
设置`mysql_url` or `JAWSDB_MARIA_URL`为 `mysql://用户名:密码@hostname:port/数据库名?auth_plugin=xxx`

**Comment by a76yyyy** [comment]
可以了么？我先关闭这个issue了，如果还是不行的话请再次re-open这个issue
