### ISSUE TITLE
是否考虑增加server酱的推送详情？

### ISSUE THREAD

**Issue by micsem00** [qd-today/qd#18]
例如，获得53魔力，可用正则提取出来推送至手机

**Comment by asdaragon** [comment]
默认的推送消息是日志，你日志里有这些自然有，日志支持正则提取。
如果非要自定义一个，可以在har最后发送一个GET/POST请求，然后推送到S酱就可以了。

**Comment by micsem00** [comment]
谢谢大佬思路
