### ISSUE TITLE
[Feature] 希望能对模板内字符串一键替换功能

### ISSUE THREAD

**Issue by sunjx97** [qd-today/qd#185]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

某些站点经常更换域名，每次更换都要重新修正一遍模板，比较麻烦。

### Describe the solution

希望能增加对模板内指定字符串查找、替换、批量替换的功能。

**Comment by a76yyyy** [comment]
可以下载模板har后在本地编辑器里一键替换或者直接将需要经常更换的地方改为变量，在创建任务时手动修改

**Comment by sunjx97** [comment]
第一个方法妙啊（
