### ISSUE TITLE
Docker Image版本

### ISSUE THREAD

**Issue by rickychaw** [qd-today/qd#19]
A大您好，使用了您的docker镜像，先说声谢谢。另外想问下您最近的更新是否没有推送到dockerhub?那边拉取的镜像版本还在0709。
是否最近的版本没有推送成功？烦请修正，谢谢。
祝好

**Comment by asdaragon** [comment]
@rickychaw 
docker 推送会晚于git上，毕竟要找人测试，目前最新版有点bug还没修复，暂时没有推送计划。

**Comment by rickychaw** [comment]
好的明白了，谢谢回复。因为看见 Build Image.yml 文件已经记录到0907了，以为是推送到dockerhub出了问题.,
