### ISSUE TITLE
[Feature] 能把签到失败次数限制放宽点吗？至少管理员可以给放宽点吧

### ISSUE THREAD

**Issue by ddd-zero** [qd-today/qd#206]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

今天晚上电信的出口炸了，我有一个项目，几个小时直接就把8次尝试用完自己禁用了。。。

### Describe the solution

.......

**Comment by a76yyyy** [comment]
<img width="442" alt="1641960064(1)" src="https://user-images.githubusercontent.com/56478790/149061708-9fa51ed6-abb9-4088-b2bc-433cad2f0c21.png">
新建或修改任务时可以自行设置

**Comment by ddd-zero** [comment]
> <img width="442" alt="1641960064(1)" src="https://user-images.githubusercontent.com/56478790/149061708-9fa51ed6-abb9-4088-b2bc-433cad2f0c21.png">
> 
> 新建或修改任务时可以自行设置

可以设置重试间隔时间。但是无法突破8次重试。有时候宕机都能宕机一天多。。比如最近的馒头pt

**Comment by ddd-zero** [comment]
> <img width="442" alt="1641960064(1)" src="https://user-images.githubusercontent.com/56478790/149061708-9fa51ed6-abb9-4088-b2bc-433cad2f0c21.png">
> 
> 新建或修改任务时可以自行设置

我记得以前的版本，是按比例增加的，比如第一次1分钟，第二次10分钟，然后一小时，4小时，一天，这样。现在是改了吗？
或者增加个长效选项也行。失败超过一定次数，隔一天一试。反正别禁用就行

**Comment by a76yyyy** [comment]
> > <img alt="1641960064(1)" width="442" src="https://user-images.githubusercontent.com/56478790/149061708-9fa51ed6-abb9-4088-b2bc-433cad2f0c21.png">
> > 新建或修改任务时可以自行设置
> 
> 我记得以前的版本，是按比例增加的，比如第一次1分钟，第二次10分钟，然后一小时，4小时，一天，这样。现在是改了吗？ 或者增加个长效选项也行。失败超过一定次数，隔一天一试。反正别禁用就行

重试次数为`-1`表示默认不禁用任务，一直重试
重试间隔不填则是你说的那种按比例增加直至每天重试一次，填了的话按照填写的间隔等间隔重试

**Comment by ddd-zero** [comment]
> 

好的。懂了
