### ISSUE TITLE
[Bug] 页面的点击获取cookies按钮无效

### ISSUE THREAD

**Issue by nozomileng** [qd-today/qd#211]
### Verify steps

- [x] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20211228

### Bug on OS

Windows

### Bug on Platform

Docker/Linux 64位

### To Reproduce

页面的点击获取cookies按钮无效

### Describe the Bug

使用cookies任务里的点击获取按钮无反应

### QianDao log

```shell
无
```

### Expected behavior

点击能直接获取cookies

**Comment by a76yyyy** [comment]
现在谷歌浏览器已经调整了跨域获取cookie的策略,现在可以试试安装这个仓库的插件后使用此功能

https://github.com/ckx000/get-cookies

**Comment by nozomileng** [comment]
感谢，已解决这个问题
