### ISSUE TITLE
签到列表加个排序功能

### ISSUE THREAD

**Issue by goooxyz** [qd-today/qd#213]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

1:加个排序功能,比如按照上次成功时间,状态,下次签到时间等等来排序
2:把定时明细直接展现出来,这样就能直观的看到每个任务有没有定时

### Describe the solution

1:加个排序功能,比如按照上次成功时间,状态,下次签到时间等等来排序
2:把定时明细直接展现出来,这样就能直观的看到每个任务有没有定时

**Comment by a76yyyy** [comment]
排序功能和分组功能冲突了

如果之前单个任务定时后,点击定时按钮会显示单个任务的上一次定时操作,可以更新至最新框架源码查看

如果有什么建议或者更好的想法请reopen此issue
