### ISSUE TITLE
[Bug]  BPF_CGROUP_DEVICE failed to start containers: qiandao

### ISSUE THREAD

**Issue by BenMake** [qd-today/qd#215]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20211228

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 32位

### To Reproduce

docker start qiandao

### Describe the Bug

docker start qiandao
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: bpf_prog_query(BPF_CGROUP_DEVICE) failed: invalid argument: unknown
Error: failed to start containers: qiandao

### QianDao log

```shell
docker start qiandao
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: bpf_prog_query(BPF_CGROUP_DEVICE) failed: invalid argument: unknown
Error: failed to start containers: qiandao
```

### Expected behavior

docker version
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:00 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:44:14 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

 docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  cgroupns
 Kernel Version: 4.19.46
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: armv7l
 CPUs: 2
 Total Memory: 1003MiB
 Name: Ben-A20Cubie
 ID: GYCI:LZXN:2CMY:HIA3:ORSG:DHK2:WPZK:VDZF:XIOM:7MCO:L35O:BQPN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No cpuset support
WARNING: No io.weight support
WARNING: No io.weight (per device) support
WARNING: No io.max (rbps) support
WARNING: No io.max (wbps) support
WARNING: No io.max (riops) support
WARNING: No io.max (wiops) support

zcat /proc/config.gz   | grep -E 'CONFIG_BPF|CONFIG_FREEZER'
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
# CONFIG_BPF_JIT_ALWAYS_ON is not set
CONFIG_FREEZER=y
# CONFIG_BPFILTER is not set
CONFIG_BPF_JIT=y
# CONFIG_BPF_STREAM_PARSER is not set

**Comment by a76yyyy** [comment]
这似乎是docker的问题，尝试更新docker engine后，重启系统试试

**Comment by BenMake** [comment]
尝试过了docker一直启动不起来, 其他的库可以, 应该是和镜像的 ARMv7(armhf) platform有关, 使用py源码方式部署了

**Comment by a76yyyy** [comment]
> 尝试过了docker一直启动不起来, 其他的库可以, 应该是和镜像的 ARMv7(armhf) platform有关, 使用py源码方式部署了

可以试试`docker pull ghcr.io/qiandao-today/qiandao:latest`拉取最新源码镜像，看有没有问题

**Comment by a76yyyy** [comment]
如果还有问题请reopen这个issue，我先关了
