### ISSUE TITLE
[Bug] DingDing BOT推送渠道无法收到推送

### ISSUE THREAD

**Issue by EileenFengGu** [qd-today/qd#220]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220208

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

1. “工具箱”注册DingDing Bot推送渠道
2. 按注释内容键入对应的参数注册测试提示“设置成功，已推送,请检查是否收到。”
3. 实际无法收到相应的推送内容

### Describe the Bug

因钉钉现强制要求自定义API机器人创建时选择一项安全设置，详见：[https://open.dingtalk.com/document/robots/customize-robot-security-settings](https://open.dingtalk.com/document/robots/customize-robot-security-settings)。

### QianDao config

```shell
创建容器命令：
docker run -d --name qiandao -p 8923:80 -v $(pwd)/qiandao/config:/usr/src/app/config a76yyyy/qiandao
启动命令：
sh -c 'redis-server --daemonize yes && python /usr/src/app/run.py' 
环境变量：
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ONNXRUNTIME_TAG=master
PYCURL_SSL_LIBRARY=openssl
CURL_VERSION=master
DDDDOCR_VERSION=1.4.2
PORT=80
TZ=CST-8
```

### QianDao log

```shell
WxPusher 未填写完整
Sendkey 未填写完整
BarkUrl 未填写完整
企业微信 未填写完整
Tg Bot 未填写完整
DingDing Bot 已推送,请检查是否收到
```

### Expected behavior

实现正常DingDing BOT推送渠道推送。

### Screenshots

![dingding bot](https://user-images.githubusercontent.com/99351809/153257212-e7cd66e3-cb38-43bd-8d15-2430044d273b.jpg)

**Comment by a76yyyy** [comment]
安全设置里选择自定义关键词
关键词包括签到,成功,失败

**Comment by Shiliu-daddy** [comment]
> 安全设置里选择自定义关键词 关键词包括签到,成功,失败

是这样吗？不知道为什么也是收不到
![Snipaste_02-10_06-21](https://user-images.githubusercontent.com/67667814/153335222-90707f97-6540-42e6-b4d6-88021852fd75.JPG)

**Comment by a76yyyy** [comment]
> > 安全设置里选择自定义关键词 关键词包括签到,成功,失败
> 
> 是这样吗？不知道为什么也是收不到 ![Snipaste_02-10_06-21](https://user-images.githubusercontent.com/67667814/153335222-90707f97-6540-42e6-b4d6-88021852fd75.JPG)

再加一个 测试

**Comment by Shiliu-daddy** [comment]
> > > 安全设置里选择自定义关键词 关键词包括签到,成功,失败
> > 
> > 
> > 是这样吗？不知道为什么也是收不到 ![Snipaste_02-10_06-21](https://user-images.githubusercontent.com/67667814/153335222-90707f97-6540-42e6-b4d6-88021852fd75.JPG)
> 
> 再加一个 测试

又重新测试了， 添加一个关键词Qiandao就可以了，看了下代码中包含这个， 我添加了这个测试可以推送成功。辛苦了~

**Comment by a76yyyy** [comment]
好的，有问题再reopen这个issue

**Comment by a76yyyy** [comment]
> > > > 安全设置里选择自定义关键词 关键词包括签到,成功,失败
> > > 
> > > 
> > > 是这样吗？不知道为什么也是收不到 ![Snipaste_02-10_06-21](https://user-images.githubusercontent.com/67667814/153335222-90707f97-6540-42e6-b4d6-88021852fd75.JPG)
> > 
> > 
> > 再加一个 测试
> 
> 又重新测试了， 添加一个关键词Qiandao就可以了，看了下代码中包含这个， 我添加了这个测试可以推送成功。辛苦了~

现在可能需要改成QD了

**Comment by wzyqlxp** [comment]
还是不行，关键字都添加了，依然不行

**Comment by a76yyyy** [comment]
> 还是不行，关键字都添加了，依然不行

![image](https://github.com/qd-today/qd/assets/56478790/bf34c33f-0d9f-47a5-b6f9-d751b0c00ca3)

我这边没问题

**Comment by wzyqlxp** [comment]
> > 还是不行，关键字都添加了，依然不行
> 
> ![image](https://user-images.githubusercontent.com/56478790/239952905-bf34c33f-0d9f-47a5-b6f9-d751b0c00ca3.png)
> 
> 我这边没问题

解决了，我出了设置了关键字还要密码开起来了。后来把密码关闭后，就正常了
