### ISSUE TITLE
[Feature] Docker镜像将redis分离为单独的容器

### ISSUE THREAD

**Issue by caspershw** [qd-today/qd#224]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

Docker镜像加入Redis集成以后，体积增大了很多，如果自行部署了Redis的话也就不需要多开一个，增加额外性能开销，并且Redis也不是必须。

### Describe the solution

可以通过选装的方式分离出来（跟原版一样），`redis:6.0-alpine`这个Docker镜像只有~10M，而且也不需要额外的代码监控状态。

**Comment by a76yyyy** [comment]
是一个值得考虑的事情

**Comment by caspershw** [comment]
https://github.com/hiCasper/qiandao-today/commit/fa2f1eecbfa2667951c0cd1297f83139a6c0b048 我这里尝试重构了一下Docker部分的构建，目前来看能够正常使用，可以看一下
镜像拉取地址： registry.cn-hongkong.aliyuncs.com/spub/qiandao:latest

**Comment by acooler15** [comment]
建议再增加一个docker compose配置文件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月24日(周四) 晚上9:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [qiandao-today/qiandao] [Feature] Docker镜像将redis分离为单独的容器 (Issue #224)




 
***@***.*** 我这里尝试重构了一下Docker部分的构建，目前来看能够正常使用，可以看一下
 镜像拉取地址： registry.cn-hongkong.aliyuncs.com/spub/qiandao:latest

**Comment by caspershw** [comment]
> 建议再增加一个docker compose配置文件

docker compose的配置不麻烦，已经写好，我试了一下简化镜像构建，但是由于ddddocr这个包的限制，只能在amd64跟aarch64上面跑，如果不需要ddddocr这个包，镜像也可以简化到~40M左右，具体可以见
- https://github.com/hiCasper/qiandao-today
- https://hub.docker.com/r/hicasper/qiandao-today/tags

当然还有热更新/重载之类的脚本没有考虑到里面，如果有需要我再提PR

**Comment by a76yyyy** [comment]
> > 建议再增加一个docker compose配置文件
> 
> docker compose的配置不麻烦，已经写好，我试了一下简化镜像构建，但是由于ddddocr这个包的限制，只能在amd64跟aarch64上面跑，如果不需要ddddocr这个包，镜像也可以简化到~40M左右，具体可以见
> 
> * https://github.com/hiCasper/qiandao-today
> * https://hub.docker.com/r/hicasper/qiandao-today/tags
> 
> 当然还有热更新/重载之类的脚本没有考虑到里面，如果有需要我再提PR

ddddocr无法在386和arm32架构上跑的原因在于没有构建对应架构的onnxruntime，因此我在 [qiandao-today/pycurl-docker](https://github.com/qiandao-today/pycurl-docker/tree/onnxruntime) 中做了非常繁琐的尝试

**Comment by kittycat520** [comment]
你好，问另外一个事情，贴吧签到的har有吗？

**Comment by a76yyyy** [comment]
> > 建议再增加一个docker compose配置文件
> 
> docker compose的配置不麻烦，已经写好，我试了一下简化镜像构建，但是由于ddddocr这个包的限制，只能在amd64跟aarch64上面跑，如果不需要ddddocr这个包，镜像也可以简化到~40M左右，具体可以见
> 
> * https://github.com/hiCasper/qiandao-today
> * https://hub.docker.com/r/hicasper/qiandao-today/tags
> 
> 当然还有热更新/重载之类的脚本没有考虑到里面，如果有需要我再提PR

redis分离以及无ddddocr构建docker镜像均已上线至master分支, 可以看一下有没有什么问题
