### ISSUE TITLE
这个签到真的好用，不过模板只有很少的，请问如何增加模板数量？

### ISSUE THREAD

**Issue by zasl** [qd-today/qd#23]
这个签到真的好用，不过模板只有很少的，请问如何增加模板数量？

**Comment by asdaragon** [comment]
@zasl 
大部分模板没有经过作者同意，所以就没有上传。有兴趣可以加qq群，大部分都有。没有可以找人做。
模板制作教程:
https://www.bilibili.com/video/BV1By4y1y7ar
https://www.bilibili.com/video/BV1Fg4y1i7gu

**Comment by chwl66** [comment]
哪里可以找到QQ群！
