### ISSUE TITLE
[Feature] 框架内集成www.asciitohex.com网站里的工具

### ISSUE THREAD

**Issue by AticTI** [qd-today/qd#233]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [x] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

在框架里集成www.asciitohex.com这个网站里面的工具

### Describe the solution

在框架里面集成www.asciitohex.com这个网站里面的工具

**Comment by gaows20** [comment]
大部分功能框架已经都有了啊

**Comment by a76yyyy** [comment]
请说明主要是缺少哪一类型的转换?

**Comment by uiolee** [comment]
> 请说明主要是缺少哪一类型的转换?

你好，[189天翼云盘-账号版.har](https://github.com/qiandao-today/templates/blob/master/189%E5%A4%A9%E7%BF%BC%E4%BA%91%E7%9B%98-%E8%B4%A6%E5%8F%B7%E7%89%88.har)中用到了两次base64转hex，时常会发生连接失败的情况。
![图片](https://user-images.githubusercontent.com/22849383/230814593-db5cc7fe-b344-4ac1-b89e-cb52e852b601.png)

**Comment by a76yyyy** [comment]
Feat d5bac99c076844439ee38fcc5402b33063ce3a5f

可以在20230626-dev框架中使用 `b2a_hex` 方法获取 hex 编码结果, 具体方法请参考 https://qd.a76yyyy.cn/about/

@AticTI @uiolee 

如果有问题, 请 reopen 这个 issue
