### ISSUE TITLE
[Bug] 同一个模板，老的binux/qiandao可以使用，当前版本失败

### ISSUE THREAD

**Issue by gudumuyu** [qd-today/qd#234]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20211228

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

作者你好，本人之前用的是fangzhengjin/qiandao基于binux/qiandao的docker版本，现准备切换到这里的新版本，把数据库复制过来以后，能够成功识别并登录，绝大部分任务都正常运行，只有两个网站的签到出现异常。在对这两个网站重新抓取.har文件，也没有解决问题。

### Describe the Bug

在基于binux/qiandao的docker版本上能够返回status:200，登录网站检查也成功签到。在目前20211228版本docker测试提示400 Bad Request   |   cloudflare，也尝试了重新抓包无果。不知道这什么问题导致的，该从什么地方排查问题呢？

### QianDao log

```shell
[W 220318 14:26:18 fetcher:449] POST https://***.org/plugin.php?id=dsu_paulsign%3Asign&operation=qiandao&infloat=1&sign_as=1&inajax=1 [Warning] HTTP 400: Bad Request -> Try to retry!
```

### Expected behavior

能够正常签到

**Comment by a76yyyy** [comment]
1. 请提供去除隐私信息后可以稳定复现问题的har文件
2. 把headers里的content-length参数删除试试

**Comment by gudumuyu** [comment]
> 1. 请提供去除隐私信息后可以稳定复现问题的har文件
> 2. 把headers里的content-length参数删除试试

去除headers里的content-length参数后成功签到！！
非常感谢解答，试了好几天问题终于解决了！
但请问为什么添加content-length后签到会失败呢？我是用fiddle+chrome抓包的，一般来说还有哪些参数要删除呢？谢谢！

**Comment by a76yyyy** [comment]
> 
> 去除headers里的content-length参数后成功签到！！ 非常感谢解答，试了好几天问题终于解决了！ 但请问为什么添加content-length后签到会失败呢？我是用fiddle+chrome抓包的，一般来说还有哪些参数要删除呢？谢谢！

简单来说，原版会自动忽略这个问题，新版签到需要自行设置是否忽略该参数(配置变量里看，默认不忽略)
