### ISSUE TITLE
优化任务超时提示

### ISSUE THREAD

**Issue by ss7458** [qd-today/qd#236]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

latest

### Bug on OS

macOS

### Bug on Platform

Docker/macOS

### To Reproduce

api://util/delay/20
api://util/delay/20
api://util/delay/20

### Describe the Bug

![5EP)NIXBJP{~YQ$OQ~_~4)0](https://user-images.githubusercontent.com/90891377/159210049-93830703-e021-4b34-9eeb-4901c5a9ea3b.png)

### QianDao log

```shell
123
```

### Expected behavior

好看一点

**Comment by a76yyyy** [comment]
现在还有这个错误么

**Comment by a76yyyy** [comment]
这个是nginx网关提示, 不属于签到容器问题
