### ISSUE TITLE
docker版本最新版20220315，数据库备份命令无效

### ISSUE THREAD

**Issue by snakexgc** [qd-today/qd#240]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220315

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

docker cp qiandao:/usr/src/app/config/database.db
输出：Error: No such container:path: qiandao:/usr/src/app/config/database.db

### Describe the Bug

不能备份数据库，找不到这个文件

### QianDao config

```shell
之前从readme复制来的，是从老版本升级来的
```

### QianDao log

```shell
Error: No such container:path: qiandao:/usr/src/app/config/database.db
```

### Expected behavior

可以正常备份

### Screenshots

![image](https://user-images.githubusercontent.com/78722169/160792578-70c1051e-16f9-477e-8c49-5a17226885d1.png)

**Comment by acooler15** [comment]
发下`docker ps`的结果

**Comment by snakexgc** [comment]
![image](https://user-images.githubusercontent.com/78722169/161195916-01cb4763-faed-4d1d-8610-2ecd93774dea.png)

**Comment by acooler15** [comment]
- 确认下是否使用的是最新版本的docker镜像
- `docker exec -it qiandao bash`进docker容器内,`ls -l /usr/src/app/config/`查看是否存在
- 查看是否使用的是mysql

**Comment by a76yyyy** [comment]
看一下你是不是改了config.py或者环境变量里数据库文件的地址 
或者看一下你用的是不是MySQL数据库

**Comment by snakexgc** [comment]
好的，我已经重装解决了，麻烦各位大佬了
