### ISSUE TITLE
[Feature] for range 和 unquote

### ISSUE THREAD

**Issue by lazureice** [qd-today/qd#244]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

`qiandao/about` 中有 quote，但没有 unquote。是不是只能调用 api 来转换？

=====

for 循环如果是循环列表就正常，如果是 range `{% for i in range(10) %}` 就报错。
```
Response Error : HTTP 500: The error occurred when rendering template url: {% for i in range(10) %}
TemplateSyntaxError("Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'."),
Request URL: {% for i in range(10) %}
```
我搜了一下 jinja2 似乎是支持 range 的，是我没用对吗？我现在是 api 调用一次，返回一个字符串 "0123456789"，然后迭代这个字符串。

### Describe the solution

添加 unquote 和 for range。或者已经有了，但我的写法不对？

### Additional context

现在也能间接来实现想要的效果。没有的话问题也不大。

**Comment by a76yyyy** [comment]
框架对于jinja2的for循环支持并不完整
