### ISSUE TITLE
[Bug] 群晖升级之后 备份的数据无法恢复求救

### ISSUE THREAD

**Issue by TendernessRadif** [qd-today/qd#246]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20200410

### Bug on OS

Linux

### Bug on Platform

Code Build/Linux 64位

### To Reproduce

重新安装签到

### Describe the Bug

把之前备份的数据在签到页面数据库恢复提示如下
抱歉，暂不支持通过本页面还原SQLite3数据库文件！(╥╯^╰╥)

### QianDao log

```shell
抱歉，暂不支持通过本页面还原SQLite3数据库文件！(╥╯^╰╥)
```

### Expected behavior

请求让我恢复数据

### Screenshots

![image](https://user-images.githubusercontent.com/32267867/163110742-6a43a624-d825-4f4c-92a7-8f769a2a1f60.png)
![image](https://user-images.githubusercontent.com/32267867/163110762-087a2477-953a-4100-b6fe-8f0b823252a6.png)

**Comment by acooler15** [comment]
docker请参考命令：
```
docker cp database.db 容器名:/usr/src/app/config/
```

**Comment by TendernessRadif** [comment]
> docker请参考命令：
> 
> ```
> docker cp database.db 容器名:/usr/src/app/config/
> ```
老哥 这样回复晚了 重新打开网页变成500错误了

**Comment by acooler15** [comment]
> > docker请参考命令：
> > ```
> > docker cp database.db 容器名:/usr/src/app/config/
> > ```
> 
> 老哥 这样回复晚了 重新打开网页变成500错误了

😂你docker logs -f 容器名 看下日志

**Comment by a76yyyy** [comment]
> > docker请参考命令：
> > ```
> > docker cp database.db 容器名:/usr/src/app/config/
> > ```
> 
> 老哥 这样回复晚了 重新打开网页变成500错误了

需要重启容器

**Comment by TendernessRadif** [comment]
> > > docker请参考命令：
> > > ```
> > > docker cp database.db 容器名:/usr/src/app/config/
> > > ```
> > 
> > 
> > 老哥 这样回复晚了 重新打开网页变成500错误了
> 
> 需要重启容器

docker cp /volume1/docker/database.db QD:/usr/src/app/config/ 大神 容器名称为QD 使用以上命令在DSM7.0的docker下 root权限运行后，重启QD容器 提示

<html>
<body>
<div class="x-grid3-row x-grid3-row-selected" role="row" id="ext-gen16780" style="margin: 0px; padding: 0px; cursor: default; border-width: 0px 0px 1px; border-style: dotted dotted solid; border-top-color: initial; border-right-color: initial; border-bottom-color: rgba(198, 212, 224, 0.4); border-left-color: initial; border-image: initial; width: 657px; background-color: rgba(5, 127, 235, 0.1) !important; color: rgb(65, 75, 85); font-size: 13px; font-family: Verdana, Arial, &quot;Microsoft YaHei&quot;, sans-serif; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">

Traceback (most recent call last): | stdout
-- | --


</div>
</body>
</html>
这样的错误

**Comment by TendernessRadif** [comment]
> b

![image](https://user-images.githubusercontent.com/32267867/163493148-b988fc96-01e6-457e-bbb3-061cfe404fc1.png)

**Comment by a76yyyy** [comment]
> > b
> 
> ![image](https://user-images.githubusercontent.com/32267867/163493148-b988fc96-01e6-457e-bbb3-061cfe404fc1.png)

可能是你备份的数据库在你备份的时候正在读写等操作，导致你备份的文件不完整或者损坏；

也不排除你备份文件的时候网络中断导致备份文件不完整

**Comment by TendernessRadif** [comment]
感谢老哥 您这么说我就彻底懂了 我重新来过 感谢您的付出 谢谢！
