### ISSUE TITLE
dockerman部署失败

### ISSUE THREAD

**Issue by ni7ht** [qd-today/qd#247]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220410

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

R2S软路由中dockerman使用以下指令创建容器报错
docker run -d --name qiandao -p 8923:80 -v $(pwd)/qiandao/config:/usr/src/app/config a76yyyy/qiandao

### Describe the Bug

无法创建容器
docker run -d --name qiandao -p 8923:80 -v $(pwd)/qiandao/config:/usr/src/app/config a76yyyy/qiandao

### QianDao config

```shell
默认配置
```

### QianDao log

```shell
Container: create qiandao...code:400 create $(pwd)/qiandao/config: "$(pwd)/qiandao/config" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path
```

### Expected behavior

创建脚本能够适配dockerman

### Screenshots

![微信截图_20220415174328](https://user-images.githubusercontent.com/37174285/163555881-d3c8b5ae-68af-452e-a449-9ebbe39023c9.png)

**Comment by a76yyyy** [comment]
dockerman不支持 `$(pwd)` ,把你创建命令中的 `$(pwd)/qiandao/config` 改成docker有权限访问的绝对路径, 比如 `/root/qiandao/config`

**Comment by ni7ht** [comment]
> dockerman不支持 `$(pwd)` ,把你创建命令中的 `$(pwd)/qiandao/config` 改成docker有权限访问的绝对路径, 比如 `/root/qiandao/config`

感谢回复！了解啦.
