### ISSUE TITLE
建议增加cookie保活轮询功能，这样就可以保持登录了

### ISSUE THREAD

**Issue by kayleyang** [qd-today/qd#25]
建议增加cookie保活轮询功能，这样就可以保持登录了，也不需要每次登录，毕竟很多登录接口存在很多校验，比如二维码、人机校验

**Comment by asdaragon** [comment]
@kayleyang  cookie都失效了，不登陆你哪来的有效cookie。。。

**Comment by kayleyang** [comment]
> @kayleyang cookie都失效了，不登陆你哪来的有效cookie。。。

在cookie失效前随便请求一个接口，这样服务端就会刷新cookie失效时间呀

**Comment by kayleyang** [comment]
@AragonSnow 在cookie失效前随便请求一个接口，这样服务端就会刷新cookie失效时间呀

**Comment by asdaragon** [comment]
@kayleyang 如果返回有set-cookie的话，这你自己再har里写不就好了。本身你直接用cookie打开页面，加个成功判定，不符合就报错推送给你。
