### ISSUE TITLE
[Bug] qiandao容器无法启动

### ISSUE THREAD

**Issue by sunjx97** [qd-today/qd#250]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220410

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

疑似与duplicati备份任务有关（我也不确定

自从开始用docker版duplicati进行容器备份后（备份频率：每30分钟），经常出现数据库损坏（malformed）问题，我也没什么办法，只能不断通过duplicati恢复文件。最近一次出现这个问题后，我更新了qiandao的docker容器到最新latest版（20220410），并通过duplicati恢复大约一个月前的正常数据库文件，便发生了无法启动容器的问题（之前虽然数据库仍会在两天内损坏，但恢复文件后运行qiandao容器是没问题的）。

我现在该怎么办orz（

### Describe the Bug

无法正常运行qiandao容器

### QianDao log

```shell
[W 220426 22:25:53 redisdb:26] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 82, in <module>
开启det后自动关闭ocr
    http_server = HTTPServer(Application(database), xheaders=True)
  File "/usr/src/app/web/app.py", line 35, in __init__
    self.jinja_env = jinja2.Environment(
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/usr/lib/python3.10/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'autoescape'
```

### Expected behavior

可以正常运行qiandao容器

**Comment by acooler15** [comment]
从日志上看，不是数据库的问题，是jinja2报了错误，可以尝试下重新下载docker镜像，重新创建容器。

**Comment by a76yyyy** [comment]
duplicate #245

这个显示一般原因是你把整个签到的源码全部映射了出去，导致更新容器后使用的源码仍然是容器外部的源码

两种建议：
1. 删除源码目录的映射，只映射数据库所在的config文件夹目录
2. 更新映射在外部文件夹中的源码（不如第一种）

此外，如果有备份数据库的习惯，推荐使用mysql或者在签到框架不执行任务的时间备份（建议专门空出一个时间段，该时间段不执行签到任务，只用于备份数据库）

**Comment by sunjx97** [comment]
> 

使用方法1解决了，感谢！

很奇怪，我是通过portainer创建的容器，只影射了config目录，但portainer自动映射了两个额外的源码目录。
