### ISSUE TITLE
[Bug] 数据库使用MySQL时报错:Got an error reading communication packets

### ISSUE THREAD

**Issue by znwuyi** [qd-today/qd#253]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

latest/20220410/20211228
### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

数据库使用MySQL，启动Qiandao后便报错;

### Describe the Bug

数据库使用MySQL时报错:Got an error reading communication packets；
启动qiandao后，MySQL后台持续报错： [Warning] Aborted connection 3374 to db: 'AutoSign' user: 'dockeruser' host: '172.17.0.1' (Got an error reading communication packets)；
MySQL后台查看Aborted_clients数随时间持续增加，关闭qiandao后停止增加；
错误出现期间，qiandao可正常使用；

### QianDao log

```shell
MySQL报错日志:
2022-04-28 17:55:44 3366 [Warning] Aborted connection 3366 to db: 'AutoSign' user: 'dockeruser' host: '172.17.0.1' (Got an error reading communication packets)

2022-04-28 17:55:44 3369 [Warning] Aborted connection 3369 to db: 'AutoSign' user: 'dockeruser' host: '172.17.0.1' (Got an error reading communication packets)

2022-04-28 17:55:44 3375 [Warning] Aborted connection 3375 to db: 'AutoSign' user: 'dockeruser' host: '172.17.0.1' (Got an error reading communication packets)

MariaDB [(none)]> show global status like '%abort%';
+--------------------------+-------+
| Variable_name            | Value |
+--------------------------+-------+
| Aborted_clients          | 3271  |
| Aborted_connects         | 2     |
| Aborted_connects_preauth | 0     |
| wsrep_local_bf_aborts    | 0     |
+--------------------------+-------+
4 rows in set (0.001 sec)

MariaDB [(none)]> show global status like '%abort%';
+--------------------------+-------+
| Variable_name            | Value |
+--------------------------+-------+
| Aborted_clients          | 3319  |
| Aborted_connects         | 2     |
| Aborted_connects_preauth | 0     |
| wsrep_local_bf_aborts    | 0     |
+--------------------------+-------+
4 rows in set (0.001 sec)

MariaDB [(none)]> show global status like '%abort%';
+--------------------------+-------+
| Variable_name            | Value |
+--------------------------+-------+
| Aborted_clients          | 3380  |
| Aborted_connects         | 2     |
| Aborted_connects_preauth | 0     |
| wsrep_local_bf_aborts    | 0     |
+--------------------------+-------+
4 rows in set (0.001 sec)

```

### Screenshots
![image](https://user-images.githubusercontent.com/58579685/165729840-a937fbb6-cfa4-484f-9aec-e2bebd335bfe.png)

![image](https://user-images.githubusercontent.com/58579685/165729921-a343af2c-d5f2-416e-bce9-1ed3ad9832a6.png)

**Comment by acooler15** [comment]
启动后就开始报错吗？

**Comment by znwuyi** [comment]
> 启动后就开始报错吗？

是的，一旦启动立马报错

**Comment by znwuyi** [comment]
更新MariaDB到最新版本后，不再持续报错。

**Comment by a76yyyy** [comment]
新版本针对 `abort connects` 进行过优化，或许有时间需要进一步优化一下 `abort clients` 问题

但这个应该不影响使用

**Comment by a76yyyy** [comment]
最新源码已经更新SQLAlchemy优化

想要体验的话, 务必备份好数据库（多备份几个），再进行如下操作:

### 进入容器后台, 执行命令后重启容器 

```
wget https://gitee.com/a76yyyy/qiandao/raw/master/update.sh -O /usr/src/app/update.sh && \
sh /usr/src/app/update.sh -f
```
### 一定要完整执行上面的命令

**Comment by a76yyyy** [comment]
有问题可以reopen这个issue
