### ISSUE TITLE
Ajax请求

### ISSUE THREAD

**Issue by jinshuqishi2019** [qd-today/qd#26]
Ajax请求使用get方法在签到里面没有效果，而在浏览器请求则有效果。都是添加了cookie。有这方面的例子吗？

**Comment by asdaragon** [comment]
没明白啥意思，qiandao用不是ajax请求。模版的制作参考
https://www.bilibili.com/video/BV1By4y1y7ar
https://www.bilibili.com/video/BV1Fg4y1i7gu

>
