### ISSUE TITLE
[Feature] url 编码

### ISSUE THREAD

**Issue by loveqianool** [qd-today/qd#269]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

某站登录需要把密码的特殊字符 urlencode 一下，没找到方法。

### Describe the solution

添加一个类似 {{quote_chinese(a)}} 的参数
例如 {{urlencode(a)}}
需要把 a 的 E#&46Z4ucN&* 编码成 E%23%2646Z4ucN%26*

**Comment by gMan1990** [comment]
dup https://github.com/qiandao-today/qiandao/issues/286
