### ISSUE TITLE
[Feature] 添加md5解码

### ISSUE THREAD

**Issue by xiaomi1991** [qd-today/qd#270]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

添加md5解码api

### Describe the solution

md5解码为原来的码，目前可以通过跳转到其他网站解码后在进行下面的步骤

### Describe alternatives

有些解码md5的网站可以正确解码出来md5之前的验证码内容

### Additional context

有些网站的验证码是图片中文字的md5，加上解码功能应该会更好用 不用再去加上一个跳转到其他网站去解码的步骤了

**Comment by acooler15** [comment]
抱歉，无法完成该功能。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月27日(周五) 晚上8:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiandao-today/qiandao] [Feature] 添加md5解码 (Issue #270)




 
Verify steps
  
 Tracker 我已经在 Issue Tracker 中找过我要提出的问题 

 Need 当前 QianDao 框架并不包含该功能特性或者还不完善 

 Framework 这是 QianDao 框架应包含的特性，并非模板特性 

 Meaningful 我提交的不是无意义的 催促更新或修复 请求 
 
Describe the Feature
 
添加md5解码api
 
Describe the solution
 
md5解码为原来的码，目前可以通过跳转到其他网站解码后在进行下面的步骤
 
Describe alternatives
 
有些解码md5的网站可以正确解码出来md5之前的验证码内容
 
Additional context
 
有些网站的验证码是图片中文字的md5，加上解码功能应该会更好用 不用再去加上一个跳转到其他网站去解码的步骤了
