### ISSUE TITLE
[Bug] 模板无法保存，报500错误

### ISSUE THREAD

**Issue by sunjx97** [qd-today/qd#273]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220410

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

无

### Describe the Bug

无法保存新建的模板文件，报错<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>。

### QianDao log

```shell
[E 220530 12:41:47 web:1789] Uncaught exception POST /har/save?reponame=&name= (10.10.201.3)
    HTTPServerRequest(protocol='http', host='10.10.25.7', method='POST', uri='/har/save?reponame=&name=', version='HTTP/1.1', remote_ip='10.10.201.3')
    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/src/app/web/handlers/har.py", line 159, in post
        raise Exception('create tpl error')
    Exception: create tpl error
```

### Expected behavior

可以正常保存模板。

**Comment by a76yyyy** [comment]
数据库插入数据失败导致未获取到自增id，请退出登录、清空浏览器缓存、重启容器，重新尝试；

如果还是失败请在签到配置中开启debug模式，打印详细日志；如果只是单个har保存失败请单独发一下har文件

**Comment by sunjx97** [comment]
不知为什么，又好了😂
