### ISSUE TITLE
[Bug] 自动执行失败达到设定次数也不会推送

### ISSUE THREAD

**Issue by gitiray** [qd-today/qd#274]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220525

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

- 自定义推送POST，application/json，执行成功时能收到
- 推送结果，仅开启自动执行成功通知、自动执行失败通知
- 自动错误几次后提醒设定为3
- 设置签到任务重试次数为默认8次、重试间隔默认不填，定时每天0点，且任务执行前Cookie已失效，等待自动执行

等到自动执行失败后，共出现9次执行日志：
1. 00:00，失败，未推送
2. 00:10，失败，未推送
3. 02:00，失败，未推送
4. 06:00，失败，未推送
5. 12:00，失败，未推送
6. 23:00，失败，未推送
7. 第二天10:00，失败，未推送
8. 第二天21:00，失败，未推送
9. 第三天08:00，失败，未推送失败。但由于任务超过次数，推送提示任务被禁用

### Describe the Bug

达到设定的3次失败，没有推送失败、相关日志
直到超过最大重试次数后，任务被禁用才推送

前后跨度3天，签到因此中断2天，已经多次遇到

### QianDao log

```shell
[W 220531 10:00:00 fetcher:xxx] GET https://xxxxxxxxx
[E 220531 10:00:00 funcs:xxx] Sent to Cus_Pusher error: Expecting ',' delimiter: line 1 column 186 (char 185)
    Traceback (most recent call last):
      File "/usr/src/app/libs/funcs.py", line 216, in cus_pusher_send
        postDatatmp = json.loads(postDatatmp)
      File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 186 (char 185)
[E 220531 10:00:05 worker:xxx] taskid:xx tplid:xx failed! 4.6721s
    Failed at 3/9 request,
    Fail assert: {"re": "成功", "from": "content"} from success_asserts,
    Request URL: https://xxxxxxxxxxxxxx
[I 220531 10:00:05 worker:xx] 1 task done. 0 success, 1 failed
```

### Expected behavior

达到设定失败次数，推送失败情况，并附上相应日志

**Comment by gitiray** [comment]
开启手动失败推送后，用无效Cookie去执行签到，也收不到签到失败的推送。而签到成功的就能收到。
还试了GET方式推送，也是失败不行，成功可以，此时没有json日志错误

之前使用同样的GET推送，是 ArgonSnow 维护的版本，推送是全部正常的。

**Comment by a76yyyy** [comment]
请发一下 `POST Data` 的内容格式

**Comment by gitiray** [comment]
```
{"parse_mode":"markdown", "chat_id": "xxxxxxxxxx", "text":"*{t}：*{log}"}
```

其实就是telegram，内置的消息格式不喜欢，自己写了一个

**Comment by a76yyyy** [comment]
源码更新之后看可不可以

**Comment by a76yyyy** [comment]
tg的 `markdown` 模式与自定义推送不兼容, 请修改 `parsemode` 为 `html` 

```
# 先更新框架源码, 再修改postdata
{"parse_mode":"HTML", "chat_id": "xxxxxxxxxx", "text":"<b>{t}：</b>\n{log}"}
```

**Comment by gitiray** [comment]
> tg的 `markdown` 模式与自定义推送不兼容, 请修改 `parsemode` 为 `html`
> 
> ```
> # 先更新框架源码, 再修改postdata
> {"parse_mode":"HTML", "chat_id": "xxxxxxxxxx", "text":"<b>{t}：</b>\n{log}"}
> ```

之前有考虑过这个，然后把 `parse_mode` 改成 `html` 试过了，还是收不到执行失败时的消息。

目前拉取最新代码能收到自定义推送的失败日志了，我再观察下，谢谢您！
