### ISSUE TITLE
[Bug] 新版的Arm64版本的image沒辦法部屬

### ISSUE THREAD

**Issue by SachiaLanlus** [qd-today/qd#276]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220525

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

deploy docker linux arm64版本
是"arm"64喔

### Describe the Bug

我發現新的arm64 image都會有這個問題
我想應該是因為更新了python版本的關係
我it進去看發現container裡面的libs/cookie_utils.py的import還是舊的code
```
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
# vim: set et sw=4 ts=4 sts=4 ff=unix fenc=utf8:
# Author: Binux<i@binux.me>
#         http://binux.me
# Created on 2012-09-12 22:39:57
# form requests&tornado

from collections import MutableMapping as DictMixin
import http.cookiejar as cookielib
from urllib.parse import urlparse
from tornado import httpclient, httputil
from requests.cookies import MockRequest,create_cookie,remove_cookie_by_name
```
也就是沒有try except import error的版本
所以每次deploy之後都run不起來

這個問題我確定在20211228那個image還沒有出現
因為這個版本的image是可以使用的

### QianDao log

```shell
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 15, in <module>
    from web.app import Application
  File "/usr/src/app/web/app.py", line 15, in <module>
    from libs.fetcher import Fetcher
  File "/usr/src/app/libs/fetcher.py", line 25, in <module>
    from libs import cookie_utils, utils
  File "/usr/src/app/libs/cookie_utils.py", line 9, in <module>
    from collections import MutableMapping as DictMixin
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```
```


### Expected behavior

正確的import

### Screenshots

_No response_

**Comment by a76yyyy** [comment]
请检查你的容器部署设置是否将源码映射到容器外部,导致更新容器不会更新源码?

**Comment by SachiaLanlus** [comment]
> 请检查你的容器部署设置是否将源码映射到容器外部,导致更新容器不会更新源码?

天啊，真的是這個問題。
前幾天拿amd64測的時候是按照dockerhub上面的設定去配置的，想說都沒問題。
因此才會想說會不會是arm64有問題，沒想到小丑竟是我自己。
經過您提醒後我才去檢查了arm64的那個container的配置，結果真的映射了volume。
問題解決了。
