### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by AemonCao** [qd-today/qd#277]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

希望可以添加清空成败次数的功能，或者在清空日志的时候可以情况成败次数。

### Describe the solution

希望可以添加清空成败次数的功能，或者在清空日志的时候可以情况成败次数。

**Comment by a76yyyy** [comment]
#239 0525版本已经支持了

![image](https://user-images.githubusercontent.com/56478790/173297049-a2c1038e-0497-4588-8689-242983e5ad29.png)

点击如图所示地方即可
