### ISSUE TITLE
[Bug]多条日志只能输出一条日志 不知道是不是我设置问题

### ISSUE THREAD

**Issue by muzimuxi** [qd-today/qd#279]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220525

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

我的设置 ：一个网址三个不同的请求地址， 每条请求设置的不同日志输出

### Describe the Bug

实际只输出一条日志 其他请求的日志就不输出了  每个页面测试可以看见日志正则提取成功

### QianDao log

```shell
leftDays":"394
```

### Expected behavior

可不可以正则日志输出全部推送呢

### Screenshots

![image](https://user-images.githubusercontent.com/42004082/174092882-ceb7332e-121d-4115-8323-64d6d39d4d4c.png)
![image](https://user-images.githubusercontent.com/42004082/174093256-db222f53-2f08-489a-8160-03a1cfcf7252.png)
![image](https://user-images.githubusercontent.com/42004082/174093417-6ed1d006-2c0d-4563-88be-136ac9c7706c.png)
![image](https://user-images.githubusercontent.com/42004082/174093570-0cb33fe9-7c7e-429c-876c-ecb3e8735dcf.png)

**Comment by alhricke** [comment]
需要输出多条日志内容，你需要在api上整合后在一起输出

**Comment by muzimuxi** [comment]
> 需要输出多条日志，你需要在api上整合后输出

怎样集成呢 不是很明白
![image](https://user-images.githubusercontent.com/42004082/174445165-829e286b-a15a-46cd-8ecb-26caf491155a.png)
![image](https://user-images.githubusercontent.com/42004082/174445362-a262564a-5b82-426e-b931-cee0e33d32ee.png)
![image](https://user-images.githubusercontent.com/42004082/174445374-5a0f84af-977d-4946-88f6-afaffc8fb395.png)

**Comment by a76yyyy** [comment]
<img width="540" alt="1" src="https://user-images.githubusercontent.com/56478790/174473348-6fa3eb00-0fa8-47e2-8429-05444c311f38.png">

在这个请求里
![image](https://user-images.githubusercontent.com/56478790/174473375-302f2ee2-ab43-4407-8f06-51c8d1104dc1.png)

**Comment by muzimuxi** [comment]
> <img alt="1" width="540" src="https://user-images.githubusercontent.com/56478790/174473348-6fa3eb00-0fa8-47e2-8429-05444c311f38.png">
> 
> 在这个请求里 ![图片](https://user-images.githubusercontent.com/56478790/174473375-302f2ee2-ab43-4407-8f06-51c8d1104dc1.png)

搞定了 感谢感谢
