### ISSUE TITLE
v2ex cookie 无法签到

### ISSUE THREAD

**Issue by loveqianool** [qd-today/qd#28]
我在 https://qiandao.today/ 下载了 v2ex-cookie 的模板
上传到此程序部署的站点却无法成功签到，同一时间我在 qiandao.today 使用相同的 cookie 签到成功。
我使用模板内的测试发现第一步都能成功登录，但是此程序和 qiandao.today 获得的 cookie 不一样了。
此程序
![此程序](https://cdn.jsdelivr.net/gh/sbough1/z/images/2020/10/08/697050bc913be8b8fe9eff33d46ec33d.png)

qiandao.today
![qiandao.today](https://cdn.jsdelivr.net/gh/sbough1/z/images/2020/10/08/74a090675daa88c92fbfa80d4e421ea5.png)

另外能否加入 
https://github.com/mengshouer/CheckinBox/blob/master/Cloud189Checkin/C189Checkin.py 的 int2char 和 b64tohex
我尝试了好多次抓那个 accessToken 但是都失败了。。。

**Comment by asdaragon** [comment]
@loveqianool 
1.  不知道你为什么签到不了；
2. 暂时没有添加函数的打算，189这个函数我也试过了，用一些在线的网站也能处理，不过登陆时候要js，目前是没有成功。
