### ISSUE TITLE
[Bug] 企业微信通知注册参数填写问题

### ISSUE THREAD

**Issue by goooxyz** [qd-today/qd#284]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220525

### Bug on OS

Windows

### Bug on Platform

Docker/Linux 64位

### To Reproduce

工具箱-推送注册-企业微信;只填写以下信息
(用;来分割) 企业ID;应用ID;应用密钥

### Describe the Bug

企业微信通知注册提示: 自定推送图片URL(非必需);
但是如果不填或者填的不是url,都无法成功推送通知,所以目前看来'自定推送图片URL'这个参数是必须填写而且是有效的图片url才行

### QianDao config

```shell
N/A
```

### QianDao log

```shell
N/A
```

### Expected behavior

感觉还是以前直接填企业微信图片素材ID好用,不清楚是不是因为不能用了才换URL的,这都不重要,重要的是placeholder提示文字要修正,容易被误导

### Screenshots

![Uploading qd.png…]()

**Comment by a76yyyy** [comment]
出现所述情况的原因在于**容器所在网络无法访问框架默认设置的 `push_pic` 地址**

详见 https://github.com/qiandao-today/qiandao/blob/master/config.py#L41

在config 或者环境变量中可以设置默认的推送图片地址 `PUSH_PIC_URL`

配置环境变量 - https://github.com/qiandao-today/qiandao#configpy-%E9%85%8D%E7%BD%AE%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

**Comment by a76yyyy** [comment]
已优化
