### ISSUE TITLE
[Bug] 调用存记事本api时，提交数据中含有&，&及其后内容存不上

### ISSUE THREAD

**Issue by DUKISS** [qd-today/qd#286]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220702

### Bug on OS

Linux

### Bug on Platform

Code Build/Linux 64位

### To Reproduce

![IMG_20220731_183018](https://user-images.githubusercontent.com/39652212/182092775-dc89de23-ae11-4129-875c-6e2cda6da70a.jpg)
![IMG_20220731_182928](https://user-images.githubusercontent.com/39652212/182092810-b8661697-f44d-4ffc-adf2-4f7e8fbd84ef.jpg)
本想把日志存到记事本
结果调用存记事本api后，存进去的没有&及其后内容

### Describe the Bug

同上

### QianDao log

```shell
……
```

### Expected behavior

正常可用即可。

**Comment by a76yyyy** [comment]
需要使用 urlencode过滤器 包裹 记事本工具中的data参数, 如 `data={{__log__ | urlencode}}`

**Comment by gMan1990** [comment]
- @a76yyyy
    - 这个 `{{ arg | method }}` 是什么语法，有语法教程吗？
    - 这个 method 是哪个语言的，php吗？

update: 找到了, 关于语法 http://docs.jinkan.org/docs/jinja2/templates.html#id4

**Comment by a76yyyy** [comment]
> * @a76yyyy
>   
>   * 这个 `{{ arg | method }}` 是什么语法，有语法教程吗？
>   * 这个 method 是哪个语言的，php吗？

框架首页左上角关于页面
