### ISSUE TITLE
一个用户目前只建立一个记事本，需要使用多个记事本可以使用多个账号

### ISSUE THREAD

**Issue by DUKISS** [qd-today/qd#287]
一个用户目前只建立一个记事本，需要使用多个记事本可以使用多个账号
该需求优先级较低，不过可以考虑加入该需求

_Originally posted by @a76yyyy in https://github.com/qiandao-today/qiandao/issues/154#issuecomment-989475625_

大佬，这个需求可以给添加一下吗？

**Comment by a76yyyy** [comment]
duplicate #154
