### ISSUE TITLE
创建签到500错误

### ISSUE THREAD

**Issue by fgprodigal** [qd-today/qd#30]
GET http://192.168.169.188:10086/task/new 500 (Internal Server Error)

server_1  |     [E 201013 10:43:02 web:1591] Uncaught exception GET /task/new (192.168.169.235)
server_1  |     HTTPServerRequest(protocol='http', host='192.168.169.188:10086', method='GET', uri='/task/new', version='HTTP/1.1', remote_ip='192.168.169.235', headers={'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.169.188:10086', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 Edg/85.0.564.63', 'Connection': 'keep-alive', 'Cookie': '_xsrf=2|d9195da0|16ef3aea0b69c2f7cbb31c75057e9c4b|1602556887; user="2|1:0|10:1602556917|4:user|72:hMQEcm9sZcDECG5pY2tuYW1lwMQCaWQBxAVlbWFpbLRmZ3Byb2RpZ2FsQGdtYWlsLmNvbQ==|2a129a4819ae9d10e8d937f89f66bf38e45e6f629ec2fd9734abd02872e6b2a7"', 'Upgrade-Insecure-Requests': '1'})
server_1  |     Traceback (most recent call last):
server_1  |       File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1510, in _execute
server_1  |         result = method(*self.path_args, **self.path_kwargs)
server_1  |       File "/usr/src/app/web/handlers/task.py", line 57, in get
server_1  |         tplid = int(tplid)
server_1  |     TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by asdaragon** [comment]
先添加模版，再创建任务

**Comment by fgprodigal** [comment]
gotcha
