### ISSUE TITLE
[Bug] 正则无法匹配变量

### ISSUE THREAD

**Issue by Kerwin1202** [qd-today/qd#310]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220728

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

无

### Describe the Bug

正则有点怪无法匹配 看底部截图

```
无法匹配
Bonus":([0-9\.]+) 
s":([0-9\.]+)


可以匹配
TotalBonus":([0-9\.]+)
```

部分源数据
```
"UpdateBonus":0.0,"CardDegreedeBonus":0.0,"TotalBonus":5.0,"TotalConsume":0.0,"Bonus":957.0,"CardUseDesc"
```

### QianDao log

```shell
无
```

### Expected behavior

可以正则匹配

### Screenshots

<img width="891" alt="image" src="https://user-images.githubusercontent.com/16319833/187037557-ef297753-21f3-428b-90f5-49830965bb01.png">

<img width="884" alt="image" src="https://user-images.githubusercontent.com/16319833/187037691-ff3624a9-8a0b-4bf5-afb6-390576786062.png">

其他工具可以正常匹配

<img width="832" alt="image" src="https://user-images.githubusercontent.com/16319833/187037613-2edd0375-61fd-4a39-af1d-64f640e7ec33.png">

**Comment by a76yyyy** [comment]
想要匹配多个字段, 请使用 `/g` 进行全局匹配

想要正确匹配单个字段, 请确保正则表达式匹配到的是的第一个匹配字段

比如匹配所有字段用 `/s":([0-9\.]+)/g`

匹配 `Bouns` 就用 `"Bonus":([0-9\.]+)`

此外注意转义字符的使用

**Comment by Kerwin1202** [comment]
打扰了，是我看错了，因为前面有TotalBonus 包含了 Bonus
