### ISSUE TITLE
[Bug] 无法启动

### ISSUE THREAD

**Issue by suyisong** [qd-today/qd#319]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220901

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

1.在pve（基于debian）下用lxc容器安装docker，使用portainer辅助部署，配置了端口映射和目录映射
（安装过其它镜像，其它镜像正常）

### Describe the Bug

2.无法启动，报错
似乎和redis或ocr有关，使用debug模式，但是没有太多详细日志。

### QianDao config

```shell
CURL_VERSION	7.84.0
DDDDOCR_VERSION	master
ONNXRUNTIME_TAG	v1.11.0
PATH	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PORT	80
PYCURL_SSL_LIBRARY	openssl
QIANDAO_DEBUG	True
TZ	CST-8
```

### QianDao log

```shell
[W 221007 23:28:26 qiandao.RedisDB redisdb:27] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.
[W 221007 23:28:26 qiandao.RedisDB redisdb:27] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.
[D 221007 23:28:26 asyncio selector_events:54] Using selector: EpollSelector
[W 221007 23:28:27 qiandao.RedisDB redisdb:27] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 60, in <module>
    from web.app import Application
  File "/usr/src/app/web/app.py", line 17, in <module>
    from web.handlers import handlers, ui_modules, ui_methods
  File "/usr/src/app/web/handlers/__init__.py", line 23, in <module>
    module = __import__('%s.%s' % (__package__, module), fromlist = ["handlers"])
  File "/usr/src/app/web/handlers/util.py", line 600, in <module>
    DdddOCRServer = DdddOCRServer()
  File "/usr/src/app/web/handlers/util.py", line 578, in __init__
    self.oldocr = ddddocr.DdddOcr(old=True,show_ad=False)
  File "/usr/lib/python3.10/site-packages/ddddocr-1.4.3-py3.10.egg/ddddocr/__init__.py", line 1458, in __init__
    self.__ort_session = onnxruntime.InferenceSession(self.__graph_path, providers=self.__providers)
  File "/usr/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 370, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
RuntimeError: /onnxruntime/onnxruntime/core/platform/posix/env.cc:183 onnxruntime::{anonymous}::PosixThread::PosixThread(const char*, int, unsigned int (*)(int, Eigen::ThreadPoolInterface*), Eigen::ThreadPoolInterface*, const onnxruntime::ThreadOptions&) pthread_setaffinity_np failed, error code: 2 error msg: No such file or directory
```

### Expected behavior

希望能够提供比较清晰的日志，这样有一定基础的同学可以自行搞定

**Comment by a76yyyy** [comment]
> Onnxruntime Builder does not currently support building i386 and arm32 wheels
>
> 32位容器默认不安装ddddocr, 是否有自行安装 ddddocr 模组

这个是ddddocr调用onnxruntime报错, 是平台架构的问题, 32位alpine不兼容onnxruntime(主要是我没有32位机器, 没法调试), 
建议使用 [qiandao:lite-latest](https://hub.docker.com/layers/a76yyyy/qiandao/lite-latest/images/sha256-38487226e7d41cd27a26f1171fd00f64948f91315058eec1f953133fea7bb4dd?context=repo) 版本, 
qiandao:lite-latest 与 qiandao:latest 差异详见 [pycurl-docker](https://github.com/qiandao-today/pycurl-docker/blob/main/README.md)

**Comment by suyisong** [comment]
抱歉，写错了，是64位的容器
root@debian:~# uname -a
Linux debian 5.15.60-1-pve #1 SMP PVE 5.15.60-1 (Mon, 19 Sep 2022 17:53:17 +0200) x86_64 GNU/Linux

**Comment by a76yyyy** [comment]
> 抱歉，写错了，是64位的容器 root@debian:~# uname -a Linux debian 5.15.60-1-pve #1 SMP PVE 5.15.60-1 (Mon, 19 Sep 2022 17:53:17 +0200) x86_64 GNU/Linux

如果是x64报错的话, 那么从报错内容上看出来的是 onnxruntime 没有找到对应的ocr模型文件, 有试过重新安装容器么?

**Comment by suyisong** [comment]
没，容器一次性安装成功，上面运行了很多其它docker，应该没问题。

**Comment by a76yyyy** [comment]
请使用开发版镜像尝试, 如果还有问题, 请提供 debug 模式日志

拉取开发版镜像命令:
```shell
docker pull ghcr.io/qiandao-today/qiandao:latest
```

**Comment by a76yyyy** [comment]
请问最新版镜像还有问题么
