### ISSUE TITLE
想问一下这是什么问题？是docker搭建的时候出问题了么 

### ISSUE THREAD

**Issue by hsy66** [qd-today/qd#32]
![image](https://user-images.githubusercontent.com/26462182/99868689-a2a04780-2bff-11eb-9ffa-c2af1414ea32.png)
在其他人搭建的模板上测试都成功，上传到自己的docker上就有问题，但是自己的站点上有一个能签到 不知道是哪里出问题了

**Comment by asdaragon** [comment]
网络问题，一般是在路由上搭建的docker问题，先删除容器，试试这个启动命令docker run -d --name qiandao  --network=host  --env PORT=8193-v $(pwd)/qiandao/config:/usr/src/app/config asdaragon/qiandao
然后通过ip/域名:8193访问

**Comment by hsy66** [comment]
谢谢 设置host网络模式可以了 好像是公共模板里面有几个失效了 所以测试了半天还是失败 然后换了自己的模板就好了 
另外问下 注册推送里 s酱的key提交完了是不会保存么？重新点开推送里面还是空栏

**Comment by asdaragon** [comment]
注册完找个任务测试就行了，没有设置显示前值
