### ISSUE TITLE
[Bug] 无法OCR……

### ISSUE THREAD

**Issue by philboycn** [qd-today/qd#320]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220911

### Bug on OS

Linux

### Bug on Platform

Docker/Windows x64

### To Reproduce

1，使用docker hub拉去latest版本，发现是2021年的版本。
2，于是使用update.sh文件升级最新版本，python版本应该也被升级到了3.10。
3，qiandao升级后显示20220911版本，测试OCR无法使用。
4，于是升级ddddocr，显示：
Collecting ddddocr
  Using cached ddddocr-1.4.7-py3-none-any.whl (75.9 MB)
Requirement already satisfied: Pillow in /usr/lib/python3.10/site-packages (from ddddocr) (9.2.0)
Requirement already satisfied: numpy in /usr/lib/python3.10/site-packages (from ddddocr) (1.23.3)
  Using cached ddddocr-1.4.6-py3-none-any.whl (75.9 MB)
  Using cached ddddocr-1.4.5-py3-none-any.whl (75.9 MB)
  Using cached ddddocr-1.0.6-py3-none-any.whl (6.9 MB)
ERROR: Cannot install ddddocr==1.0.6, ddddocr==1.4.5, ddddocr==1.4.6 and ddddocr==1.4.7 because these package versions have conflicting dependencies.

The conflict is caused by:
    ddddocr 1.4.7 depends on onnxruntime
    ddddocr 1.4.6 depends on onnxruntime
    ddddocr 1.4.5 depends on onnxruntime
    ddddocr 1.0.6 depends on onnxruntime

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
5，翻了翻google，说是python降级3.6-3.9能解决。未尝试。

请问是不是ddddocr和python3.10不兼容？能否更新一下docker hub，使qiandao版本为最新，且OCR能用？谢谢辛苦付出！

### Describe the Bug

请问是不是ddddocr和python3.10不兼容？能否更新一下docker hub，使qiandao版本为最新，且OCR能用？谢谢辛苦付出！

### QianDao log

```shell
请问是不是ddddocr和python3.10不兼容？能否更新一下docker hub，使qiandao版本为最新，且OCR能用？谢谢辛苦付出！
```

### Expected behavior

请问是不是ddddocr和python3.10不兼容？能否更新一下docker hub，使qiandao版本为最新，且OCR能用？谢谢辛苦付出！

**Comment by a76yyyy** [comment]
最新容器版本就是20220911
请发一下你的dockerhub镜像地址, 确认你的docker镜像是 a76yyyy/qiandao
另外不要使用aliyun的镜像源, 这个镜像源一直有问题

**Comment by philboycn** [comment]
> 最新容器版本就是20220911 请发一下你的dockerhub镜像地址, 确认你的docker镜像是 a76yyyy/qiandao 另外不要使用aliyun的镜像源, 这个镜像源一直有问题

我是用的这个命令拉取的镜像呀：
docker pull a76yyyy/qiandao:latest

docker pull a76yyyy/qiandao:latest
latest: Pulling from a76yyyy/qiandao
Digest: sha256:e70d598c76822edea6dab73de33e9c199425aed6a1b8bf03bc7f4c600c3a305f
Status: Image is up to date for a76yyyy/qiandao:latest
docker.io/a76yyyy/qiandao:latest

**Comment by thsrite** [comment]
同版本，无法使用ocr

**Comment by a76yyyy** [comment]
请问你是否有设置镜像源?

**Comment by philboycn** [comment]
> 请问你是否有设置镜像源?

是的，大佬，我忘了我设置阿里镜像源了。我重新拉了一遍，是最新版本了哈，OCR也能用了！不好意思！

**Comment by philboycn** [comment]
谢谢！！
