### ISSUE TITLE
[Bug] 发布之后的模板无法取消发布，始终处于锁定状态

### ISSUE THREAD

**Issue by jhrcc** [qd-today/qd#321]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220901

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

1、选择模板发布
2、接受发布
3、没有取消发布的地方以及按钮

### Describe the Bug

无法取消模板锁定，无法取消模板发布状态

### QianDao config

```shell
无
```

### QianDao log

```shell
无报错
```

### Expected behavior

希望可以对发布的模板进行取消发布并编辑

**Comment by a76yyyy** [comment]
更新源码后重启容器, 就可以**取消发布**状态为 `成功` 的模板了

**Comment by a76yyyy** [comment]
如果有使用问题或bug, 请reopen这个issue

**Comment by jhrcc** [comment]
> 如果有使用问题或bug, 请reopen这个issue

针对这个问题，目前看来是没问题的，谢谢 @a76yyyy
