### ISSUE TITLE
[Bug] Bark定期签到日志推送时由于通知内容过多会超过 GET 请求长度限制

### ISSUE THREAD

**Issue by AemonCao** [qd-today/qd#322]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220911

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

就是在开启定期批量推送时的那条定时通知会有此问题。

查看Bark Server日志发现了500错误，推测可能是超过了 GET 请求的长度限制。

建议使用POST请求来发送通知，具体请求方式可以查看这里：https://github.com/Finb/bark-server/blob/master/docs/API_V2.md#python

### Describe the Bug

就是在开启定期批量推送时的那条定时通知会有此问题。查看Bark Server日志发现了500错误，推测可能是超过了 GET 请求的长度限制。建议使用POST请求来发送通知，具体请求方式可以查看这里：https://github.com/Finb/bark-server/blob/master/docs/API_V2.md#python

### QianDao log

```shell
/
```

### Expected behavior

在通知内容长度过长时可以正常发送Bark请求。

**Comment by a76yyyy** [comment]
现在的bark推送就是 post 方式

**Comment by a76yyyy** [comment]
如果还有问题请reopen这个issue
