### ISSUE TITLE
[Bug] 关于https://pt.btschool.club/网页升级后提示，请使用Java cookies的问题。

### ISSUE THREAD

**Issue by 7161457** [qd-today/qd#325]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220911

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

通过签到编辑页面的测试，发现的提醒。
![1665709325304](https://user-images.githubusercontent.com/113887555/195740165-ab801f69-f8f5-4a1e-9249-d236aa94f1a6.jpg)
并且我在正常网站登录中，也容易激发出来系统的检测。
![1665710521418](https://user-images.githubusercontent.com/113887555/195741483-85f861f3-de81-4ae7-bd36-1acdaa9428cb.jpg)

### Describe the Bug

此签到长期正常使用中，中途网站进行了升级，先是可以进去网页 但是不能进行签到，后期网站也进不去，提示403错误。
![1665708912996](https://user-images.githubusercontent.com/113887555/195740878-413f339a-3584-4f64-8ed7-fcf905d89cb1.jpg)
![1665709704630](https://user-images.githubusercontent.com/113887555/195741181-5fe7a5ed-8abd-48d0-9239-f16e773bed8b.jpg)
![1665709903267](https://user-images.githubusercontent.com/113887555/195741187-2f36af2e-1f99-4796-bb3e-9f189473c0df.jpg)
![1665708950722](https://user-images.githubusercontent.com/113887555/195741190-e4f97fab-7bec-4f9f-9cbe-3c95276cc9b1.jpg)
![1665708967470](https://user-images.githubusercontent.com/113887555/195741192-010d76c3-8b5e-4fb4-912a-53f0622972b2.jpg)
![1665708983511](https://user-images.githubusercontent.com/113887555/195741193-b8c1e04b-3912-4588-b674-d27a70c13639.jpg)
![1665709325304](https://user-images.githubusercontent.com/113887555/195741198-ea6f5df5-8878-4c7a-b2e4-05d9c5db7a23.jpg)
![1665710686734](https://user-images.githubusercontent.com/113887555/195741246-1f1d6e27-4df1-4868-8319-6f6b0857b032.jpg)
![1665710666846](https://user-images.githubusercontent.com/113887555/195741260-93850a3d-7b4a-44d0-8712-c3ad8c203bb5.jpg)

### QianDao config

```shell
截图在上 这里上不了截图。
```

### QianDao log

```shell
截图在上 这里上不了截图。
```

### Expected behavior

![1665708912996](https://user-images.githubusercontent.com/113887555/195741530-6c1128c7-c065-48dd-b846-c11496031562.jpg)
可以正常的在此网站进行签到。

### Screenshots

![1665708950722](https://user-images.githubusercontent.com/113887555/195741652-488b4d48-bbb3-41ba-a13a-d8f2d8fbc5f3.jpg)
![1665708967470](https://user-images.githubusercontent.com/113887555/195741664-3ae542c5-d413-46d5-8969-88201f52a923.jpg)
![1665708983511](https://user-images.githubusercontent.com/113887555/195741666-2385633c-91a2-45d4-be95-da1de3e07d53.jpg)
![1665709325304](https://user-images.githubusercontent.com/113887555/195741670-cc3446fe-6886-4172-ac19-4b93b6a03cf1.jpg)
![1665709704630](https://user-images.githubusercontent.com/113887555/195741675-ca331def-6f4a-489e-9b56-b5a6c30ad564.jpg)
![1665709903267](https://user-images.githubusercontent.com/113887555/195741678-89e9980f-754d-4de5-a730-39e527dcf7d5.jpg)
![1665710521418](https://user-images.githubusercontent.com/113887555/195741683-406cec8e-3d8e-4e69-ba62-b778ceb05524.jpg)
![1665710666846](https://user-images.githubusercontent.com/113887555/195741687-79b2094a-0138-4f69-bcff-6d4cf3a2a395.jpg)
![1665710686734](https://user-images.githubusercontent.com/113887555/195741691-94757b22-9740-4b25-9231-2f1b90785637.jpg)
![1665708912996](https://user-images.githubusercontent.com/113887555/195741694-fa64e9f3-bb1a-4b03-b931-f65764b00e6d.jpg)

**Comment by a76yyyy** [comment]
框架本身不允许任务内部运行JavaScript, 同时该问题属于模板问题, 不是框架的bug, 建议移步模板库相应模板下反馈问题,

该issue将被关闭, 如有其它框架问题请 reopen 这个 issue
