### ISSUE TITLE
[Feature] 支持转大小写的方法

### ISSUE THREAD

**Issue by Kerwin1202** [qd-today/qd#327]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

有的签名之类需要大写，默认 md5 之类的都是小写

### Describe the solution

支持转大小写的方法

### Describe alternatives

我试了正则，但是不好使 ``` {{regex_replace(sign, "([a-z])", "\U\1", 0, True, False)}}	```   会报错

**Comment by Kerwin1202** [comment]
<img width="914" alt="image" src="https://user-images.githubusercontent.com/16319833/196016611-36dc5656-c32c-4c14-87a1-da2abd726cec.png">

以及这是个啥，不支持大小写我就找了个在线的
结果导入curl 就多了一个page_0 保存了下重新打开还一直存在

```
curl --location --request POST 'https://www.iamwawa.cn/home/daxiaoxie/ajax' \
--header 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.47' \
--header 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
--header 'Cookie: PHPSESSID=235mj54doapkjmaq11443tbnt3' \
--data-raw 'text=AAAA2222AAAA&type=1'
```

**Comment by Kerwin1202** [comment]
<img width="871" alt="image" src="https://user-images.githubusercontent.com/16319833/196016780-c77d18de-a182-4a65-a9a7-144e8e2758d1.png">

我插入了一个请求，然后从别的复制了一个replace的 结果保存之后，参数不自动到下面去，修改起来就有点麻烦

**Comment by Kerwin1202** [comment]
<img width="882" alt="image" src="https://user-images.githubusercontent.com/16319833/196017418-8a325a8e-f337-4dec-b154-2b1cc1cceb0f.png">

这里每次从这里保存的都会丢，不存   text=AAAA2222AAAA&type=1

**Comment by Kerwin1202** [comment]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/16319833/196017822-98c90997-f167-45a4-8129-601d2cd634d0.png">

这里概率会丢，比如刚点击过另一个请求，再点击这个，打开就丢了



以上是 20220911 版本

**Comment by a76yyyy** [comment]
使用 `{{ 变量 | lower}}` 实现小写; 使用 `{{ 变量 | upper}}` 实现大写;

**Comment by a76yyyy** [comment]
不同的问题提多个issue吧, 方便我统计和维护开发, 我先把这个 issue 关了

**Comment by a76yyyy** [comment]
> <img alt="image" width="914" src="https://user-images.githubusercontent.com/16319833/196016611-36dc5656-c32c-4c14-87a1-da2abd726cec.png">
> 
> 以及这是个啥，不支持大小写我就找了个在线的 结果导入curl 就多了一个page_0 保存了下重新打开还一直存在
> 
> ```
> curl --location --request POST 'https://www.iamwawa.cn/home/daxiaoxie/ajax' \
> --header 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.47' \
> --header 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
> --header 'Cookie: PHPSESSID=235mj54doapkjmaq11443tbnt3' \
> --data-raw 'text=AAAA2222AAAA&type=1'
> ```

page_0 是考虑兼容性固定存在的, 不影响使用

**Comment by a76yyyy** [comment]
> <img alt="image" width="871" src="https://user-images.githubusercontent.com/16319833/196016780-c77d18de-a182-4a65-a9a7-144e8e2758d1.png">
> 
> 我插入了一个请求，然后从别的复制了一个replace的 结果保存之后，参数不自动到下面去，修改起来就有点麻烦

最新版源码可以自动显示, 可以尝试一下, 如果不可以, 请重开一个issue, 说明自己的浏览器型号和版本

**Comment by a76yyyy** [comment]
> <img alt="image" width="592" src="https://user-images.githubusercontent.com/16319833/196017822-98c90997-f167-45a4-8129-601d2cd634d0.png">
> 
> 这里概率会丢，比如刚点击过另一个请求，再点击这个，打开就丢了
> 
> 以上是 20220911 版本

已知问题, 还没有复现出来, 请耐心等待修复
