### ISSUE TITLE
[Feature] 企业微信推送可否增加自定义代理

### ISSUE THREAD

**Issue by thsrite** [qd-today/qd#328]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

企业微信推送可否增加自定义代理

家宽ip经常变。vps nginx反代的话体验会好很多。

### Describe the solution

  server 
     {
         listen 80;
         server_name  域名;

         location /cgi-bin/gettoken {
  			proxy_pass https://qyapi.weixin.qq.com;
		}
		location /cgi-bin/message/send 
		{
  			proxy_pass https://qyapi.weixin.qq.com; 
		}
     }
}

**Comment by a76yyyy** [comment]
源码已更新, 请自行测试

**Comment by thsrite** [comment]
> 源码已更新, 请自行测试

企业微信 推送失败, 失败原因: Expecting value: line 1 column 1 (char 0)

**Comment by thsrite** [comment]
企业微信 已推送,请检查是否收到

但是没收到

**Comment by a76yyyy** [comment]
格式正确么?

**Comment by a76yyyy** [comment]
发一下后台错误日志吧

**Comment by a76yyyy** [comment]
请问还有问题么? 如果还有的话请 reopen 这个 issue.
