### ISSUE TITLE
[Feature] 关于现在每次签到都失败，因为会跳转此名称的防护。Cloudflare

### ISSUE THREAD

**Issue by 7161457** [qd-today/qd#329]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

关于现在每次签到都失败，因为会跳转此名称的防护。Cloudflare

### Describe the solution

可以过掉此程序的防护，正常签到

### Additional context

![1666499917749](https://user-images.githubusercontent.com/113887555/197374128-906f312a-1b4c-472e-b9a8-26c6576f0f5a.jpg)
防护的网站https://www.cloudflare.com/zh-cn/

**Comment by 7161457** [comment]
![1666500160380](https://user-images.githubusercontent.com/113887555/197374193-58f02866-ae99-4fb9-94cc-8b4bb4b1f5fc.jpg)

**Comment by a76yyyy** [comment]
参见 qiandao-today/qiandao#184 qiandao-today/qiandao#86
