### ISSUE TITLE
[Feature] 关于过cloudflare盾返回599状态码的时间希望可以自定义，不要30000.

### ISSUE THREAD

**Issue by 7161457** [qd-today/qd#330]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

现在很多PT站都有cloudflare，当我在用FlareSolverr过盾的时候，明明FlareSolverr正在运行并且成功返回，但是由于签到设置的是30000自动返回599，所以很多时候FlareSolverr过盾成功了，但是签到程序在过盾成功之前返回了599状态码。希望可以自定义maxTimeout的时间。

### Describe the solution

现在很多PT站都有cloudflare，当我在用FlareSolverr过盾的时候，明明FlareSolverr正在运行并且成功返回，但是由于签到设置的是30000自动返回599，所以很多时候FlareSolverr过盾成功了，但是签到程序在过盾成功之前返回了599状态码。希望可以自定义maxTimeout的时间。

### Additional context

![1667143095307](https://user-images.githubusercontent.com/113887555/198887049-0cd08b7f-e2a8-44b5-a807-6daabf8dc4f0.jpg)
![1667143121995](https://user-images.githubusercontent.com/113887555/198887053-7bca9980-94ea-49f1-a8b7-1ec2ec56ecdb.jpg)
![1667143150405](https://user-images.githubusercontent.com/113887555/198887055-5ca0348c-7615-41c5-8c94-70c4d9af3cff.jpg)

**Comment by 7161457** [comment]
已经通过模糊修改3处环境变量成功，但是不清楚具体哪一个是的，请作者明鉴告诉。
![1667305223662](https://user-images.githubusercontent.com/113887555/199231226-ae6350ef-3776-4c90-8638-2603fd117f1a.jpg)

**Comment by a76yyyy** [comment]
> 已经通过模糊修改3处环境变量成功，但是不清楚具体哪一个是的，请作者明鉴告诉。 ![1667305223662](https://user-images.githubusercontent.com/113887555/199231226-ae6350ef-3776-4c90-8638-2603fd117f1a.jpg)

三个变量是相关的, 具体请参考 https://github.com/qiandao-today/qiandao/blob/master/config.py#L89
