### ISSUE TITLE
[Feature] 能否增加form表单提交支持？

### ISSUE THREAD

**Issue by youzongku** [qd-today/qd#331]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

有些场景会使用到form表单提交数据，不知道能否添加支持

### Describe the solution

有些场景会使用到form表单提交数据，不知道能否添加支持

**Comment by a76yyyy** [comment]
请提供用于测试的框架不支持的har

**Comment by youzongku** [comment]
> 请提供用于测试的框架不支持的har

[瓷器cookie.zip](https://github.com/qiandao-today/qiandao/files/9925241/cookie.zip)

这个har里面签到那个请求，现在这种方式请求失败，postman参数放form-data可以用

**Comment by a76yyyy** [comment]
抱歉, 我没有瓷器的账号, 前段时间一直忘了测试.
今天测试没有发现不支持 form-data 的 har (瓷器的har没有账号, 所以没有测试结果).
可以放一下瓷器失败的 `预览 /Preview` 和 `结果 /Headers` 截图看一下 (隐去cookie等隐私信息)

PS: 请更新至最新源码后尝试, 如果没有问题请 close 这个 issue

**Comment by a76yyyy** [comment]
如果有问题, 请 reopen 这个 issue
