### ISSUE TITLE
[Bug] Docker.ja3 访问某https网站出现 BoringSSL SSL_connect: Connection reset by peer in connection

### ISSUE THREAD

**Issue by nsnake** [qd-today/qd#338]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220911

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

[E 221129 15:37:23 qiandao.Http.Fetcher fetcher:470] BoringSSL SSL_connect: Connection reset by peer in connection to www.wnflb99.com:443 

[E 221129 15:37:23 qiandao.Worker worker:267] taskid:8 tplid:7 failed! 0.7279s 

    Failed at 1/4 request, 

    Fail assert: {"re": "200", "from": "status"} from success_asserts, 

    Response Error : HTTP 599: BoringSSL SSL_connect: Connection reset by peer in connection to www.wnflb99.com:443 , 

    Request URL: https://www.wnflb99.com/plugin.php?id=fx_checkin%3Alist

[W 221129 15:37:28 qiandao.Http.Fetcher fetcher:466] GET https://www.wnflb99.com/plugin.php?id=fx_checkin%3Alist [Warning] HTTP 599: BoringSSL SSL_connect: Connection reset by peer in connection to www.wnflb99.com:443  -> Try to retry!

[E 221129 15:37:28 qiandao.Http.Fetcher fetcher:470] BoringSSL SSL_connect: Connection reset by peer in connection to www.wnflb99.com:443 

[E 221129 15:37:28 qiandao.Web.Handler task:191] taskid:8 tplid:7 failed! 2.3505s 

    Failed at 1/4 request, 

在对福利吧站进行签到时出现无法签到成功的问题

    Fail assert: {"re": "200", "from": "status"} from success_asserts, 

    Response Error : HTTP 599: BoringSSL SSL_connect: Connection reset by peer in connection to www.wnflb99.com:443 , 

    Request URL: https://www.wnflb99.com/plugin.php?id=fx_checkin%3Alist

### Describe the Bug

视乎是对证书选择出现了错误

### QianDao config

```shell
不需要
```

### QianDao log

```shell
不需要
```

### Expected behavior

不需要

**Comment by a76yyyy** [comment]
是只有这个网站不行还是所有网站都有问题

**Comment by spin6lock** [comment]
我也遇到类似的问题，smzdm签到挂了，提示HTTP 599，不过我是OpenSSL不是BoringSSL，后面发现是和服务器的cipher对不上

查看服务器的cipher：[参考这篇](https://superuser.com/questions/109213/how-do-i-list-the-ssl-tls-cipher-suites-a-particular-website-offers)
查看OpenSSL的cipher：```openssl ciphers 'ALL:eNULL' | sed -e 's/:/\n/g'```

PS：我用20220911的docker版本似乎没自带BoringSSL，是需要配置什么选项吗？

**Comment by a76yyyy** [comment]
> PS：我用20220911的docker版本似乎没自带BoringSSL，是需要配置什么选项吗？

Boringssl 是 ja3 版本使用的

**Comment by a76yyyy** [comment]
万能福利吧新模板已上传, 如果还是不行请 reopen 这个issue
