### ISSUE TITLE
[Bug] docker lite镜像 丢失Request Payload参数

### ISSUE THREAD

**Issue by LSD08KM** [qd-today/qd#339]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220911

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 32位

### To Reproduce

编辑模板时，点击请求列表中包含Request Payload参数的请求，会大概率导致Request Payload的参数消失。

- 如果Request Payload内有{{变量}}，点开请求时，变量会变成值。
- 如果Request Payload参数是固定值，点开请求时，Request Payload会被清空。如果一次没有清空，多点两三次肯定会被清空。

### Describe the Bug

请求tab最下方Request Payload消失问题。只发生在lite镜像，尝试了普通镜像没有此bug

### QianDao log

```shell
无日志
```

### Expected behavior

修复

**Comment by a76yyyy** [comment]
请使用开发版镜像尝试, 如果还有问题, 请提供可复现问题的har

拉取开发版镜像命令:
```shell
docker pull ghcr.io/qiandao-today/qiandao-lite:latest
```

**Comment by a76yyyy** [comment]
请问还有问题么?
