### ISSUE TITLE
原项目过来，2个小问题请求解答

### ISSUE THREAD

**Issue by if1y** [qd-today/qd#34]
1. 使用上，如何能提取返回内容，使之展示在签到执行日志中呢

2. 这个修改的版本可以按条件发提醒吗，比如：签到成功时不推送提醒，出现异常才推送？

感谢维护！

**Comment by asdaragon** [comment]
![JMD6%UE$YGV9`I1$QS~ 816](https://user-images.githubusercontent.com/22835918/101276396-4b959780-37e7-11eb-8b6a-3b376ef4aad4.png)
1. 模板编辑页面，切换到这条请求的预览页，赋值通过正则提取信息，给变量__log__，就可以把你想要的内容提取到日志
 
![N)63CEAY9C3~Y0)%TQ% F3D](https://user-images.githubusercontent.com/22835918/101276429-9f07e580-37e7-11eb-8719-de6f298c8c57.png)
2. 把推送注册后，选择推送设置-自动执行失败通知即可

**Comment by if1y** [comment]
好的非常感谢，这两个问题解决了我的痛点。
刚把镜像切过来，再琢磨琢磨。
