### ISSUE TITLE
[Feature] 签到失败禁用的任务，第二天能自动恢复执行吗

### ISSUE THREAD

**Issue by yeyinghai** [qd-today/qd#341]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

签到失败禁用的任务，第二天能自动恢复执行吗》

### Describe the solution

签到失败禁用的任务，第二天能自动恢复执行吗》

**Comment by a76yyyy** [comment]
禁用之后需要手动恢复执行的

**Comment by a76yyyy** [comment]
如果只是询问的话, 将关闭此 issue, 如果需要提交新特性需求, 请完善需求内容后 reopen 这个 issue.
