### ISSUE TITLE
[Bug] Cannot save Test variables when editing HAR

### ISSUE THREAD

**Issue by einverne** [qd-today/qd#346]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20221218

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

This bug exists when adding new template or editing an exist template.

When adding a new template, it cannot save the Variables I added.

### Describe the Bug

This bug exists when adding new template or editing an exist template.

When adding a new template, it cannot save the Variables I added.

### QianDao config

```shell
version: "3"

services:
  qiandao:
    image: a76yyyy/qiandao:latest
    # image: a76yyyy/qiandao:lite-latest
    container_name: qiandao
    depends_on:
      - redis
    volumes:
      - "${QIANDAO_CONFIG}:/usr/src/app/config"
    environment:
      - QIANDAO_DEBUG=False
      # - MULTI_PROCESS=False
      # - AUTO_RELOAD=False
      # - GZIP=True
      # - BIND=0.0.0.0
      # - PORT=80
      # - QUEUE_NUM=50
      # - ENABLE_HTTPS=False
      # - ACCESS_LOG=True
      - DOMAIN=${DOMAIN}
      # - USE_PYCURL=True
      # - ALLOW_RETRY=True
      # - DNS_SERVER=
      # - CURL_ENCODING=True
      # - CURL_CONTENT_LENGTH=True
      # - NOT_RETRY_CODE=301|302|303|304|305|307|400|401|403|404|405|407|408|409|410|412|415|413|414|500|501|502|503|504|599
      # - EMPTY_RETRY=True
      # - COOKIE_DAY=5
      # - JAWSDB_MARIA_URL=mysql://user:pass@localhost:3306/dbname?auth_plugin=
      - REDISCLOUD_URL=redis://redis:6379
      # - TRACEBACK_PRINT=False
      # - PUSH_PIC_URL=https://fastly.jsdelivr.net/gh/a76yyyy/qiandao@master/web/static/img/push_pic.png
      # - PUSH_BATCH_SW=True
      # - PUSH_BATCH_DELTA=60
      - DB_TYPE=sqlite3
      # - QIANDAO_SQL_LOGGING_NAME=qiandao.sql
      # - QIANDAO_SQL_LOGGING_LEVEL=WARNING
      # - QIANDAO_SQL_POOL_LOGGING_NAME=qiandao.sql.pool
      # - QIANDAO_SQL_POOL_LOGGING_LEVEL=WARNING
      # - QIANDAO_SQL_POOL_SIZE=5
      # - QIANDAO_SQL_MAX_OVERFLOW=10
      # - QIANDAO_SQL_POOL_PRE_PING=True
      # - QIANDAO_SQL_POOL_RECYCLE=3600
      # - QIANDAO_SQL_POOL_TIMEOUT=30
      # - QIANDAO_SQL_POOL_USE_LIFO=True
      # - REDIS_DB_INDEX=1
      # - QIANDAO_EVIL=1000
      # - EVIL_PASS_LAN_IP=True
      - PBKDF2_ITERATIONS=400
      - AES_KEY=${AES_KEY}
      - COOKIE_SECRET=${COOKIE_SECRET}
      # - CHECK_TASK_LOOP=500
      # - DOWNLOAD_SIZE_LIMIT=5242880
      # - REQUEST_TIMEOUT=30.0
      # - CONNECT_TIMEOUT=30.0
      # - DELAY_MAX_TIMEOUT=29.9
      # - PROXIES=
      # - PROXY_DIRECT_MODE=regexp
      # - PROXY_DIRECT=(?xi)\A([a-z][a-z0-9+\-.]*://)?(0(.0){3}|127(.0){2}.1|localhost|\[::([\d]+)?\])(:[0-9]+)?
      # - NEW_TASK_DELAY=1
      # - EXTRA_ONNX_NAME=
      # - EXTRA_CHARSETS_NAME=
      # - NEW_TASK_DELAY=1
      - MAIL_SMTP=${MAIL_SMTP}
      - MAIL_PORT=${MAIL_PORT}
      # - MAIL_SSL=True
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_USER}
      # - MAIL_DOMAIN=
      # - MAILGUN_KEY=
      # - USER0ISADMIN=True

  redis:
    image: redis:alpine
    container_name: redis
    command: ["--loglevel warning"]
    # command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./redis/data:/data:rw

networks:
  default:
    name: nginx-proxy
    external: true
```

### QianDao log

```shell
qiandao  | [I 221228 14:54:06 tornado.access web:2271] 200 GET /har/edit (172.70.223.2) 11.69ms
qiandao  | [W 221228 14:54:51 tornado.access web:2271] 400 POST /tpl/run (172.68.118.217) 5.82ms
qiandao  | [W 221228 14:54:54 tornado.access web:2271] 400 POST /tpl/run (172.68.118.217) 3.70ms
qiandao  | [I 221228 14:55:02 tornado.access web:2271] 200 POST /har/test (172.68.118.217) 306.66ms
qiandao  | [I 221228 14:55:20 tornado.access web:2271] 200 POST /har/save?reponame=&name= (172.68.118.217) 91.64ms
qiandao  | [I 221228 14:55:20 tornado.access web:2271] 200 GET /tpl/26/edit (172.68.118.217) 7.31ms
qiandao  | [I 221228 14:55:22 tornado.access web:2271] 200 POST /tpl/26/edit (172.68.118.217) 36.62ms
qiandao  | [I 221228 14:55:25 tornado.access web:2271] 200 GET /my/ (172.68.118.217) 202.89ms
qiandao  | [I 221228 14:55:27 tornado.access web:2271] 200 GET /task/new?tplid=26 (172.68.118.217) 29.96ms
qiandao  | [I 221228 14:55:32 tornado.access web:2271] 200 GET /tpl/26/edit (172.68.118.217) 8.73ms
qiandao  | [I 221228 14:55:33 tornado.access web:2271] 200 POST /tpl/26/edit (172.68.118.217) 71.45ms
qiandao  | [I 221228 14:55:56 tornado.access web:2271] 200 POST /tpl/26/save?reponame=&name= (172.68.118.217) 110.20ms
```

### Expected behavior

I expect that I can save the `cookie` variable.

<img width="914" alt="image" src="https://user-images.githubusercontent.com/1962738/209772474-9fdf3acc-d2cf-4c8d-952c-85d517ad4b44.png">

and click 保存

<img width="334" alt="image" src="https://user-images.githubusercontent.com/1962738/209772529-f9023fe5-2928-457d-bf70-659b38ab1711.png">

When I reopen the page, or edit the template

<img width="909" alt="image" src="https://user-images.githubusercontent.com/1962738/209772636-3ccf928f-8550-49da-93c4-75930abf74de.png">

There is no variable.

**Comment by a76yyyy** [comment]
Test variables are only used for testing and cannot be saved. If you want to save variables, please create variables by creating `{{variable}}` in the "请求" tab

**Comment by einverne** [comment]
I have created a variable using the `{{cookie}}` syntax in the Request page. But it not working after saving it as a template.

I have checked other templates from https://github.com/qiandao-today/templates, they all have default Test variables.

<img width="905" alt="image" src="https://user-images.githubusercontent.com/1962738/209903317-aabeb610-7a72-4188-9d48-e0ad3566d9f9.png">

**Comment by a76yyyy** [comment]
Here are some older tutorials on making templates, involving some variable creation and extraction operations.
- Video: 
[一个辛苦的自动签到模板制作过程~~~](https://www.bilibili.com/video/BV1ox411C7RT)
[自动签到2 自己制作一个模板与输出日志 qiandao](https://www.bilibili.com/video/BV1By4y1y7ar)
[自动签到3 制作 discuz 点击签到模板](https://www.bilibili.com/video/BV1Nt4y1e7EQ)

- HTML:
[自建一个 PSNine 自动签到服务](https://blog.abyss.moe/posts/Qiandao/)

**Comment by einverne** [comment]
I have found the problem, I have to check the checkbox before the request, and then click the save button. All the modifications I made will be saved. If I did not check the checkbox, I would lose my modifications. It is not a bug, but it let me confused. Thank you for your help. I will close the issue.
