### ISSUE TITLE
[Feature] 烦请增加功能，支持6位cron定时

### ISSUE THREAD

**Issue by zhuyaozi** [qd-today/qd#347]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

目前只支持5位cron，最短只能1分钟请求一次，有一些论坛需要保持在线的，只能通过2条请求之间插入时延的方式来缩短间隔

### Describe the solution

支持6位cron，正好可以把原定时下面的”精确到秒“的功能整合掉，

**Comment by a76yyyy** [comment]
请更新源码后尝试, 如无问题请 close 这个 issue
