### ISSUE TITLE
[Feature] 注册时候管理员密码只填写一次，我的密码可能按错了。现在怎么办？？

### ISSUE THREAD

**Issue by sycpiek** [qd-today/qd#349]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

第一次填写密码的时候可能输入错误了，现在上不去了。邮箱找回也收不到邮件。现在应该怎么办？

### Describe the solution

第一次填写密码的时候可能输入错误了，现在上不去了。邮箱找回也收不到邮件。现在应该怎么办？

**Comment by zhuyaozi** [comment]
新注册一个账号，设置成管理员，再改之前的账号密码

**Comment by sycpiek** [comment]
我应该如何操作呢？比较小白。

**Comment by sycpiek** [comment]
解决了 谢谢
