### ISSUE TITLE
使用20202.12.04最新的Docker镜像后，任务运行结束后仍有'logDay'报错。

### ISSUE THREAD

**Issue by billysun76** [qd-today/qd#35]
如题，使用最新镜像，运行签到任务，成功后看日志还是有logDay报错，导致任务反复重试执行，多次出错后自动禁用。

2020-12-7 9:52:01 | 失败 | failed at 1/4 request, , https://www.52pojie.cn/home.php?mod=task&do=apply&id=2
2020-12-7 3:51:51 | 失败 | 'logDay'
2020-12-7 3:51:51 | 成功 | 吾爱币 :  651 CB CB
2020-12-6 23:51:41 | 失败 | failed at 1/4 request, , https://www.52pojie.cn/home.php?mod=task&do=apply&id=2
2020-12-6 22:01:31 | 失败 | failed at 1/4 request, , https://www.52pojie.cn/home.php?mod=task&do=apply&id=2
2020-12-6 21:51:21 | 失败 | 'logDay'
2020-12-6 21:51:21 | 成功 | 吾爱币 :  649 CB CB
2020-12-5 21:51:14 | 成功 | 吾爱币 :  647 CB CB

Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1510, in _execute
result = method(*self.path_args, **self.path_kwargs)
File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 2898, in wrapper
return method(self, *args, **kwargs)
File "/usr/src/app/web/handlers/site.py", line 30, in get
self.render("site_manage.html", userid=userid, adminflg=adminflg, site=site, logDay=site['logDay'])
KeyError: 'logDay'

**Comment by asdaragon** [comment]
是不是先升级了1120再升级的1204？

**Comment by billysun76** [comment]
> 是不是先升级了 1120 再升级的 1204？

我是用的Docker，1120是第一次建的，发现有logDay的问题，然后升级的1204，刚升完以为正常了就没管，结果这两天发现又开始报错了。

**Comment by hsy66** [comment]
我也同样，把镜像删了重新拉取同样报错logday

**Comment by My-stery** [comment]
同样也有该种问题依旧logday

**Comment by asdaragon** [comment]
@hsy66 @billysun76 @My-stery  已经修复，更新镜像即可
