### ISSUE TITLE
[Feature] 编辑模板时的代理选项

### ISSUE THREAD

**Issue by Cirn09** [qd-today/qd#353]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

创建签到任务时可以设置代理，但创建模板时只能使用全局的设置。在为需要代理的网站创建模板时，测试起来非常麻烦。

### Describe the solution

最简单的实现方法是检测变量，如果创建了变量 `__proxy__`，则使用 `__proxy__` 的值作为代理。否则使用全局设置。

**Comment by Cirn09** [comment]
这个在写了吗，我最近闲下来了，可以帮忙完成

我还没看过代码，目前的思路是把模板编辑和实际工作两模块的代理选项都统一成访问 `__proxy__ `

**Comment by a76yyyy** [comment]
> 这个在写了吗，我最近闲下来了，可以帮忙完成
> 
> 我还没看过代码，目前的思路是把模板编辑和实际工作两模块的代理选项都统一成访问 `__proxy__ `

最近在忙自己的事, 预计下个月继续维护本项目, 你可以尝试按照你的思路提交一个PR, 我之后进行merge
