### ISSUE TITLE
[Feature] 延时时间为什么限制最高30s？

### ISSUE THREAD

**Issue by Antiky** [qd-today/qd#355]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

seconds:延时指定时间 大于30s均视为延时30.0s
是有什么线程超时的说法吗

### Describe the solution

我自己只能曲线救国
api://util/unicode?content=1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%2C11%2C12%2C13%2C14%2C15%2C16%2C17%2C18%2C
{% for index in list %}
api://util/delay/30
{% endfor %}

循环18次是九分钟

### Describe alternatives

util/delay/限制改一下参数就好了

**Comment by a76yyyy** [comment]
config.py 里有相关超时配置参数

https://github.com/qiandao-today/qiandao/blob/c09d6ca98a0dbb7095f03f2bdefcada2ab5bf9bb/config.py#L89-L91

如果使用docker-compose部署的话可以修改这部分内容(去掉注释符号`# `)

https://github.com/qiandao-today/qiandao/blob/c09d6ca98a0dbb7095f03f2bdefcada2ab5bf9bb/docker-compose.yml#L58-L60

**Comment by Antiky** [comment]
已解决，也就是说config.py对应的参数项都是可以写到docker的环境里的
但是要放模板库里的话还是得长循环：https://github.com/Antiky/Qiandao-stage1st
可以合进templates里

**Comment by a76yyyy** [comment]
> 已解决，也就是说config.py对应的参数项都是可以写到docker的环境里的 但是要放模板库里的话还是得长循环：https://github.com/Antiky/Qiandao-stage1st 可以合进templates里

公共模板库建议还是按照公开配置走比较好

模板可以直接提交PR 到 [qiandao-today/templates](https://github.com/qiandao-today/templates)
