### ISSUE TITLE
[Bug] 日志输出为None

### ISSUE THREAD

**Issue by yikwongee** [qd-today/qd#362]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20230111

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

<img width="644" alt="image" src="https://user-images.githubusercontent.com/77314844/215283060-d32a0a72-327d-4eeb-b1d8-0563957983c5.png">
<img width="678" alt="image" src="https://user-images.githubusercontent.com/77314844/215283099-82845c75-567c-45ba-9b6d-a11460e0ef51.png">

以上已经获取到参数，并且测试日志输出没有任何问题！但是正常签到就出了问题，以下为输出日志：
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/77314844/215283195-97df749f-fa9e-4dbd-a697-fe96ba41b414.png">

### Describe the Bug

测试一切正常，正常运行输出日志为None

### QianDao log

```shell
无
```

### Expected behavior

无

**Comment by a76yyyy** [comment]
测试正常，请检查正则表达式，cookie等信息是否正确，及网页是否有正确响应。

如果仍未解决问题，请提供测试用har，并确保该网站可以正常注册

**Comment by a76yyyy** [comment]
如果有问题, 请 reopen 这个 issue
