### ISSUE TITLE
[Feature] 如何取数组下标

### ISSUE THREAD

**Issue by Aiome** [qd-today/qd#364]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

sidArr数据
["213456653","213456650","213456652","213456649","213456648","213456651","213441245","213441246","213441244","212971114","212971113","212971100"]
stateArr数据
["01","01","01","01","01","01","02","02","02","02","02","02"]
sidArr与stateArr 数据一一对应

![image](https://user-images.githubusercontent.com/15247336/215936008-c6f07cf6-82bc-4e53-97bb-afc528d13000.png)

诉求

`{% for sid in sidArr %}                                         `
`         {% if stateArr[当前循环下标] == "01" %}   `
`              发送请求                                               `
`         {% endif %}                                                `
`{% endfor %}                                                       `
jinja语法可以通过loop.index拿到下标，但是咱这框架不支持，我这种诉求可以通过什么样的方式来满足？

### Describe the solution

如上

**Comment by a76yyyy** [comment]
Feat 86b04cec293f14c8860bcc803e3712dee1f911b3

**Comment by jyz0501** [comment]
是否支持for 循环嵌套，或者说，我有三个一一对应的数组，如何循环提交包含多个变量的请求

**Comment by a76yyyy** [comment]
> 是否支持for 循环嵌套，或者说，我有三个一一对应的数组，如何循环提交包含多个变量的请求

支持for循环嵌套
