### ISSUE TITLE
[Bug] /util/delay?seconds=15 直接意外终止

### ISSUE THREAD

**Issue by yikwongee** [qd-today/qd#365]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20230111

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

请求 http://ip:8923/util/delay?seconds=15 时等了一会儿浏览器就显示无法访问此网站

 意外终止了连接。
请试试以下办法：
检查网络连接
ERR_CONNECTION_CLOSED

在模版中用使用也是如此
但是很奇怪 4秒包括4秒以下就没问题 5秒以上就终止连接了

### Describe the Bug

util/delay  api工具 响应超时

### QianDao log

```shell
无
```

### Expected behavior

修复一下

**Comment by a76yyyy** [comment]
测试没有问题, 请检查你的 config 配置

**Comment by a76yyyy** [comment]
如果还有问题, 请 reopen 这个 issue, 同时提交 debug 模式的错误信息
