### ISSUE TITLE
我的模板中增加类似公共模板的备注说明

### ISSUE THREAD

**Issue by OwnerCM** [qd-today/qd#366]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

我的模板添加后无法进行备注说明，对新用户有一定的使用难度。

### Describe the solution

在我的模板中增加类似公共模板的备注说明。

**Comment by a76yyyy** [comment]
订阅公共模板自动保存备注，新建模板时提供模板说明
