### ISSUE TITLE
docker 进入容器你后更新最新版重启打不开 日志显示：ModuleNotFoundError: No module named 'aiohttp'

### ISSUE THREAD

**Issue by jichun29** [qd-today/qd#370]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

最新版

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

docker 进入容器你后更新最新版重启打不开 日志显示：ModuleNotFoundError: No module named 'aiohttp'

### Describe the Bug

docker 进入容器你后更新最新版重启打不开 日志显示：ModuleNotFoundError: No module named 'aiohttp'

### QianDao log

```shell
[W 230213 09:18:11 qiandao.RedisDB redisdb:28] Connect Redis falied: Error 101 connecting to localhost:6379. Network unreachable.
[W 230213 09:18:11 qiandao.RedisDB redisdb:28] Connect Redis falied: Error 101 connecting to localhost:6379. Network unreachable.
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 58, in 
    from web.app import Application
  File "/usr/src/app/web/app.py", line 17, in 
    from web.handlers import handlers, ui_modules, ui_methods
  File "/usr/src/app/web/handlers/__init__.py", line 26, in 
    module = __import__('%s.%s' % (__package__, module), fromlist = ["handlers"])
  File "/usr/src/app/web/handlers/subscribe.py", line 15, in 
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
```

### Expected behavior

可以正常访问

**Comment by a76yyyy** [comment]
更新前版本号多少？
使用什么方式更新的呢？

**Comment by zhuzhuani** [comment]
我有同样的问题 更新前为20220911  更新后报错 报错内容和楼上一样 docker部署

**Comment by zhuzhuani** [comment]
> 我有同样的问题 更新前为20220911 更新后报错 报错内容和楼上一样 docker部署

解决方案：暂停容器 删除容器 拉取最新版本 创建容器 完事

**Comment by a76yyyy** [comment]
问题应该是没有先更新 `update.sh`, 直接使用旧版 `update.sh` 更新导致模块缺失

如果还有问题, 请 reopen 这个 issue.
