### ISSUE TITLE
[Feature] while( condition ) { } 循环功能

### ISSUE THREAD

**Issue by sagan** [qd-today/qd#371]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

目前 QianDao 支持的 for 循环语法：

{% for bar in bars %}
{% endfor %}

这个语法无法支持不定长次数的循环场景。例如，[绯月论坛](https://bbs.kfpromax.com/) 的每日“争夺”小游戏（能够获取论坛积分）的调用方式是循环向同一个url发送请求，直到服务器 response 返回 "no" 表示本日游戏结束并获取到了奖励。

### Describe the solution

加入 while 控制的循环功能，语法类似这种：

{% while condition %}
{% endwhile %}

**Comment by OwnerCM** [comment]
遇到类似问题，的确很需要这个功能，王哥加油！！！

**Comment by a76yyyy** [comment]
@sagan  @OwnerCM  请更新到最新dev版后尝试该功能, 如果有问题请及时反馈

**Comment by a76yyyy** [comment]
如果有问题, 请 reopen 这个 Issue
