### ISSUE TITLE
if 、for循环命令中无法使用‘%’取余

### ISSUE THREAD

**Issue by OwnerCM** [qd-today/qd#374]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20230111

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

因为if、for循环系统标识中已包含%，导致判断条件不能使用‘%’计算取余数，如下：
{% if days|int % 7 == 0 %}

### Describe the Bug

取余符号跟{%标识冲突

### QianDao log

```shell
<class 'TypeError'>: "unsupported operand type(s) for %: 'type' and 'int'" while evaluating 'days|int % 7 == 0 '
```

### Expected behavior

希望可以增加‘%’取余计算逻辑

**Comment by a76yyyy** [comment]
使用 
`{% if int(days) % 7 == 0 %}`

在if判断里使用`int(days)`来将`str`转换为整数

**Comment by OwnerCM** [comment]
> 在if判断里使用`int(days)`来将`str`转换为整数

这种方式也使用过了，同样报错，错误如下（我感觉是因为%的关系）：
![41PU}MFLCS22W({D@{J C T](https://user-images.githubusercontent.com/22722811/220377833-62bc1558-1863-4248-935a-c6bdb2806944.png)

**Comment by a76yyyy** [comment]
> > 在if判断里使用`int(days)`来将`str`转换为整数
> 
> 这种方式也使用过了，同样报错，错误如下（我感觉是因为%的关系）： ![41PU}MFLCS22W({D@{J C T](https://user-images.githubusercontent.com/22722811/220377833-62bc1558-1863-4248-935a-c6bdb2806944.png)

暂时只支持在 `if` API里使用 `int(days)`, 其他地方请使用 `{{days|int % 7}}`

**Comment by OwnerCM** [comment]
已经解决，谢谢王哥
