### ISSUE TITLE
[Bug] 升级到新版本后，所有任务都消失了

### ISSUE THREAD

**Issue by sunjx97** [qd-today/qd#375]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20230111

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

升级到最新的qiandao容器

### Describe the Bug

所有任务都消失了。

经过比较，我发现运行新版docker容器后，数据库多了notepad和taskold两个表，所有任务都到了taskold表下，这是什么情况？我能做些什么，让我的任务重新出现吗？

### QianDao log

```shell
无报错

[W 230222 23:03:56 qiandao.RedisDB redisdb:28] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.
[W 230222 23:03:56 qiandao.RedisDB redisdb:28] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.
[W 230222 23:03:57 qiandao.RedisDB redisdb:28] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.
[W 230222 23:03:57 qiandao.RedisDB redisdb:28] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.
[W 230222 23:03:57 qiandao.RedisDB redisdb:28] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.
[W 230222 23:03:57 qiandao.RedisDB redisdb:28] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.
[W 230222 23:03:57 qiandao.RedisDB redisdb:28] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.
[I 230222 23:03:57 qiandao.Worker worker:273] Queue Worker start...
[I 230222 23:03:57 qiandao.Run run:83] Http Server started on 0.0.0.0:80
```

### Expected behavior

可以看到我原来所有的任务

**Comment by a76yyyy** [comment]
将 taskold 表重命名为 task

**Comment by sunjx97** [comment]
操作过程中显示：database disk image is malformed

**Comment by a76yyyy** [comment]
> 操作过程中显示：database disk image is malformed

改名操作不应该会导致数据库损坏, 你如果映射了数据库文件的话, 建议关闭容器后修改数据库, 再启动容器, 否则可能会和容器内数据库连接发生冲突

**Comment by a76yyyy** [comment]
如果还有问题请reopen这个issue

**Comment by sunjx97** [comment]
还是不行……我一个个手动重新创建任务吧 orz
话说为什么上新版本后会有 task 和 taskold 两个表……

**Comment by a76yyyy** [comment]
> 还是不行……我一个个手动重新创建任务吧 orz 话说为什么上新版本后会有 task 和 taskold 两个表……

更新版本会先进行数据库测试和更新，更新过程中会将 task 重命名为 oldtask，再创建新的 task 表，再将oldtask中的数据写入task

**Comment by Patrick-Ze** [comment]
> 还是不行……我一个个手动重新创建任务吧 orz 话说为什么上新版本后会有 task 和 taskold 两个表……

要是我早点看到这个issue就好了，我的也丢失了。早知道不升级了

**Comment by a76yyyy** [comment]
> > 还是不行……我一个个手动重新创建任务吧 orz 话说为什么上新版本后会有 task 和 taskold 两个表……
> 
> 要是我早点看到这个issue就好了，我的也丢失了。早知道不升级了

什么版本升到什么版本？

**Comment by Patrick-Ze** [comment]
> 什么版本升到什么版本？

升级前的版本记不清了，应该是202301开头，升级后版本是 20230718。不确定是否和我操作不当有关，以下是大概步骤（凭回忆，可能不太准）
1. 发现某个使用防屏蔽地址签到的任务失败
2. 下载har，替换防屏蔽地址为永久地址，然后重新上传，还是失败
3. 进入docker内部的shell，设置了环境变量HTTP_PROXY和HTTPS_PROXY然后测试curl
4. 尝试运行docker外的代码版，好像报redis的什么错（当时没有记录）
5. 尝试重新docker compose up（使用过代码版里的yml，也使用过wget下来的yml，但是记不清顺序。代码版应该是和升级前的是一个版本）
6. 不记得这里是否成功，中间好像还搜索了一下docker如何升级
以上4,5,6之间的顺序不甚可靠。最终就是新版本没有签到任务。前面提到的数据库表重命名的操作没试过（不了解数据库），我挂的签到任务就四五个，手动添加一下也还行，就手动添加了。

**Comment by a76yyyy** [comment]
> > 什么版本升到什么版本？
> 
> 升级前的版本记不清了，应该是202301开头，升级后版本是 20230718。不确定是否和我操作不当有关，以下是大概步骤（凭回忆，可能不太准）
> 
> 1. 发现某个使用防屏蔽地址签到的任务失败
> 2. 下载har，替换防屏蔽地址为永久地址，然后重新上传，还是失败
> 3. 进入docker内部的shell，设置了环境变量HTTP_PROXY和HTTPS_PROXY然后测试curl
> 4. 尝试运行docker外的代码版，好像报redis的什么错（当时没有记录）
> 5. 尝试重新docker compose up（使用过代码版里的yml，也使用过wget下来的yml，但是记不清顺序。代码版应该是和升级前的是一个版本）
> 6. 不记得这里是否成功，中间好像还搜索了一下docker如何升级
>    以上4,5,6之间的顺序不甚可靠。最终就是新版本没有签到任务。前面提到的数据库表重命名的操作没试过（不了解数据库），我挂的签到任务就四五个，手动添加一下也还行，就手动添加了。

大概看了一下，你是不是旧版本没有映射数据库所在文件夹的地址到容器外部

**Comment by Patrick-Ze** [comment]
> 大概看了一下，你是不是旧版本没有映射数据库所在文件夹的地址到容器外部

没有，不是很熟docker，应该没有进行过这个操作

**Comment by a76yyyy** [comment]
https://github.com/qd-today/qd/blob/21efe6f8c91cf8603fd406026e8afb1ea31a21bb/docker-compose.yml#L14

这一行表示将容器内的 config 文件夹映射到你 yml 所在目录下的 config 文件夹，也就是说使用 `docker compose` 方式后，你的数据库存在yml所在目录的config文件夹里，名字为 `database.db`，以后把这个保存好

**Comment by Patrick-Ze** [comment]
> 这一行表示将容器内的 config 文件夹映射到你 yml 所在目录下的 config 文件夹，也就是说使用 `docker compose` 方式后，你的数据库存在yml所在目录的config文件夹里，名字为 `database.db`，以后把这个保存好

好的，感谢解答~
