### ISSUE TITLE
[Feature] 有没有办法获取签到网站的dom标签元素值？

### ISSUE THREAD

**Issue by KyoShio** [qd-today/qd#380]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

分析了网站登录需要拿到dom上面的一个token值传入登录请求参数中，想知道这个有没有办法获取网页dom中的元素值加入请求中

### Describe the solution

分析了网站登录需要拿到dom上面的一个token值传入登录请求参数中，想知道这个有没有办法获取网页dom中的元素值加入请求中

**Comment by KyoShio** [comment]
![截屏2023-03-02 18 40 36](https://user-images.githubusercontent.com/20240090/222406128-6cb677c4-c6b0-412b-be90-d030d220b697.png)

**Comment by a76yyyy** [comment]
提供一下测试har，目测正则表达式提取即可

**Comment by KyoShio** [comment]
> 提供一下测试har，目测正则表达式提取即可

可以的，直接用正则提取
