### ISSUE TITLE
[Bug] docker进入容器更新后打不开签到界面

### ISSUE THREAD

**Issue by shinesky** [qd-today/qd#382]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20230228

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

进入qiandao容器后，执行更新命令
```
wget https://gitee.com/a76yyyy/qiandao/raw/master/update.sh -O /usr/src/app/update.sh && \
sh /usr/src/app/update.sh
```

### Describe the Bug

docker进入容器更新后打不开签到界面，报错：ModuleNotFoundError: No module named 'aiohttp'
和这个情况相同：https://github.com/qiandao-today/qiandao/issues/370
### QianDao config

更新前的签到版本：20220728

### QianDao log

```shell
ModuleNotFoundError: No module named 'aiohttp'
[W 230302 23:24:00 qiandao.RedisDB redisdb:28] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.
[W 230302 23:24:00 qiandao.RedisDB redisdb:28] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.
[W 230302 23:24:03 qiandao.Web.Util util:20] Import DdddOCR module falied: No module named 'ddddocr'
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 58, in <module>
    from web.app import Application
  File "/usr/src/app/web/app.py", line 17, in <module>
    from web.handlers import handlers, ui_modules, ui_methods
  File "/usr/src/app/web/handlers/__init__.py", line 26, in <module>
    module = __import__('%s.%s' % (__package__, module), fromlist = ["handlers"])
  File "/usr/src/app/web/handlers/util.py", line 24, in <module>
    import aiohttp
```

### Expected behavior

正常打开界面使用

**Comment by a76yyyy** [comment]
20220728的旧版本容器中无法通过`apk add`安装`py3-aiohttp`，导致缺少模块。

考虑兼容性，后续可能修复。

目前建议重新拉取最新容器以解决问题（一定要多备份几次数据库，防止数据库出问题）
