### ISSUE TITLE
[Bug] 调用GetCookie插件失败

### ISSUE THREAD

**Issue by WanKa-zone** [qd-today/qd#383]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20230228

### Bug on OS

Windows

### Bug on Platform

Code Build/Windows x64

### To Reproduce

点击 “[点击获取]”按钮

### Describe the Bug

对GetCookie插件失败， 多次刷新页面仍不能成功调用，无获取cookie弹窗， 重装GetCookie插件、更换浏览器、启用隐私模式或者重启docker问题均不能解决

### QianDao log

```shell
null
```

### Expected behavior

获取cookie 弹窗

**Comment by a76yyyy** [comment]
@ckx000

**Comment by ckx000** [comment]
报告一下浏览器平台 。同时 打开扩展程序里的 查看视图-【背景页】。看下扩展有没有具体的报错信息。
刚看了下我这边chrome107下还是正常的。。

**Comment by WanKa-zone** [comment]
> 

![image](https://user-images.githubusercontent.com/45703375/229194408-4ba5bf8c-b341-41fd-abd9-ed44d3778099.png)

**Comment by ckx000** [comment]
可能是弃用Manifest V2造成的不再支持Manifest V2老版本插件的原因。近期将会更新v3测试。如果急用可以暂时尝试chrome旧版107或以下。

**Comment by demostars** [comment]
一个不成熟的想法，发现一个有趣的项目 https://github.com/easychen/CookieCloud ，有没有可能结合 CookieCloud，自动同步cookie.😀

**Comment by FrancisNGG** [comment]
> 以暂时尝试chrome

今天 Chrome 更新完彻底不支持 `Manifest V2` 了，请大佬更新一下升级到 `Manifest V3` ，万分感激。

另外我自己尝试按 `Manifest V3` 标准修改了 `Manifest.json` ，修改内容如下 ：

```
{
   "manifest_version": 3,
   "name": "__MSG_appName__",
   "version": "0.0.7",
   "description": "__MSG_description__",
   "icons": {
      "16": "images/logo16.png",
      "32": "images/logo32.png",
      "48": "images/logo48.png",
      "128": "images/logo128.png"
   },
   "permissions": [
      "cookies",
      "activeTab"
   ],
   "host_permissions": [
      "<all_urls>"
   ],
   "background": {
      "service_worker": "background.js"
   },
   "content_scripts": [
      {
         "matches": [
            "<all_urls>"
         ],
         "js": [
            "js/cookie.js"
         ]
      }
   ],
   "default_locale": "en"
}
```

提示 `service_worker` 有错误：

`Error in event handler: TypeError: Error processing argument at index 0,`

可能是 `background.js` 里面使用的 API 有变更，但外行实在看不懂，还请大佬更新更新，谢谢了

**Comment by ckx000** [comment]
已更新至Manifest V3,请移步 [Releases](https://github.com/ckx000/get-cookies/releases)下载新版测试

**Comment by FrancisNGG** [comment]
> 已更新至Manifest V3,请移步 [Releases](https://github.com/ckx000/get-cookies/releases)下载新版测试

确认可用，感谢大佬付出

**Comment by WanKa-zone** [comment]
> 已更新至Manifest V3,请移步 [Releases](https://github.com/ckx000/get-cookies/releases)下载新版测试

感激大佬
![image](https://github.com/qd-today/qd/assets/45703375/e0ac05d4-b64a-463e-9145-98aca08ed833)

**Comment by guojindai** [comment]
> 一个不成熟的想法，发现一个有趣的项目 https://github.com/easychen/CookieCloud ，有没有可能结合 CookieCloud，自动同步cookie.😀

这想法真不错
