### ISSUE TITLE
[Bug] 用页面备份的数据库，恢复时显示无法导入，用命令行也不行

### ISSUE THREAD

**Issue by wcy233** [qd-today/qd#384]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20230111

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 32位

### To Reproduce

用页面备份的数据库，恢复时显示无法导入，用命令行也不行

### Describe the Bug

用页面备份的数据库，恢复时显示无法导入，用命令行也不行

### QianDao log

```shell
用页面备份的数据库，恢复时显示无法导入，用命令行也不行
```

### Expected behavior

用页面备份的数据库，恢复时显示无法导入，用命令行也不行

**Comment by a76yyyy** [comment]
参考文档 https://qiandao-today.github.io/qiandao/zh_CN/guide/faq.html

**Comment by a76yyyy** [comment]
Bug 已修复, 如有问题请 reopen 这个 Issue
