### ISSUE TITLE
[Feature] 为什么重启之后显示密码错误或账号不存在啊

### ISSUE THREAD

**Issue by Clavicler** [qd-today/qd#386]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

1

### Describe the solution

1

**Comment by a76yyyy** [comment]
重启容器么, 你的数据库文件有做映射么?

**Comment by a76yyyy** [comment]
如果有反馈请reopen这个issue
