### ISSUE TITLE
[Feature] 注册TgBot作为推送渠道的操作指南

### ISSUE THREAD

**Issue by Patrick-Ze** [qd-today/qd#387]
### Verify steps

- [x] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

目前签到框架网页对注册TgBot作为推送方式的指引中，相关字段含义可能不是很清晰
![image](https://user-images.githubusercontent.com/19711799/224078973-e9c78339-6b15-41f2-b93b-2c9dd8186808.png)

## qiandao注册TgBot的字段说明

假设你已经创建了一个具有自定义域名的telegram bot API （如何创建这样一个域名&各个字段的含义可以搜索教程和telegram文档，此处略去不表）:

`https://tg.mydomain.com/bot1111111111:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/sendMessage?chat_id=222222222&text=HelloWorld`

上面这个请求将会向`222222222`这个聊天发送一条`HelloWorld`消息。那么在注册TgBot的页面时：
- `TG_TOKEN`应当填写bot的ID以及对应的key的组合，但是不包括`bot`，即申请TgBot时BotFather提供的token：`1111111111:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA` 
- `TG_USERID`应当填写telegram API中的`chat_id`字段，即 `222222222`
- `TG_HOST`基本不会有歧义，这里填`tg.mydomain.com`，也可以带上`http://`或者`https://`前缀

因此最终填写形式形如：

`1111111111:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;222222222;tg.mydomain.com`

（我看代码之前以为的`TG_USERID`是TgBot的ID，`TG_TOKEN`是`AAAA……`这段key）

### Describe the solution

见上文。

### Describe alternatives

我是查看了项目的源代码之后才知道如何填写的，我也愿意参与repo文档的更新，本来是想向github.io的文档提PR，但是好像github page是不公开编辑的，因此开了一个issue供有类似需要的同学参考步骤（或者大佬是否考虑把这个添加到FAQ里？）

**Comment by a76yyyy** [comment]
英文文档编辑 FAQ: https://github.com/qiandao-today/qiandao/blob/master/web/docs/guide/faq.md
中文 FAQ: https://github.com/qiandao-today/qiandao/blob/master/web/docs/zh_CN/guide/faq.md
