### ISSUE TITLE
[Feature] 时间戳API加入更多转换功能

### ISSUE THREAD

**Issue by github-h** [qd-today/qd#388]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

当前时间戳只能接受ts参数并转换成其他格式，希望加入更多接受参数实现更多转换

### Describe the solution

![图片](https://user-images.githubusercontent.com/49114731/224475639-a2ad7d01-1849-422a-9099-5b1df5bc4f85.png)

希望接受常见的比如 GMT 或者ISO 格式的时间格式

然后像ts参数一样可以转换成其他一堆的时间格式供提取

**Comment by github-h** [comment]
当前时间戳转换只支持秒级别的转换 比如 
![图片](https://github.com/qd-today/qd/assets/49114731/8976fb7e-6c74-4dd3-bcde-627025453822)

希望支持对毫秒级别的转换

对于秒时间戳使用 ts  对于毫秒时间戳使用tms

**Comment by a76yyyy** [comment]
请更新到最新dev版后尝试该功能, 如果有问题请及时反馈

**Comment by a76yyyy** [comment]
如有问题, 请 reopen 这个 Issue

**Comment by github-h** [comment]
还是有点问题哦
当参数为  
`form=%Y-%m-%dT%H:%M:%S.%fZ&dt=2023-06-20T02:58:23.181051Z`
结果为
{
    "完整时间戳": 1687201103.181051,
    "时间戳": 1687201103,
    "16位时间戳": 1687201103181051,
    "周": "2/25",
    "日": "171/365",
    "北京时间": "2023-06-20T02:58:23.000000Z",
    "GMT格式": "Mon, 19 Jun 2023 18:58:23 GMT",
    "ISO格式": "2023-06-19T18:58:23Z",
    "状态": "200"
}

并没有达到ISO格式转正常显示的北京时间的效果

如果想达到理想效果 还得再加一次api
`ts=1687201103.181051`

**Comment by a76yyyy** [comment]
> 还是有点问题哦 当参数为 `form=%Y-%m-%dT%H:%M:%S.%fZ&dt=2023-06-20T02:58:23.181051Z` 结果为 { "完整时间戳": 1687201103.181051, "时间戳": 1687201103, "16位时间戳": 1687201103181051, "周": "2/25", "日": "171/365", "北京时间": "2023-06-20T02:58:23.000000Z", "GMT格式": "Mon, 19 Jun 2023 18:58:23 GMT", "ISO格式": "2023-06-19T18:58:23Z", "状态": "200" }
> 
> 并没有达到ISO格式转正常显示的北京时间的效果
> 
> 如果想达到理想效果 还得再加一次api `ts=1687201103.181051`

默认以北京时间为准转换，因为容器里TZ环境变量为北京时区

**Comment by github-h** [comment]
> > 还是有点问题哦 当参数为 `form=%Y-%m-%dT%H:%M:%S.%fZ&dt=2023-06-20T02:58:23.181051Z` 结果为 { "完整时间戳": 1687201103.181051, "时间戳": 1687201103, "16位时间戳": 1687201103181051, "周": "2/25", "日": "171/365", "北京时间": "2023-06-20T02:58:23.000000Z", "GMT格式": "Mon, 19 Jun 2023 18:58:23 GMT", "ISO格式": "2023-06-19T18:58:23Z", "状态": "200" }
> > 并没有达到ISO格式转正常显示的北京时间的效果
> > 如果想达到理想效果 还得再加一次api `ts=1687201103.181051`
> 
> 默认以北京时间为准转换，因为容器里TZ环境变量为北京时区

是的是的 但是 你看ISO转换完的北京时间显示是有问题的
"北京时间": "2023-06-20T02:58:23.000000Z",

**Comment by a76yyyy** [comment]
> > > 还是有点问题哦 当参数为 `form=%Y-%m-%dT%H:%M:%S.%fZ&dt=2023-06-20T02:58:23.181051Z` 结果为 { "完整时间戳": 1687201103.181051, "时间戳": 1687201103, "16位时间戳": 1687201103181051, "周": "2/25", "日": "171/365", "北京时间": "2023-06-20T02:58:23.000000Z", "GMT格式": "Mon, 19 Jun 2023 18:58:23 GMT", "ISO格式": "2023-06-19T18:58:23Z", "状态": "200" }
> > > 并没有达到ISO格式转正常显示的北京时间的效果
> > > 如果想达到理想效果 还得再加一次api `ts=1687201103.181051`
> > 
> > 
> > 默认以北京时间为准转换，因为容器里TZ环境变量为北京时区
> 
> 是的是的 但是 你看ISO转换完的北京时间显示是有问题的 "北京时间": "2023-06-20T02:58:23.000000Z",

已修复

**Comment by github-h** [comment]
> > > > 还是有点问题哦 当参数为 `form=%Y-%m-%dT%H:%M:%S.%fZ&dt=2023-06-20T02:58:23.181051Z` 结果为 { "完整时间戳": 1687201103.181051, "时间戳": 1687201103, "16位时间戳": 1687201103181051, "周": "2/25", "日": "171/365", "北京时间": "2023-06-20T02:58:23.000000Z", "GMT格式": "Mon, 19 Jun 2023 18:58:23 GMT", "ISO格式": "2023-06-19T18:58:23Z", "状态": "200" }
> > > > 并没有达到ISO格式转正常显示的北京时间的效果
> > > > 如果想达到理想效果 还得再加一次api `ts=1687201103.181051`
> > > 
> > > 
> > > 默认以北京时间为准转换，因为容器里TZ环境变量为北京时区
> > 
> > 
> > 是的是的 但是 你看ISO转换完的北京时间显示是有问题的 "北京时间": "2023-06-20T02:58:23.000000Z",
> 
> 已修复

还是没有修复 ISO时间转换北京时间的问题

还是建议改为参数格式  自定义格式可以保留
新增 iso=   gmt=  这种的是不是好一些
```
api://util/timestamp?form=%Y-%m-%dT%H:%M:%SZ&dt=2021-06-30T16:00:00Z

{
    "完整时间戳": 1625040000.0,
    "时间戳": 1625040000,
    "16位时间戳": 1625040000000000,
    "周": "3/26",
    "日": "181/365",
    "北京时间": "2021-06-30T16:00:00Z",
    "GMT格式": "Wed, 30 Jun 2021 08:00:00 GMT",
    "ISO格式": "2021-06-30T08:00:00Z",
    "状态": "200"
}
```

这种显示还是有问题的


然后有些时间可能是这种格式  2023-06-24T01:09:09.3605191Z
自定义格式匹配还是有点问题
![图片](https://github.com/qd-today/qd/assets/49114731/232f235f-f3a4-4f3f-bf42-23f558548ee0)
