### ISSUE TITLE
希望支持滑块验证码识别

### ISSUE THREAD

**Issue by OwnerCM** [qd-today/qd#390]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

ddddocr最新版本已支持滑块验证码识别，但需要传入背景图片、滑块图片2个参数，qiandao框架的ocr识别api仅支持传入一个图片参数，希望能增加滑块验证码支持。

### Describe the solution

ddddocr最新版本已支持滑块验证码识别，但需要传入背景图片、滑块图片2个参数，qiandao框架的ocr识别api仅支持传入一个图片参数，希望能增加滑块验证码支持。

**Comment by a76yyyy** [comment]
Feat #397
