### ISSUE TITLE
[Feature] 希望web保存登录状态的时间能自定义

### ISSUE THREAD

**Issue by ICEY1W32** [qd-today/qd#393]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

自部署了框架, 隔几天就需要重新登录, 非常不方便

### Describe the solution

希望web保存登录状态的时间能自定义, 起码能设置的更长一点就好了

**Comment by a76yyyy** [comment]
环境变量中设置 `COOKIE_DAY` 或修改配置文件即可解决你的问题

设置完成并重启容器后, 记的在浏览器端重新登陆

如果还有问题, 请 reopen 这个 Issue
