### ISSUE TITLE
[Feature] telegram 消息内容增加 hashtag 以便于搜索

### ISSUE THREAD

**Issue by wen-long** [qd-today/qd#401]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

没有 hashtag 时，telegram 通知按时间排列，难以肉眼跟踪特定站点的消息

### Describe the solution

在 https://github.com/qiandao-today/qiandao/blob/master/libs/funcs.py#L153 处进行修改，将站点的二级域名部份作为 hashtag
例如 签到任务 `#btschool` - 成功
此时 #btschool 高亮为蓝色，且点击后进入按 #btschool 关键词搜索后的消息页面

要注意，hashtag 部分必须作为单独的实体，通过修改现在的 content 是不会让 TG 客户端高亮显示 hashtag 并进行索引的
可以参考 https://core.telegram.org/bots/update56kabdkb12ibuisabdubodbasbdaosd

### Additional context

希望的效果如图
![](https://i.imgur.com/FJ0bGTX.png)

点击后如图
![](https://i.imgur.com/efUIzer.png)

**Comment by a76yyyy** [comment]
请更新至 dev 版尝试, 如无问题请 close 这个 issue

**Comment by wen-long** [comment]
> 请更新至 dev 版尝试, 如无问题请 close 这个 issue

试了不行，不过代码也不太对
`<b>` 里面再有 # 是无效的，正文 Describe the solution 有提到

**Comment by a76yyyy** [comment]
> > 请更新至 dev 版尝试, 如无问题请 close 这个 issue
> 
> 试了不行，不过代码也不太对 `<b>` 里面再有 # 是无效的，正文 Describe the solution 有提到

我这边是没有问题的
![Screenshot_2023-06-12-15-33-11-242_org telegram messenger web](https://github.com/qd-today/qd/assets/56478790/1c061700-c415-4d9c-b43c-96fef64f6b5f)

![IMG_20230612_153528](https://github.com/qd-today/qd/assets/56478790/c04b9603-5297-4fa4-a2aa-417e9de9a255)

你那边显示什么

**Comment by wen-long** [comment]
不好意思我 docker-compose pull 下来用 docker-compose start 启动的还是旧镜像；docker-compose up 起新镜像现在可以了。
thanks for your work
