### ISSUE TITLE
[Bug]流意外关闭，无法获取公开模板数据

### ISSUE THREAD

**Issue by XZ1314XZ** [qd-today/qd#405]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20230228

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

打开公开模板页面：http://xxxxx/tpls/public

### Describe the Bug

问题：
Python Tornado Web 服务器的请求处理错误。在处理 GET 请求时，执行 `await self.render('push_list.html', pushs=pushs, pulls=pulls)` 代码语句，出现了 StreamClosedError 错误。

日志如图：
![Snipaste_2023-04-12_15-33-57](https://i2.100024.xyz/2023/04/12/pdiq9h.webp)

### QianDao config

```shell
正常搭建后第一次打开就遇到的错误，对原配置无任何修改
```

### QianDao log

```shell
qiandao  | [I 230412 15:07:33 tornado.access web:2271] 200 GET /user/2/setnewpwd (172.18.0.1) 11.65ms
qiandao  | [I 230412 15:07:35 tornado.access web:2271] 200 GET /pushs (172.18.0.1) 25.96ms
qiandao  | [E 230412 15:07:35 tornado.application web:1798] Uncaught exception GET /pushs (172.18.0.1)
qiandao  |     HTTPServerRequest(protocol='http', host='192.168.1.3:8923', method='GET', uri='/pushs', version='HTTP/1.1', remote_ip='172.18.0.1')
qiandao  |     Traceback (most recent call last):
qiandao  |       File "/usr/lib/python3.11/site-packages/tornado/web.py", line 1713, in _execute
qiandao  |         result = await result
qiandao  |                  ^^^^^^^^^^^^
qiandao  |       File "/usr/src/app/web/handlers/push.py", line 72, in get
qiandao  |         await self.render('push_list.html', pushs=pushs, pulls=pulls)
qiandao  |     tornado.iostream.StreamClosedError: Stream is closed
qiandao  | [I 230412 15:27:09 tornado.access web:2271] 200 GET /pushs (172.18.0.1) 25.99ms
qiandao  | [I 230412 15:27:11 tornado.access web:2271] 302 GET / (172.18.0.1) 0.83ms
qiandao  | [I 230412 15:27:11 tornado.access web:2271] 200 GET /my/ (172.18.0.1) 21.74ms
```

### Expected behavior

![Snipaste_2023-04-12_15-38-45](https://i2.100024.xyz/2023/04/12/pg00nv.webp)

### Screenshots

![Snipaste_2023-04-12_15-38-45](https://i2.100024.xyz/2023/04/12/pg00nv.webp)

**Comment by a76yyyy** [comment]
尝试更新至最新源码确认是否还有该问题

**Comment by a76yyyy** [comment]
如果还有问题请Reopen这个issue
