### ISSUE TITLE
[Feature] 希望大佬能加入节假日签到计划功能

### ISSUE THREAD

**Issue by wu0lei** [qd-today/qd#408]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

或者支持手动配置节假日，让部分签到不在节假日工作

### Describe the solution

这个功能你懂的

**Comment by a76yyyy** [comment]
做到一半发现有的网站节假日禁止签到天数并不会完全按照国家法定节假日走, 觉得没什么意义, 就不做了

**Comment by a76yyyy** [comment]
给框架加了个关于节假日的小彩蛋, 详见PR #411
