### ISSUE TITLE
公开模板中提交参数会出现乱码

### ISSUE THREAD

**Issue by Xm798** [qd-today/qd#41]
参数在模板编辑过程中正常，发布到公开模板中再查看，便会出现乱码的情况。例如：
编辑界面：`province=%E6%B1%9F%E8%8B%8F%E7%9C%81&city=%E5%8D%97%E4%BA%AC%E5%B8%82&`
公开模板：`åäº¬å¸ æ±èç。`

![image](https://user-images.githubusercontent.com/48074861/103422023-625abe80-4bda-11eb-94ca-798b9b5b3948.png)

**Comment by Xm798** [comment]
顺祝，新年快乐！

**Comment by asdaragon** [comment]
@Xm798  把har发一下我试试

**Comment by Xm798** [comment]
[从公开模板下载的json格式的Har文件](https://cowtransfer.com/s/722b03a5dc654e)
公开模板中显示的乱码情况如下图
![IMG_20210103_175019.jpg](https://user-images.githubusercontent.com/48074861/103475889-d16d1a00-4d76-11eb-8db1-d31a9f159aef.jpg)

**Comment by asdaragon** [comment]
@Xm798 文件格式json，改成har就行了

**Comment by Xm798** [comment]
> @Xm798 文件格式json，改成har就行了

请问在哪边更改文件格式呢？我当时创建的时候是上传HAR创建的，从公开模板页面点击下载就变成了json格式。
@AragonSnow

**Comment by asdaragon** [comment]
应该是显示问题，无视就好。
