### ISSUE TITLE
[Bug] GB2312编码 有问题，遇到字符 & 会截断

### ISSUE THREAD

**Issue by loveqianool** [qd-today/qd#414]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20230302

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

GB2312编码转换 !!! 结果 = %21%21%21
若是转换 !&!! 结果 = %21

### Describe the Bug

转换结果不准确

### QianDao log

```shell
没有报错
```

### Expected behavior

准确转换

**Comment by a76yyyy** [comment]
推荐使用post方式进行api操作

**Comment by a76yyyy** [comment]
GET方式下请对参数进行 `urlencode` 操作, 建议使用post方式的json方法

如果还有问题, 请 reopen 这个 Issue
