### ISSUE TITLE
新版0518打不开公共模板

### ISSUE THREAD

**Issue by 404gods** [qd-today/qd#420]
新版0518打不开公共模板，强制更新和重建缓存都不行。
报错信息：失败原因: 'NoneType' object has no attribute 'get'
Note: 请刷新页面并修改配置后, 通过强制更新或重建缓存重试!

**Comment by thomasdba** [comment]
+1

**Comment by ddd-zero** [comment]
> 新版0518打不开公共模板，强制更新和重建缓存都不行。 报错信息：失败原因: 'NoneType' object has no attribute 'get' Note: 请刷新页面并修改配置后, 通过强制更新或重建缓存重试!


> +1

[#国内公共模板无法更新的，请自定义加速源](https://github.com/qd-today/qd/discussions/417)

**Comment by a76yyyy** [comment]
请重新拉取latest容器, 并更新至最新源码
