### ISSUE TITLE
[Bug] 使用域名更新公共模板失败

### ISSUE THREAD

**Issue by lancer-wang** [qd-today/qd#423]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20230601

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

使用nginx反代端口
用域名访问，模板页面提示更新失败

### Describe the Bug

![image](https://github.com/qd-today/qd/assets/69783837/87d3f955-4289-4f13-a4cf-bec9081ddfe2)

### QD config

```shell
均为默认，环境为ubuntu20 ，装的docker
```

### QD log

```shell
[I 230605 09:32:05 QD.Run run:87] Http Server started on 0.0.0.0:80
[I 230605 09:32:09 tornado.access web:2344] 304 GET /subscribe/1/ (172.17.0.1) 59.56ms
[W 230605 09:32:10 tornado.access web:2344] 400 GET /subscribe/1/updating/ (172.17.0.1) 1.27ms
```

### Expected behavior

使用域名也可以更新

**Comment by lancer-wang** [comment]
![image](https://github.com/qd-today/qd/assets/69783837/23dd804a-0c15-4106-a42e-651fa9ce1b7d)

**Comment by lancer-wang** [comment]
使用ip:port访问可以正常更新

**Comment by a76yyyy** [comment]
参考 [Release 说明](https://github.com/qd-today/qd/releases/tag/20230601) 和 [说明文档](https://qd-today.github.io/qd/zh_CN/guide/faq.html#%E5%85%AC%E5%85%B1%E6%A8%A1%E6%9D%BF%E6%9B%B4%E6%96%B0%E9%A1%B5%E9%9D%A2%E6%8F%90%E7%A4%BA%E9%94%99%E8%AF%AF%E4%BB%A3%E7%A0%81%E4%B8%BA-undefined), 请修改 nginx 反代配置

**Comment by lancer-wang** [comment]
> 参考 [Release 说明](https://github.com/qd-today/qd/releases/tag/20230601) 和 [说明文档](https://qd-today.github.io/qd/zh_CN/guide/faq.html#%E5%85%AC%E5%85%B1%E6%A8%A1%E6%9D%BF%E6%9B%B4%E6%96%B0%E9%A1%B5%E9%9D%A2%E6%8F%90%E7%A4%BA%E9%94%99%E8%AF%AF%E4%BB%A3%E7%A0%81%E4%B8%BA-undefined), 请修改 nginx 反代配置

![image](https://github.com/qd-today/qd/assets/69783837/b6d59dd5-5967-4c2b-a1da-220701908d38)
这一段我是有的啊

**Comment by a76yyyy** [comment]
请在 `location / {}`中配置

**Comment by lancer-wang** [comment]
> 请在 `location / {}`中配置

![image](https://github.com/qd-today/qd/assets/69783837/1660ffd0-5112-40c2-9773-775e78c15b7e)
还是不行

**Comment by lancer-wang** [comment]
可以了，原来是多了几个重复值

**Comment by lancer-wang** [comment]
![image](https://github.com/qd-today/qd/assets/69783837/28b2efca-a6d5-4a84-a500-5fdd96a51a2e)

```nginx
    location / {
        proxy_set_header  Host $host;
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto  $scheme;
        proxy_pass http://127.0.0.1:8923;
        
        # WebSocket 关键配置 start
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        # 关键配置 end
    }
```
给后面用的人一个参考吧

**Comment by ddd-zero** [comment]
啊？是加了websocket了吗？可我CDN没有websocket啊。。。有些家的CDN为了防止websocket被拿去翻墙做代理，就把这个功能关了。。。

**Comment by a76yyyy** [comment]
直接IP地址访问不可以用么

> 啊？是加了websocket了吗？可我CDN没有websocket啊。。。有些家的CDN为了防止websocket被拿去翻墙做代理，就把这个功能关了。。。

**Comment by ddd-zero** [comment]
> 直接IP地址访问不可以用么
> 
> > 啊？是加了websocket了吗？可我CDN没有websocket啊。。。有些家的CDN为了防止websocket被拿去翻墙做代理，就把这个功能关了。。。

我也搞不明白，这个机子用IP访问，登录不上去，群里我也发过视频。登陆后不跳转，闪了一下还在这个登陆页面

**Comment by KoWming** [comment]
> 请在 中配置`location / {}`

大佬，我使用群辉Docker部署QD后使用的是群辉的Web Station来配置域名进行访问，无法编辑Nginx WebSocket 关键配置，大佬有其他方法吗？

**Comment by KoWming** [comment]
> > 请在 中配置`location / {}`
> 
> 大佬，我使用群辉Docker部署QD后使用的是群辉的Web Station来配置域名进行访问，无法编辑Nginx WebSocket 关键配置，大佬有其他方法吗？

![1](https://github.com/qd-today/qd/assets/96684377/8c28fa7d-0fe7-4498-8184-2ace17b0c8fa)
放弃使用群辉Web Station来配置域名进行访问，使用群辉自带的反向代理服务器 添加WebSocket 解决了公共模板更新问题。

**Comment by a76yyyy** [comment]
> > > 请在 `location / {}` 中配置
> > 
> > 大佬，我使用群辉Docker部署QD后使用的是群辉的Web Station来配置域名进行访问，无法编辑Nginx WebSocket 关键配置，大佬有其他方法吗？
> 
> 放弃使用群辉Web Station来配置域名进行访问，使用群辉自带的反向代理服务器 添加WebSocket 解决了公共模板更新问题。

我没有群晖, 不能给你更好的建议了

**Comment by KoWming** [comment]
> > > > 请在 `location / {}` 中配置
> > > 
> > > 
> > > 大佬，我使用群辉Docker部署QD后使用的是群辉的Web Station来配置域名进行访问，无法编辑Nginx WebSocket 关键配置，大佬有其他方法吗？
> > 
> > 
> > 放弃使用群辉Web Station来配置域名进行访问，使用群辉自带的反向代理服务器 添加WebSocket 解决了公共模板更新问题。
> 
> 我没有群晖, 不能给你更好的建议了

感谢你的回复，我已经用上面的方法解决了这个问题。再次感谢你一直维护的这个项目。

**Comment by caelumlux** [comment]
> 

可能需要加上 proxy_set_header Origin '';

**Comment by liaojack8** [comment]
> > > 请在 中配置`location / {}`
> > 
> > 
> > 大佬，我使用群辉Docker部署QD后使用的是群辉的Web Station来配置域名进行访问，无法编辑Nginx WebSocket 关键配置，大佬有其他方法吗？
> 
> ![1](https://private-user-images.githubusercontent.com/96684377/245481459-8c28fa7d-0fe7-4498-8184-2ace17b0c8fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzE1NDUsIm5iZiI6MTcwNDM3MTI0NSwicGF0aCI6Ii85NjY4NDM3Ny8yNDU0ODE0NTktOGMyOGZhN2QtMGZlNy00NDk4LTgxODQtMmFjZTE3YjBjOGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDEyMjcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyODcxMTM4MWMxYmUxYjQ1OWRjMDZmMTRkMWVjNzA2YjA4OTY2MDZiMDRkYzVmMDc3YjQzOTZkZDE1YzViMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zO21CQ7Kj5MP31Kq2H0sdv6EXcoELGBVJs8sGSNqpBA) 放弃使用群辉Web Station来配置域名进行访问，使用群辉自带的反向代理服务器 添加WebSocket 解决了公共模板更新问题。

設定了反向代理, 忽略了WebSocket的設定值, 今天找到這裡, 終於解決了

**Comment by UnicornUnderMoon** [comment]
也遇到类似问题，反代服务器是apache2，版本Apache/2.4.58 ，系统ubuntu 24.02。
经下方2.4.47以上版本方法测试，故障去除
### Apache HTTP Server >= 2.4.47
`ProxyPass / http://localhost:8888/ upgrade=websocket`
### Apache HTTP Server < 2.4.47
```
ProxyPass / http://localhost:8888/
RewriteEngine   on
RewriteCond     %{HTTP:Upgrade}       websocket                   [NC]
RewriteCond     %{HTTP:Connection}    upgrade                     [NC]
RewriteRule     ^/?(.*)               "ws://localhost:8888/$1"    [P,L]
```
