### ISSUE TITLE
docker邮箱配置失效

### ISSUE THREAD

**Issue by MrLiuGangQiang** [qd-today/qd#424]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20230601

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

![微信截图_20230605143618](https://github.com/qd-today/qd/assets/7357127/7adc4510-a205-43f0-b4ab-4ca39635c032)

### Describe the Bug

![image](https://github.com/qd-today/qd/assets/7357127/1c7cf666-5350-40fd-8e85-79565c49ef86)

### QD log

```shell
2023-06-05T06:28:10.053853327Z [I 230605 14:28:10 tornado.access web:2344] 200 POST /password_reset (222.210.139.25) 9.98ms
2023-06-05T06:28:10.053938102Z [I 230605 14:28:10 QD.Web.Handler login:252] password reset: userid=1 email=mrliugangqiang@vip.qq.com
2023-06-05T06:28:10.067027272Z [I 230605 14:28:10 QD.Http.Util utils:390] send mail to mrliugangqiang@vip.qq.com
2023-06-05T06:28:10.175999626Z [E 230605 14:28:10 QD.Http.Util utils:409] send mail error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1002)
2023-06-05T06:28:40.821298357Z [I 230605 14:28:40 tornado.access web:2344] 302 POST /login (222.210.139.25) 110.19ms
2023-06-05T06:28:41.019646331Z [I 230605 14:28:41 tornado.access web:2344] 200 GET /my/ (222.210.139.25) 168.26ms
2023-06-05T06:28:45.627749660Z [I 230605 14:28:45 tornado.access web:2344] 304 GET /util/toolbox/1 (222.210.139.25) 7.66ms
2023-06-05T06:28:49.033169037Z [I 230605 14:28:49 tornado.access web:2344] 200 POST /util/urldecode (127.0.0.1) 0.83ms
2023-06-05T06:28:49.050955904Z [I 230605 14:28:49 tornado.access web:2344] 200 POST /task/17/run (222.210.139.25) 434.02ms
2023-06-05T06:28:49.060977730Z [I 230605 14:28:49 QD.Http.Util utils:390] send mail to mrliugangqiang@vip.qq.com
2023-06-05T06:28:49.166581933Z [E 230605 14:28:49 QD.Http.Util utils:409] send mail error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1002)
```

### Expected behavior

应该正常发出邮箱才对

**Comment by a76yyyy** [comment]
请检查你的邮箱配置中端口信息是否配置正确, 0601版本要求端口必须配置正确才可以;

如果还是有问题, 请发一下你的邮箱配置, 注意隐去隐私信息

**Comment by MrLiuGangQiang** [comment]
> 请检查你的邮箱配置中端口信息是否配置正确, 0601版本要求端口必须配置正确才可以;
> 
> 如果还是有问题, 请发一下你的邮箱配置, 注意隐去隐私信息

邮箱配置肯定是没有问题的 其他地方都在用这个

**Comment by MrLiuGangQiang** [comment]
> 正确

我是用的QQ邮箱
SMTP:smtp.qq.com
PORT:587
账号密码可以肯定是没错的

**Comment by a76yyyy** [comment]
> > 正确
> 
> 我是用的QQ邮箱 SMTP:smtp.qq.com PORT:587 账号密码可以肯定是没错的

端口号改成 465 试试

**Comment by hzfla** [comment]
端口改成25试试看，我用25端口可以正常使用，qq邮箱

**Comment by a76yyyy** [comment]
> > ```shell
> > SSL: WRONG_VERSION_NUMBER
> > ```
> 
> 参考 [QQ邮箱 报错 SSL: WRONG_VERSION_NUMBER](https://blog.csdn.net/sicsdnid/article/details/127732580) 和 [知乎](https://zhuanlan.zhihu.com/p/569155035)
请修改邮箱端口 (QQ邮箱 一般开启SSL用465, 否则用25), 如果还有问题请 reopen 这个 Issue

**Comment by a76yyyy** [comment]
> > ```shell
> > SSL: WRONG_VERSION_NUMBER
> > ```
> 
> 参考 [QQ邮箱 报错 SSL: WRONG_VERSION_NUMBER](https://blog.csdn.net/sicsdnid/article/details/127732580) 和 [知乎](https://zhuanlan.zhihu.com/p/569155035)
请修改邮箱端口 (QQ邮箱 一般开启SSL用465, 否则用25), 如果还有问题请 reopen 这个 Issue

**Comment by liaojack8** [comment]
若`stmp port number`為`587`時
需要先執行`s.starttls()`
後續login才不會出錯
https://github.com/qd-today/qd/blob/68aa0b7bde49bebf10bbd640b88cfd8ecad7e016/libs/utils.py#L456

建議一下, 改為這樣應該就不會出錯, 實際QQ郵箱還需實測, 我用gmail沒問題
```
if config.mail_ssl or config.mail_port in [465, 587]:
                s = smtplib.SMTP_SSL(config.mail_smtp, config.mail_port)
                              if config.mail_port in 587: #use starttls
                                              s.starttls()
```

**Comment by liaojack8** [comment]
@a76yyyy 抱歉, 昨天發issue時miss掉了我這邊修改過的另外一個命令
starttls的連線方法順序為
```
s = smtplib.SMTP()
s.connect()
s.starttls()
s.login()
s.sendmail()
s.quit()
```
依照ˋ[0859366](https://github.com/qd-today/qd/commit/0859366acca4f773c2e6c927b5cfb2c6f842cc7c)
`s.connect()`與`s.starttls()`方法順序顛倒不會直接報錯, 而是引發`s.login()`報錯
L463不會caught到err
https://github.com/qd-today/qd/blob/0859366acca4f773c2e6c927b5cfb2c6f842cc7c/libs/utils.py#L463
err msg 顯示send mail errror
![2024-02-11_04h12_56](https://github.com/qd-today/qd/assets/23449425/db60cad2-9e1a-4071-bc88-cc175c36e697)

把465與587分成2個case處理應該還是比較好的, 這樣做就沒問題了
已經再三測試, 可以正常工作, 再次抱歉

```
async def _send_mail(to, subject, text=None, subtype='html'):
    if not config.mail_smtp:
        logger_util.info('no smtp')
        return
    msg = MIMEText(text, _subtype=subtype, _charset='utf-8')
    msg['Subject'] = subject
    msg['From'] = config.mail_from
    msg['To'] = to
    try:
        logger_util.info('send mail to %s', to)
        if config.mail_port:
            if config.mail_port == 465:
                s = smtplib.SMTP_SSL(config.mail_smtp, config.mail_port)
                s.connect(config.mail_smtp, config.mail_port)
            elif config.mail_port == 587: # use starttls
                s = smtplib.SMTP(config.mail_smtp, config.mail_port)
                s.connect(config.mail_smtp, config.mail_port)
                try:
                    s.starttls()
                except smtplib.SMTPException as e:
                    logger_util.error("smtp starttls failed: %s", e, exc_info=config.traceback_print)
        else:
            if config.mail_ssl:
                s = smtplib.SMTP_SSL(config.mail_smtp)
            else:
                s = smtplib.SMTP(config.mail_smtp)
            s.connect(config.mail_smtp)
        # s = config.mail_ssl and smtplib.SMTP_SSL(config.mail_smtp) or smtplib.SMTP(config.mail_smtp)
        if config.mail_user:
            s.login(config.mail_user, config.mail_password)
        s.sendmail(config.mail_from, to, msg.as_string())
        s.close()
    except Exception as e:
        logger_util.error('send mail error: %s', e, exc_info=config.traceback_print)
    return
```

**Comment by liaojack8** [comment]
另外我寫了一個測試starttls連線寄信的小程式
使用starttls連線的朋友可以先測試看看, 能成功寄送的話
這次bug修復掉, 發版過後, 郵箱配置應該就沒問題了

@a76yyyy 也許可以考慮一下要不要把starttls另外加到config選項中
好像有遇過少數部分郵箱服務使用starttls協議但default port不是587的
未來應該也會漸漸全面改用starttls, 這部分outlook領先
可以看到[微軟幫助](https://support.microsoft.com/zh-cn/office/outlook-com-%E7%9A%84-pop-imap-%E5%92%8C-smtp-%E8%AE%BE%E7%BD%AE-d088b986-291d-42b8-9564-9c414e2aa040)已經全面拿掉SSL, 只剩下TLS與STARTTLS

```
import smtplib
from email.mime.text import MIMEText

def send_email_starttls(smtp_server, smtp_server_port, sender, password, receiver, message):
    server = smtplib.SMTP(smtp_server,smtp_server_port)
    server.connect(smtp_server, smtp_server_port)
    smtp_ttls = server.starttls()
    print(f'start tls ==> {smtp_ttls}')

    server.login(sender, password)
    message['From'] = sender
    status = server.sendmail(sender, receiver, message.as_string())
    if not status:
        print('寄信成功')
    else:
        print(f'寄信失敗。{status}')
      
    server.quit()

if __name__ == '__main__':
    smtp_server = 'smtp-mail.outlook.com'
    smtp_server_port = 587
    sender_address = 'xxxxxxxx@outlook.com'
    sender_password = 'xxxxxxxx'
    to_mail = 'Your emil address'

    message = MIMEText(_text = 'Are all settings correct?\r\nSent via mail.py')
    message['Subject'] = 'Test Message'
    message['To'] = to_mail
    send_email_starttls(smtp_server, smtp_server_port, sender_address, sender_password, to_mail, message)
```

**Comment by a76yyyy** [comment]
> 另外我寫了一個測試starttls連線寄信的小程式
> 使用starttls連線的朋友可以先測試看看, 能成功寄送的話
> 這次bug修復掉, 發版過後, 郵箱配置應該就沒問題了
> 
> @a76yyyy 也許可以考慮一下要不要把starttls另外加到config選項中
> 好像有遇過少數部分郵箱服務使用starttls協議但default port不是587的
> 未來應該也會漸漸全面改用starttls, 這部分outlook領先
> 可以看到[微軟幫助](https://support.microsoft.com/zh-cn/office/outlook-com-%E7%9A%84-pop-imap-%E5%92%8C-smtp-%E8%AE%BE%E7%BD%AE-d088b986-291d-42b8-9564-9c414e2aa040)已經全面拿掉SSL, 只剩下TLS與STARTTLS

@liaojack8 建议开一个PR吧，在PR中共同审查代码

**Comment by fgrtew** [comment]
创建容器的时候提示：Create container qd-1 failed: {"message":"No command specified"}.
