### ISSUE TITLE
[Bug] 模板编辑时的测试功能不通过环境变量设置的代理

### ISSUE THREAD

**Issue by ICEY1W32** [qd-today/qd#427]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20230618

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

测试任意模板即可

### Describe the Bug

使用附图左侧红框内测试无法通过代理访问，而右侧绿框内测试则正常通过代理

### QD log

```shell
[I 230618 13:25:12 tornado.access web:2344] 200 POST /har/test (*) 60017.59ms
[W 230618 13:26:00 QD.Http.Fetcher fetcher:484] GET * [Warning] HTTP 599: Connection timed out after 30001 milliseconds -> Try to retry!
[E 230618 13:26:30 QD.Http.Fetcher fetcher:488] Connection timed out after 30001 milliseconds
[I 230618 13:26:30 tornado.access web:2344] 200 POST /har/test (*) 60030.79ms
[I 230618 13:27:00 tornado.access web:2344] 200 POST /tpl/run (*) 1220.55ms
```

### Expected behavior

测试功能可以通过代理

### Screenshots

![示意图](https://github.com/qd-today/qd/assets/95471816/c185f1d3-6863-4a9c-b5b0-e100e2efb8e5)

**Comment by a76yyyy** [comment]
close by #398
