### ISSUE TITLE
[Bug] 排序后点保存，刷新后就变回之前那样，特别是有多个page的时候

### ISSUE THREAD

**Issue by aogg** [qd-today/qd#429]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20230618

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

[Bug] 排序后点保存，刷新后就变回之前那样，特别是有多个page的时候

还有点击下载，只能下载一个空文件，只有[]内容，是因为我设置了加密环境变量参数吗

### Describe the Bug

[Bug] 排序后点保存，刷新后就变回之前那样，特别是有多个page的时候

### QD log

```shell
无报错
```

### Expected behavior

不要刷新后就重置了

**Comment by a76yyyy** [comment]
老问题了，前端第三方组件和框架交互的问题，建议先不要使用拖拽排序功能吧，等待后续修复

**Comment by a76yyyy** [comment]
fixed by #447 

如果还有问题，请 reopen 这个 issue
