### ISSUE TITLE
[Bug] 总是出现修改了模板后在界面点运行还是跑的旧，编辑界面下面的总测试也是旧的，但是单个就是正常的

### ISSUE THREAD

**Issue by aogg** [qd-today/qd#436]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20230618

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

[Bug] 总是出现修改了模板后在界面点运行还是跑的旧，编辑界面下面的总测试也是旧的，但是单个就是正常的

### Describe the Bug

[Bug] 总是出现修改了模板后在界面点运行还是跑的旧，编辑界面下面的总测试也是旧的，但是单个就是正常的
重新登录也不行

### QD log

```shell
无报错
```

### Expected behavior

希望正常

**Comment by aogg** [comment]
编辑下面的总测试点击
[D 230702 11:25:36 tornado.curl_httpclient curl_httpclient:571] > authorization: OPENFRPeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2YWFlMTRjOGVhYzA0ZThkYjRkODdhNGY5N2IyZmVjMSIsImV4cCI6MTY4ODkxNjMwNn0.x9AyjCDDFrrwP9XdEOlWz_50NOwTJ3OuiIcaG-K74CSYe9N6H4u9S_3K1dk-uIhWvaBXAbYM7EGKRY6f_XQvNg, Strict-Transport-Security: max-age=31536000}




单个点击
[D 230702 11:25:06 tornado.curl_httpclient curl_httpclient:571] > authorization: OPENFRPeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMGZiYzQ1MmNhMTg0ZWY5YmM0YTQ4Y2JlZDYyNzIwYiIsImV4cCI6MTY4ODkxNjI0OH0.6ETRgGB_6fdgMOyJv10ETz6t3HHj-nImWU1aN-wv32UedpEnOgcA7-3fYYbZO1WJc0HZtya2u-vAon-Ver6XvQ



是什么影响了这两种方式同一个请求导致返回的结果不一样的

**Comment by aogg** [comment]
是不是单个点击请求的时候是从网页发送的请求？

**Comment by a76yyyy** [comment]
> 编辑下面的总测试点击 [D 230702 11:25:36 tornado.curl_httpclient curl_httpclient:571] > authorization: OPENFRPeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2YWFlMTRjOGVhYzA0ZThkYjRkODdhNGY5N2IyZmVjMSIsImV4cCI6MTY4ODkxNjMwNn0.x9AyjCDDFrrwP9XdEOlWz_50NOwTJ3OuiIcaG-K74CSYe9N6H4u9S_3K1dk-uIhWvaBXAbYM7EGKRY6f_XQvNg, Strict-Transport-Security: max-age=31536000}
> 
> 单个点击 [D 230702 11:25:06 tornado.curl_httpclient curl_httpclient:571] > authorization: OPENFRPeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMGZiYzQ1MmNhMTg0ZWY5YmM0YTQ4Y2JlZDYyNzIwYiIsImV4cCI6MTY4ODkxNjI0OH0.6ETRgGB_6fdgMOyJv10ETz6t3HHj-nImWU1aN-wv32UedpEnOgcA7-3fYYbZO1WJc0HZtya2u-vAon-Ver6XvQ
> 
> 是什么影响了这两种方式同一个请求导致返回的结果不一样的

怀疑你是这个问题

duplicate #432

**Comment by aogg** [comment]
应该是，快点到稳定版吧

**Comment by a76yyyy** [comment]
我先close这个issue了，如果有问题请再次reopen
