### ISSUE TITLE
[Feature] 希望自带的 urlencode 和 urldecode 可以指定字符集

### ISSUE THREAD

**Issue by sunjx97** [qd-today/qd#437]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QD 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QD 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

希望自带的 urlencode 和 urldecode 可以指定字符集。
最近遇到了个奇葩，urlencode 用的字符集是 GB18030，用默认的传过去是乱码，服了。

### Describe the solution

自带的 urlencode 和 urldecode 可以指定字符集，以应对更多情形。
默认（不指定参数）为 UTF-8，如有需要可以指定其他字符集（如 GB18030 等）。

**Comment by a76yyyy** [comment]
ToDo

**Comment by a76yyyy** [comment]
有问题请 reopen 这个 issue
