### ISSUE TITLE
[Bug] 使用源码的方式部署项目无法启动

### ISSUE THREAD

**Issue by yaoysyao** [qd-today/qd#444]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

最新源码

### Bug on OS

Windows

### Bug on Platform

Code Build/Windows x64

### To Reproduce

按照(https://qd-today.github.io/qd/zh_CN/guide/deployment.html)说明文档中的部署说明，python版本为3.8，安装了requirements.txt中所需要的库，使用python ./run.py 命令启动项目出现错误
`Traceback (most recent call last):
  File "./run.py", line 21, in <module>
    from web.app import Application
  File "E:\MyJob\PyCharm\qd\web\app.py", line 16, in <module>
    from libs.fetcher import Fetcher
  File "E:\MyJob\PyCharm\qd\libs\fetcher.py", line 29, in <module>
    from .safe_eval import safe_eval
  File "E:\MyJob\PyCharm\qd\libs\safe_eval.py", line 611, in <module>
    zoneinfo = wrap_module(__import__('zoneinfo'), [
ModuleNotFoundError: No module named 'zoneinfo'
`

### Describe the Bug

如上所述

### QD log

```shell
无
```

### Expected behavior

无

### Screenshots

![image](https://github.com/qd-today/qd/assets/38513384/5a240238-0cb5-458a-9b34-d6bb94cbfbb1)

**Comment by uiolee** [comment]
`No module named 'zoneinfo' .`

Update python to version 3.9 or higher

**Comment by yaoysyao** [comment]
> `No module named 'zoneinfo' .`
> 
> Update python to version 3.9 or higher

已解决
