### ISSUE TITLE
[Bug] Tg Bot 推送失败, 失败原因: 'NoneType' object has no attribute 'get_extra_info'

### ISSUE THREAD

**Issue by hunter8605** [qd-today/qd#446]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20230626

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

用下面的格式注册TG推送

1285435655:xxxxxxxxxx;856666666;;http://192.168.2.110:5890

token;userid;;proxy_url
tg_host使用默认，所以为空

点击注册，报错如下：
Tg Bot 推送失败, 失败原因: 'NoneType' object has no attribute 'get_extra_info'

用20220208版本时，同样的格式和内容，能成功注册，并收到推送信息

### Describe the Bug

点击注册，报错如下：
Tg Bot 推送失败, 失败原因: 'NoneType' object has no attribute 'get_extra_info'

用20220208版本时，同样的格式和内容，能成功注册，并收到推送信息

### QD log

```shell
[E 230713 11:33:13 QD.Http.Funcs funcs:174] Sent to Telegram error: 'NoneType' object has no attribute 'get_extra_info'
[I 230713 11:33:13 tornado.access web:2344] 200 POST /user/1/regpush (172.17.0.1) 10.65ms
容器才启动的日志：
[W 230713 11:00:43 QD.RedisDB redisdb:29] Connect Redis falied: "Error 99 connecting to localhost:6379. Address not available.".
```

### Expected behavior

成功注册并能收到推送信息

**Comment by a76yyyy** [comment]
上游模组 调用proxy tls的问题，详见 aio-libs/aiohttp#3355

**Comment by hunter8605** [comment]
> 上游模组 调用proxy tls的问题，详见 [aio-libs/aiohttp#3355](https://github.com/aio-libs/aiohttp/issues/3355)

现在只能等新版本更新，是吗?

**Comment by a76yyyy** [comment]
> > 上游模组 调用proxy tls的问题，详见 [aio-libs/aiohttp#3355](https://github.com/aio-libs/aiohttp/issues/3355)
> 
> 现在只能等新版本更新，是吗?

可以尝试更换代理或者等待模组更新

**Comment by hunter8605** [comment]
> > > 上游模组 调用proxy tls的问题，详见 [aio-libs/aiohttp#3355](https://github.com/aio-libs/aiohttp/issues/3355)
> > 
> > 
> > 现在只能等新版本更新，是吗?
> 
> 可以尝试更换代理或者等待模组更新

好的，感谢

**Comment by a76yyyy** [comment]
上游已修复, 请尝试更新至最新源码, 如还有问题请reopen这个issue

**Comment by hunter8605** [comment]
> 上游已修复, 请尝试更新至最新源码, 如还有问题请reopen这个issue
已更新至20230718版本，问题依旧
