### ISSUE TITLE
[Feature] 提取 Response Headers

### ISSUE THREAD

**Issue by loveqianool** [qd-today/qd#448]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QD 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QD 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

某些站 302 在 Response Headers 提供了 新地址，需要提取 Response Headers 某些字段为变量

### Describe the solution

没什么想法

**Comment by a76yyyy** [comment]
框架本身支持提取headers内容

就是目前有一些小bug，请等待后天发版或者使用已修复的dev版

**Comment by loveqianool** [comment]
> 框架本身支持提取headers内容
> 
> 就是目前有一些小bug，请等待后天发版或者使用已修复的dev版

怎么提呀，能不能告诉我一哈。

**Comment by a76yyyy** [comment]
> > 框架本身支持提取headers内容
> > 就是目前有一些小bug，请等待后天发版或者使用已修复的dev版
> 
> 怎么提呀，能不能告诉我一哈。

![image](https://github.com/qd-today/qd/assets/56478790/fa04b6ce-4f6d-44b0-a161-e3f0e439ec36)

**Comment by loveqianool** [comment]
> 

谢谢大佬
