### ISSUE TITLE
[Bug] 无法使用代理访问站点，疑似代理设置未生效

### ISSUE THREAD

**Issue by Patrick-Ze** [qd-today/qd#450]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20230718

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

**选择`qdtoday/qd:lite-latest`进行`docker compose`**

1. 添加一个需要代理才能访问的签到站点（例如 south-plus ）
2. 添加签到任务，在任务配置中设置代理为`http://192.168.31.50:1080`，代理客户端为docker外运行的clash
3. 执行签到任务，报错
```
Failed at 1/8 request,
Fail assert: {"re": "200", "from": "status"} from success_asserts,
Response Error : HTTP 599: error:0A000126:SSL routines::unexpected eof while reading,
Request URL: https://www.south-plus.net/plugin.php?H_name-tasks.html=
```

**备注**
1. 无需代理的任务签到正常
2. 我是从202301??的版本升级来的
3. 代理IP地址是host机的IP地址，已在docker内测试确认能够工作
```
sudo docker exec -it qd sh
/usr/src/app # curl https://www.south-plus.net -x 192.168.31.50:1080
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" ...此处省略网页内容
```

### Describe the Bug

To Reproduce 已经描述了

### QD log

```shell
Failed at 1/7 request,
Fail assert: {"re": "200", "from": "status"} from success_asserts,
Response Error : HTTP 599: error:0A000126:SSL routines::unexpected eof while reading,
Request URL: https://www.sehuatang.net/plugin.php?id=dd_sign%3Aindex
```

### Expected behavior

应当正常访问网络

**Comment by a76yyyy** [comment]
这个可能是对端网站服务器使用了过老的ssl/tls版本等产生的问题, 框架和代理本身是没有问题的

参考 openssl/openssl#18866, curl/curl#7800, 或许 加上 [SSL_OP_IGNORE_UNEXPECTED_EOF](https://www.openssl.org/docs/man3.0/man3/SSL_CTX_set_options.html#SSL_OP_IGNORE_UNEXPECTED_EOF) 可能有用, 但是我认为这可能不是框架本身应该实现的, 后续再考虑考虑

**Comment by Patrick-Ze** [comment]
> 这个可能是对端网站服务器使用了过老的ssl/tls版本等产生的问题, 框架和代理本身是没有问题的
> 
> 参考 [openssl/openssl#18866](https://github.com/openssl/openssl/issues/18866), [curl/curl#7800](https://github.com/curl/curl/issues/7800), 或许 加上 [SSL_OP_IGNORE_UNEXPECTED_EOF](https://www.openssl.org/docs/man3.0/man3/SSL_CTX_set_options.html#SSL_OP_IGNORE_UNEXPECTED_EOF) 可能有用, 但是我认为这可能不是框架本身应该实现的, 后续再考虑考虑

谢谢，我回去看下OpenSSL那边的这个问题

**Comment by SelxCyrus** [comment]
> > 这个可能是对端网站服务器使用了过老的ssl/tls版本等产生的问题, 框架和代理本身是没有问题的
> > 参考 [openssl/openssl#18866](https://github.com/openssl/openssl/issues/18866), [curl/curl#7800](https://github.com/curl/curl/issues/7800), 或许 加上 [SSL_OP_IGNORE_UNEXPECTED_EOF](https://www.openssl.org/docs/man3.0/man3/SSL_CTX_set_options.html#SSL_OP_IGNORE_UNEXPECTED_EOF) 可能有用, 但是我认为这可能不是框架本身应该实现的, 后续再考虑考虑
> 
> 谢谢，我回去看下OpenSSL那边的这个问题

大佬咋解决的，我的这边加了代理也无法签到，求教 @Patrick-Ze

**Comment by Patrick-Ze** [comment]
> 大佬咋解决的，我的这边加了代理也无法签到，求教 @Patrick-Ze

@SelxCyrus 你没描述问题现象。尝试重新docker compose up或者检查代理地址，不要用localhost

**Comment by SelxCyrus** [comment]
> 

非常感谢大佬回复，我的情况是这样的：
①我的“目标签到网址”需要搭梯子才可以访问这个网址，默认的情况执行签到会显示Response Error : HTTP 599: Failed to connect to xsijishe.com port 443 after 15215 ms: Couldn't connect to server。
②我的Docker部署在nas中，并非局域网，通过DDNS-GO内网穿透实现容器的访问。
③梯子官网给我的代理环境，set http_proxy=http://127.0.0.1:15732&& set https_proxy=http://127.0.0.1:15732。
        我原本的想法是，在框架启用任务中的“代理”一行，填写我梯子给的服务器代理地址（127.0.0.1:15732，也是官网提供）来进行签到，但尝试后仍无法链接，显示Response Error : HTTP 599: Failed to connect to 127.0.0.1 port 15732 after 0 ms: Couldn't connect to server。问a76大佬，说“框架无法在容器内部通过本地地址访问到容器外的外部地址的代理”，我大概理解了一点。
        但是不知道具体如何去实现我这种情况的自动签到，如何更改代理地址（小白对代理的理解有误，思来想去不知道到底该改哪个地址），还是需要我更改整个容器甚至Docker的代理环境，还是其他的方法。
        希望辛苦大佬给我指导下，万分感谢！！！ @Patrick-Ze

**Comment by Patrick-Ze** [comment]
@SelxCyrus 127.0.0.1，也就是localhost，是本地环回地址，在docker内的127.0.0.1和docker外的127.0.0.1不能互相访问的（你可以理解为它们具有各自的“本地”）。要在docker内访问架设在docker外的代理的话，需要先获取到docker外运行代理的机器的ip，例如我的就是192.168.31.50，然后使用这个IP来配置qiandao的代理。
可以通过如下方式验证代理在docker内能否访问
`sudo docker exec -it qd sh`
上面这句是连接到docker内部的命令行

`/usr/src/app # curl https://www.south-plus.net/ -x 192.168.31.50:1080`
上面这句是在docker内部使用代理访问被墙地址。网址和代理换成你自己的

**Comment by Patrick-Ze** [comment]
> 谢谢，我回去看下OpenSSL那边的这个问题

之前莫名其妙遇到这个问题，又莫名其妙好了。这两天又遇到了（没有更新OpenSSL），通过换代理工具、换版本等一番折腾和摸索，定位到应该是clash的cache.db文件有影响，具体内部原理未知。我删除clash的cache.db，然后重启clash后，这些需要代理的站点访问就正常了。
