### ISSUE TITLE
突然之间所有任务都消失了，查看数据库发现任务数据全部到了taskold

### ISSUE THREAD

**Issue by x2009again** [qd-today/qd#452]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20230228

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

不知道为什么突然23号的时候，任务列表的任务全部丢失了，我没有更新过版本

### Describe the Bug

不知道为什么突然23号的时候，任务列表的任务全部丢失了，查看sqlite发现任务数据都到了taskold，吧taskold的数据插入到task恢复了任务，我不知道为什么会出现这种情况，查看源码发现在DBconverter中的_convert_task有个修改表名task为taskold的操作，我想问问什么时候会触发这个操作？

### QD log

```shell
docker里面没有23号的日志
```

### Expected behavior

想知道哪里会触发task改为taskold，会不会那个按钮误操作会触发。

**Comment by a76yyyy** [comment]
可能是在容器因某些非框架原因导致容器重启，容器重启后在进行初始化(这时会进行数据库转换)的过程中，容器又崩溃了，导致容器初始化中断

**Comment by x2009again** [comment]
有这个可能，9点多是我自己重启的，15点30这个估计是出问题了重启的，下面是日志
[I 230722 09:24:54 qiandao.Worker worker:273] Queue Worker start...
[I 230722 09:24:54 qiandao.Run run:83] Http Server started on 0.0.0.0:80
[I 230722 15:30:21 qiandao.Worker worker:273] Queue Worker start...
[I 230722 15:30:21 qiandao.Run run:83] Http Server started on 0.0.0.0:80

**Comment by a76yyyy** [comment]
> 有这个可能，9点多是我自己重启的，15点30这个估计是出问题了重启的，下面是日志 [I 230722 09:24:54 qiandao.Worker worker:273] Queue Worker start... [I 230722 09:24:54 qiandao.Run run:83] Http Server started on 0.0.0.0:80 [I 230722 15:30:21 qiandao.Worker worker:273] Queue Worker start... [I 230722 15:30:21 qiandao.Run run:83] Http Server started on 0.0.0.0:80

我先暂时关闭这个issue了，如果经常出现这种情况，请 reopen 这个issue
