### ISSUE TITLE
[Bug] 公共模板更新失败

### ISSUE THREAD

**Issue by chingxuds** [qd-today/qd#453]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20230718

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

正常登录后，打开公共模板页面，提示模板更新失败，错误码：1006。如下图：
<img width="1624" alt="image" src="https://github.com/qd-today/qd/assets/3142486/22e5bdb9-dab5-47d7-ac3e-9b790e4f1cdd">

### Describe the Bug

如上文描述，打开公共模板页面提示更新错误，错误码：1006。
1、前提：服务器已支持直接访问github。
2、已尝试解决方案如下，均无效：
（1）替换SUBSCRIBE_ACCELERATE_URL为fastgit。
（2）替换SUBSCRIBE_ACCELERATE_URL为https://raw.githubusercontent.com/，即尝试不使用代理。
3、通过查询DNS记录，发现并无相关域名请求记录，怀疑为请求未真正发起。

### QD config

```shell
version: "3"

services:
  qiandao:
    image: qdtoday/qd:latest
    container_name: qiandao
    restart: always
    expose:
      - 80
    volumes:
      - ./config:/usr/src/app/config
    environment:
      - BIND=0.0.0.0
      - PORT=80
      - DOMAIN=xxx
      - AES_KEY=xxx
      - COOKIE_SECRET=xxx
      - SUBSCRIBE_ACCELERATE_URL=https://raw.githubusercontent.com/
```

### QD log

```shell
Docker错误日志：

qiandao    | [I 230724 09:31:53 tornado.access web:2344] 101 GET /subscribe/1/updating/ (10.10.10.2) 0.88ms
qiandao    | [E 230724 09:31:53 tornado.application web:1871] Uncaught exception GET /subscribe/1/updating/ (10.10.10.2)
qiandao    |     HTTPServerRequest(protocol='https', host='xxx.xxx', method='GET', uri='/subscribe/1/updating/', version='HTTP/1.0', remote_ip='xxx.xxx.xxx.xxx')
qiandao    |     Traceback (most recent call last):
qiandao    |       File "/usr/lib/python3.11/site-packages/tornado/websocket.py", line 939, in _accept_connection
qiandao    |         await open_result
qiandao    |       File "/usr/src/app/web/handlers/subscribe.py", line 252, in open
qiandao    |         self.write_message({'code': 1000, 'message': '开始更新...'})
qiandao    |       File "/usr/lib/python3.11/site-packages/tornado/websocket.py", line 331, in write_message
qiandao    |         raise WebSocketClosedError()
qiandao    |     tornado.websocket.WebSocketClosedError
```
```


### Expected behavior

公共模板能够正常访问。

### Screenshots

_No response_

**Comment by chen8945** [comment]
不出意外你大概是你的反代没有配置 WS
![image](https://github.com/qd-today/qd/assets/44148812/33d1eb7a-f75e-445d-b918-ce208e2d1cdd)

**Comment by chingxuds** [comment]
> 

确实没有配置http版本，多谢了。
之前版本没有配置一直没有问题，最近更新了下结果报错了，所以没往这边想。

**Comment by leic4u** [comment]
谢谢

**Comment by 907739769** [comment]
location / {
	proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_pass http://IP地址:端口;
    }
