### ISSUE TITLE
[Feature] 怎么才能使用邮箱服务？

### ISSUE THREAD

**Issue by zadishu** [qd-today/qd#455]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QD 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QD 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

找不到答案
![WeChat截图_20230724145807](https://github.com/qd-today/qd/assets/110985414/b6eab72c-c4ac-4ea8-8e06-4d91818937dd)

### Describe the solution

不知道怎么设置

**Comment by a76yyyy** [comment]
https://qd-today.github.io/qd/zh_CN/toolbox/pusher.html#%E9%82%AE%E4%BB%B6%E6%8E%A8%E9%80%81

**Comment by zadishu** [comment]
配置好了 显示(535, b'Error: authentication failed')

**Comment by a76yyyy** [comment]
dup #454
