### ISSUE TITLE
[Bug] 上传har后，页面上有接口显示，但点下载是空，点测试直接报错

### ISSUE THREAD

**Issue by aogg** [qd-today/qd#457]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20230618

### Bug on OS

Linux

### Bug on Platform

Code Build/Linux 64位

### To Reproduce

[Bug] 上传har后，页面上有接口显示，但点下载是空，点测试直接报错

### Describe the Bug

[Bug] 上传har后，页面上有接口显示，但点下载是空，点测试直接报错

### QD log

```shell
[Bug] 上传har后，页面上有接口显示，但点下载是空，点测试直接报错
```

### Expected behavior

[Bug] 上传har后，页面上有接口显示，但点下载是空，点测试直接报错

**Comment by a76yyyy** [comment]
更新到最新版尝试，并且请提供一下前端控制台或者容器后端的错误日志

**Comment by a76yyyy** [comment]
这里测试没问题, 请提供测试har

并且这里看到您使用了**源码部署**方式, 不知道您是否修改了配置文件的哪些地方或者设置了何种反代方式

如果有相关修改或配置, 方便的话可以提供一下

**Comment by acooler15** [comment]
点击全选后，再点击“测试”或“下载”，如果还不行，麻烦提交下操作截图

**Comment by a76yyyy** [comment]
这个 issue 很久没有更新，先暂时关闭 issue 了，如果您还有问题请 reopen 这个 issue
