### ISSUE TITLE
自然日内随机延迟执行签到

### ISSUE THREAD

**Issue by if1y** [qd-today/qd#46]
目前在“定时”选项中设置`随机延迟`后，只有效一次。
、
因为最近遇到某网站会排查异常行为，一直同一个时间就会被判断为异常，所以希望最好可以在**每天自然日内随机延迟执行**。

**Comment by asdaragon** [comment]
@if1y 设置后长期有效的，你可以将延时设大一点，如3600 - 7200 s

**Comment by if1y** [comment]
这就比较蹊跷了，那我多观察几天吧，昨天设置了一次，执行完成之后就复原了……
