### ISSUE TITLE
[Bug] 开启推送后重复推送

### ISSUE THREAD

**Issue by zadishu** [qd-today/qd#462]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20230718

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

每隔1分钟左右就会推送，无限推送

### Describe the Bug

每隔1分钟左右就会推送，无限推送

### QD log

```shell
每隔1分钟左右就会推送，无限推送
```

### Expected behavior

每隔1分钟左右就会推送，无限推送

**Comment by a76yyyy** [comment]
你看一下`工具箱-推送设置`里是不是开启了`自动执行成功推送`，如果开启了的话，每自动执行成功一次任务都会推送一次。

或者检查是否开启了`批量推送`，如果开启了看一下推送间隔是否设置有问题，推送间隔是以秒为单位计算的

**Comment by zadishu** [comment]
没有开启，自动执行成功推送
开启定期批量推送 间隔86400秒、
好像是自从删了某个任务，就开始疯狂推送

**Comment by a76yyyy** [comment]
> 没有开启，自动执行成功推送 开启定期批量推送 间隔86400秒、 好像是自从删了某个任务，就开始疯狂推送

看一下后台日志，最好可以通过环境变量开一下debug模式看看

**Comment by zadishu** [comment]
[qiandao_logs (1).txt](https://github.com/qd-today/qd/files/12385921/qiandao_logs.1.txt)
后台日志，无限推送，

**Comment by zadishu** [comment]
日志2
[qiandao_logs (2).txt](https://github.com/qd-today/qd/files/12385948/qiandao_logs.2.txt)

**Comment by zadishu** [comment]
![3](https://github.com/qd-today/qd/assets/110985414/de86d0e5-994a-4d8a-9a43-f6c54e83982d)
[_a76yyyy-qiandao_logs (3).txt](https://github.com/qd-today/qd/files/12386077/_a76yyyy-qiandao_logs.3.txt)

**Comment by a76yyyy** [comment]
> ![3](https://user-images.githubusercontent.com/110985414/261802288-de86d0e5-994a-4d8a-9a43-f6c54e83982d.png)

Bug 已定位, txt 链接帮您删了, 避免泄露隐私

**Comment by zadishu** [comment]
大佬 求解决方案

**Comment by a76yyyy** [comment]
> 大佬 求解决方案

已修复代码, 请拉取 `qdtoday/qd:dev` 容器测试问题是否解决.

更换 dev 容器前请**务必备份数据库**

**Comment by zadishu** [comment]
问题已得到解决
qdtoday/qd:dev
