### ISSUE TITLE
[Feature] 提取 Request Headers

### ISSUE THREAD

**Issue by chen8945** [qd-today/qd#466]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QD 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QD 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

目前框架似乎只支持提取Response Headers，但是个别网站在使用账号密码登录后需要提取请求头中 Cookie 的部分内容，加入到后续请求的请求头中

### Describe the solution

例如这个，就需要提取请求头 Cookie 中的 b2_token 字段，加入到后续请求的请求头中
![image](https://github.com/qd-today/qd/assets/44148812/d15330c2-9113-45ca-bf0c-eb1b4ecea7e7)
![image](https://github.com/qd-today/qd/assets/44148812/9149a036-6658-484e-903d-cb08f059c24e)

**Comment by a76yyyy** [comment]
可是request header不可能是凭空来的呀?它一般只可能是手动设置或者其他response的结果

**Comment by chen8945** [comment]
> 可是request header不可能是凭空来的呀?它一般只可能是手动设置或者其他response的结果

刚刚找到了另一个方式获取token，但是之前我说的是这样的

这第一个请求是通过账号密码登录，发送出去后响应内容为空，直接重定向到了网站首页，第二个请求响应头里也没有相关数据，也可能是我遗漏了，回头我再排查看看
![image](https://github.com/qd-today/qd/assets/44148812/586c0308-da7c-42dd-ba93-aaf7f81be560)
