### ISSUE TITLE
bark无法推送

### ISSUE THREAD

**Issue by hecarli555** [qd-today/qd#47]
设置了bark，点击了测试，可收到短信，但实际上定时签到的时候并没有触发bark的推送通知，望大佬修复解决

**Comment by hecarli555** [comment]
> 设置了bark，点击了测试，可收到测试推送，但实际上定时签到的时候并没有触发bark的推送通知，望大佬修复解决

**Comment by asdaragon** [comment]
@hecarli555 测试后要点注册，然后在首页-推送设置里开启推送，选择四个情况都推送，手动执行以下看是否推送

**Comment by hecarli555** [comment]
> @hecarli555 测试后要点注册，然后在首页-推送设置里开启推送，选择四个情况都推送，手动执行以下看是否推送

另外请问一下，推送通知里能展示通知详情么？例如签到有多少积分，诸如此类的内容

**Comment by asdaragon** [comment]
默认是推送日志，你日志里有这些内容就会有

**Comment by hecarli555** [comment]
> 默认是推送日志，你日志里有这些内容就会有
日志里是有积分详细内容的，刚刚测试手动执行签到的时候，bark推送只显示“签到任务XXX成功”，没有显示签到详情。。。

**Comment by hecarli555** [comment]
> 默认是推送日志，你日志里有这些内容就会有

日志里是有积分详细内容的，刚刚测试手动执行签到的时候，bark推送只显示“签到任务XXX成功”，没有显示签到详情。。。

**Comment by asdaragon** [comment]
手动运行的没有，设个定时自动运行

**Comment by hecarli555** [comment]
> 手动运行的没有，设个定时自动运行

好的，谢谢大佬解答，明天定时签到看看有没有详情

**Comment by hecarli555** [comment]
> > 手动运行的没有，设个定时自动运行
> 
> 好的，谢谢大佬解答，明天定时签到看看有没有详情



> 手动运行的没有，设个定时自动运行

**Comment by hecarli555** [comment]
> > 手动运行的没有，设个定时自动运行
> 
> 好的，谢谢大佬解答，明天定时签到看看有没有详情

大佬，另外问一下，那个成功失败的次数记录能手动清零的么？

**Comment by hecarli555** [comment]
> 手动运行的没有，设个定时自动运行

大佬，另外问一下，那个成功失败的次数记录能手动清零的么？
