### ISSUE TITLE
[Feature] Enable JavaScript and cookies to continue报错

### ISSUE THREAD

**Issue by shanren200** [qd-today/qd#476]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QD 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QD 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

模板是自己修改的某91大神游戏网站，前两天成功了第三天签到失败了，然后进行单步测试发现第一步就报错Enable JavaScript and cookies to continue。
![图片](https://github.com/qd-today/qd/assets/60208500/f82d73a2-48dc-4976-878e-ee46be21915a)
![图片](https://github.com/qd-today/qd/assets/60208500/2a8886fe-a5aa-41a9-b716-9c39e911d994)

### Describe the solution

想请问这是网站端被拦截还是有类似的打开开关？

**Comment by a76yyyy** [comment]
框架因为安全性考虑，没有计划支持js加载

**Comment by Zyx-A** [comment]
> 框架因为安全性考虑，没有计划支持js加载

那如果遇到这种签到的需求，请问有替代或变通的解决方案吗

**Comment by a76yyyy** [comment]
> > 框架因为安全性考虑，没有计划支持js加载
> 
> 那如果遇到这种签到的需求，请问有替代或变通的解决方案吗

事实上这种一般都是开了CF盾，可以参考这个帖子 https://github.com/qd-today/templates/issues/329
