### ISSUE TITLE
[bug]管理员将网站管理中的禁止注册和必须验证邮箱都勾选之后，无法登录。

### ISSUE THREAD

**Issue by WhyFear** [qd-today/qd#49]
管理员将[网站管理]中的[禁止注册]和[必须验证邮箱]都勾选之后，因为没有设置邮件发送，无法发送验证邮件，这时就会出现管理员账号也无法登录的情况。登录时提示“email地址未验证，邮件已发送，请验证邮件后登陆”。因为禁止注册，也无法通过注册新用户然后设置为管理员的方法将必须验证邮箱选项关闭。
必须更改本地sqlite数据库，将email_verified 改为1管理员账号才能登录。
我认为在管理员未设置邮件发送方式时，必须验证邮箱选项应该不可选。
另外，除了更改数据库，还有其他解决上述问题的办法吗？

**Comment by asdaragon** [comment]
@WhyFear 懒得改了，修改数据库吧

**Comment by if1y** [comment]
确实是逻辑漏洞，验证邮箱没什么必要，别勾选

**Comment by asdaragon** [comment]
改好了
