### ISSUE TITLE
[Feature] Bark-server的basic auth（←server启用用户名密码）不懂qd里该如何输入使其成功推送

### ISSUE THREAD

**Issue by DFP86** [qd-today/qd#499]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QD 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QD 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

bark-server 设置了用户名和密码， qd框架里面无法成功注册 bark 推送。
（bark-server不设置用户名和密码测试成功）

### Describe the solution

您好，大大，我想请问下，框架里面bark的推送注册链接，是否不支持bark-server的有用户名和密码功能？我用postman等工具测试是可以的，但注册推送的时候填入的内容无法包含 basic auth 的用户名和密码内容……

测试了好久和查了所有关于bark的issue也没找到解决办法，可能是我没找到设置方法，如果支持，请告诉我该如何设置。如果不支持，请问未来能否添加上支持basic auth用户名和密码的bark推送？

感谢您抽出时间查看我的问题~~万分感谢！！

### Describe alternatives

暂无，只能先关闭bark的用户名和密码……但因为服务器暴露在公网，感觉比较危险。

### Additional context

![image](https://github.com/qd-today/qd/assets/12046701/b6b63ef7-6d62-4c87-a374-78780a9b943e)

**Comment by a76yyyy** [comment]
https://qd-today.github.io/qd/zh_CN/toolbox/pusher.html#bark-%E6%8E%A8%E9%80%81

你是说只设置推送码不安全，再加上用户名密码认证么？

**Comment by DFP86** [comment]
> https://qd-today.github.io/qd/zh_CN/toolbox/pusher.html#bark-%E6%8E%A8%E9%80%81
> 
> 你是说只设置推送码不安全，再加上用户名密码认证么？

大佬 我错了，昨晚我加了bark的群问到了，原来qd框架已经支持basic auth了！！！因为我太小白所以不懂。

因为在bark-server的启动设置里设置了用户名和密码，所以输入barkUrl的时候也需要加入，但bark的作者没有在教程中写出来，结果我搞了好久也填不进去，实际上这样就可以了:

http:// user : pwd @192.168.1.100:port/ my key/

就可以了！！！

谢谢大佬！！！万分感激啊！！！！
