### ISSUE TITLE
[Bug] 添加任务-设置代理-提交后显示：405: Method Not Allowed

### ISSUE THREAD

**Issue by Kolakona** [qd-today/qd#500]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20230821

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位, Code Build/Linux 64位

### To Reproduce
平台：dsm7.0.1 docker20.10.3.1239
添加任务，设置代理该选项时，输入http://192.168.123.110:10809 （局域网中代理地址），提交。

### Describe the Bug

添加任务-设置代理-提交后显示：405: Method Not Allowed

### QD log

```shell
无
```

### Expected behavior

可以通过设置代理来进行无法直连的网站签到

### Screenshots

![image](https://github.com/qd-today/qd/assets/19240323/cea99e02-7e2e-47fb-a7be-524989a23daa)

**Comment by a76yyyy** [comment]
升级至最新版后再试一次

**Comment by Kolakona** [comment]
> 升级至最新版后再试一次

更新版本到20240208了，还是一样显示 405: Method Not Allowed

**Comment by a76yyyy** [comment]
有405日志或者截图么？或者开启debug模式，看一下后台日志

看看是不是代理不支持http

**Comment by loveqianool** [comment]
> 有405日志或者截图么？或者开启debug模式，看一下后台日志
> 
> 看看是不是代理不支持http

最新版随便找个任务修改都是 405，不管是用户名，密码，还是代理备注，但是可以删除任务，然后新建正常运行。
新春快乐

**Comment by Kolakona** [comment]
> 有405日志或者截图么？或者开启debug模式，看一下后台日志
> 
> 看看是不是代理不支持http

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tornado/web.py", line 269, in _unimplemented_method
    raise HTTPError(405)
tornado.web.HTTPError: HTTP 405: Method Not Allowed

**Comment by Kolakona** [comment]
> > 有405日志或者截图么？或者开启debug模式，看一下后台日志
> > 看看是不是代理不支持http
> 
> 最新版随便找个任务修改都是 405，不管是用户名，密码，还是代理备注，但是可以删除任务，然后新建正常运行。 新春快乐

原来如此，试了一下删除再新建确实可以了！
祝开发者及层主新春快乐~

**Comment by a76yyyy** [comment]
确实是bug，尽快修复

**Comment by a76yyyy** [comment]
@Kolakona @loveqianool Dev 版已修复（Fixed by #[68aa0b7](https://github.com/qd-today/qd/commit/68aa0b7bde49bebf10bbd640b88cfd8ecad7e016)），可以使用 qdtoday/qd:dev 容器测试一下，如果没有问题我尽快发版

**Comment by Kolakona** [comment]
> @Kolakona @loveqianool Dev 版已修复（Fixed by #[68aa0b7](https://github.com/qd-today/qd/commit/68aa0b7bde49bebf10bbd640b88cfd8ecad7e016)），可以使用 qdtoday/qd:dev 容器测试一下，如果没有问题我尽快发版

测试了，正常了
