### ISSUE TITLE
[ASK] 對於請求時夾帶base64編碼過後的資料能夠透過那些方式解決呢

### ISSUE THREAD

**Issue by liaojack8** [qd-today/qd#501]
### Verify steps

- [x] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QD 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QD 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

自動化過程中需要捕捉網頁上的不固定的字串
並解夾帶在之後的請求當中
但是夾帶的資料是經過base64編碼的
先利用正則過濾出我要的字串作為變數
但沒辦法將變數再進行base64編碼

### Describe the solution

使用了b64encode api過後報錯
想知道有沒有其他的解決思路
![2024-02-11_06h00_19](https://github.com/qd-today/qd/assets/23449425/b369ecf3-8c57-45ec-b542-28939a7aff46)
![2024-02-11_06h00_32](https://github.com/qd-today/qd/assets/23449425/e43acb4b-e5cb-43d4-b567-18f51ae79687)

**Comment by a76yyyy** [comment]
使用 `{{b64encode(testvar)}}`，`{{}}`内无需再用`{{}}`包裹变量
