### ISSUE TITLE
默认为禁止注册状态？隐藏按钮了怎么注册管理员

### ISSUE THREAD

**Issue by ghost** [qd-today/qd#51]
默认为禁止注册状态？隐藏按钮了怎么注册管理员

**Comment by bao3** [comment]
我也注册不了，无法登录也无法注册。
如果自己在数据库创建用户，则登录时就会 `500: Internal Server Error`

>  [I 210110 19:46:21 web:2162] 200 POST /login (192.168.50.248) 6.23ms
> [I 210110 19:46:21 web:2162] 304 GET /static/body.jpg (192.168.50.248) 6.89ms
> [I 210110 19:46:21 web:2162] 304 GET /static/components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff (192.168.50.248) 1.51ms
> [E 210110 19:46:25 web:1670] Uncaught exception POST /login (192.168.50.248)
>     HTTPServerRequest(protocol='http', host='192.168.50.85', method='POST', uri='/login', version='HTTP/1.1', remote_ip='192.168.50.248')
>     Traceback (most recent call last):
>       File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
>         result = method(*self.path_args, **self.path_kwargs)
>       File "/root/qiandao/web/handlers/login.py", line 49, in post
>         if self.db.user.challenge(email, password):
>       File "/root/qiandao/db/user.py", line 72, in challenge
>         password_hash = self.decrypt(user['id'], user['password'])
>       File "/root/qiandao/db/user.py", line 109, in decrypt
>         userkey = self.__getuserkey(id)
>       File "/root/qiandao/libs/utils.py", line 45, in wrapper
>         self._cache[key] = fn(self, *args, **kwargs)
>       File "/root/qiandao/db/user.py", line 94, in __getuserkey
>         return crypto.aes_decrypt(userkey)
>       File "/root/qiandao/libs/mcrypto.py", line 46, in aes_decrypt
>         word, iv = umsgpack.unpackb(word)
>       File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 1081, in _unpackb2
>         return _unpack(io.BytesIO(s), options)
>       File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 936, in _unpack
>         code = _read_except(fp, 1)
>       File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 707, in _read_except
>         raise InsufficientDataException()
>     InsufficientDataException
> [E 210110 19:46:25 web:1670] Uncaught exception POST /login (192.168.50.248)
>     HTTPServerRequest(protocol='http', host='192.168.50.85', method='POST', uri='/login', version='HTTP/1.1', remote_ip='192.168.50.248')
>     Traceback (most recent call last):
>       File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
>         result = method(*self.path_args, **self.path_kwargs)
>       File "/root/qiandao/web/handlers/login.py", line 49, in post
>         if self.db.user.challenge(email, password):
>       File "/root/qiandao/db/user.py", line 72, in challenge
>         password_hash = self.decrypt(user['id'], user['password'])
>       File "/root/qiandao/db/user.py", line 109, in decrypt
>         userkey = self.__getuserkey(id)
>       File "/root/qiandao/libs/utils.py", line 45, in wrapper
>         self._cache[key] = fn(self, *args, **kwargs)
>       File "/root/qiandao/db/user.py", line 94, in __getuserkey
>         return crypto.aes_decrypt(userkey)
>       File "/root/qiandao/libs/mcrypto.py", line 46, in aes_decrypt
>         word, iv = umsgpack.unpackb(word)
>       File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 1081, in _unpackb2
>         return _unpack(io.BytesIO(s), options)
>       File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 936, in _unpack
>         code = _read_except(fp, 1)
>       File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 707, in _read_except
>         raise InsufficientDataException()
>     InsufficientDataException
> [E 210110 19:46:25 web:2162] 500 POST /login (192.168.50.248) 10.20ms
> [E 210110 19:46:25 web:2162] 500 POST /login (192.168.50.248) 10.20ms
> 
> 
>

**Comment by ghost** [comment]
> 我也注册不了，无法登录也无法注册。
> 如果自己在数据库创建用户，则登录时就会 `500: Internal Server Error`
> 
> > [I 210110 19:46:21 web:2162] 200 POST /login (192.168.50.248) 6.23ms
> > [I 210110 19:46:21 web:2162] 304 GET /static/body.jpg (192.168.50.248) 6.89ms
> > [I 210110 19:46:21 web:2162] 304 GET /static/components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff (192.168.50.248) 1.51ms
> > [E 210110 19:46:25 web:1670] Uncaught exception POST /login (192.168.50.248)
> > HTTPServerRequest(protocol='http', host='192.168.50.85', method='POST', uri='/login', version='HTTP/1.1', remote_ip='192.168.50.248')
> > Traceback (most recent call last):
> > File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
> > result = method(*self.path_args, **self.path_kwargs)
> > File "/root/qiandao/web/handlers/login.py", line 49, in post
> > if self.db.user.challenge(email, password):
> > File "/root/qiandao/db/user.py", line 72, in challenge
> > password_hash = self.decrypt(user['id'], user['password'])
> > File "/root/qiandao/db/user.py", line 109, in decrypt
> > userkey = self.__getuserkey(id)
> > File "/root/qiandao/libs/utils.py", line 45, in wrapper
> > self._cache[key] = fn(self, *args, **kwargs)
> > File "/root/qiandao/db/user.py", line 94, in __getuserkey
> > return crypto.aes_decrypt(userkey)
> > File "/root/qiandao/libs/mcrypto.py", line 46, in aes_decrypt
> > word, iv = umsgpack.unpackb(word)
> > File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 1081, in _unpackb2
> > return _unpack(io.BytesIO(s), options)
> > File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 936, in _unpack
> > code = _read_except(fp, 1)
> > File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 707, in _read_except
> > raise InsufficientDataException()
> > InsufficientDataException
> > [E 210110 19:46:25 web:1670] Uncaught exception POST /login (192.168.50.248)
> > HTTPServerRequest(protocol='http', host='192.168.50.85', method='POST', uri='/login', version='HTTP/1.1', remote_ip='192.168.50.248')
> > Traceback (most recent call last):
> > File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
> > result = method(*self.path_args, **self.path_kwargs)
> > File "/root/qiandao/web/handlers/login.py", line 49, in post
> > if self.db.user.challenge(email, password):
> > File "/root/qiandao/db/user.py", line 72, in challenge
> > password_hash = self.decrypt(user['id'], user['password'])
> > File "/root/qiandao/db/user.py", line 109, in decrypt
> > userkey = self.__getuserkey(id)
> > File "/root/qiandao/libs/utils.py", line 45, in wrapper
> > self._cache[key] = fn(self, *args, **kwargs)
> > File "/root/qiandao/db/user.py", line 94, in __getuserkey
> > return crypto.aes_decrypt(userkey)
> > File "/root/qiandao/libs/mcrypto.py", line 46, in aes_decrypt
> > word, iv = umsgpack.unpackb(word)
> > File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 1081, in _unpackb2
> > return _unpack(io.BytesIO(s), options)
> > File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 936, in _unpack
> > code = _read_except(fp, 1)
> > File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 707, in _read_except
> > raise InsufficientDataException()
> > InsufficientDataException
> > [E 210110 19:46:25 web:2162] 500 POST /login (192.168.50.248) 10.20ms
> > [E 210110 19:46:25 web:2162] 500 POST /login (192.168.50.248) 10.20ms

打开/web/tpl/register.html  删除第34行 {% if regFlg %}  和36行{% endif %}，就有注册按钮了

**Comment by bao3** [comment]
> > 我也注册不了，无法登录也无法注册。
> > 如果自己在数据库创建用户，则登录时就会 `500: Internal Server Error`
> > > [I 210110 19:46:21 web:2162] 200 POST /login (192.168.50.248) 6.23ms
> > > [I 210110 19:46:21 web:2162] 304 GET /static/body.jpg (192.168.50.248) 6.89ms
> > > [I 210110 19:46:21 web:2162] 304 GET /static/components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff (192.168.50.248) 1.51ms
> > > [E 210110 19:46:25 web:1670] Uncaught exception POST /login (192.168.50.248)
> > > HTTPServerRequest(protocol='http', host='192.168.50.85', method='POST', uri='/login', version='HTTP/1.1', remote_ip='192.168.50.248')
> > > Traceback (most recent call last):
> > > File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
> > > result = method(*self.path_args, **self.path_kwargs)
> > > File "/root/qiandao/web/handlers/login.py", line 49, in post
> > > if self.db.user.challenge(email, password):
> > > File "/root/qiandao/db/user.py", line 72, in challenge
> > > password_hash = self.decrypt(user['id'], user['password'])
> > > File "/root/qiandao/db/user.py", line 109, in decrypt
> > > userkey = self.__getuserkey(id)
> > > File "/root/qiandao/libs/utils.py", line 45, in wrapper
> > > self._cache[key] = fn(self, *args, **kwargs)
> > > File "/root/qiandao/db/user.py", line 94, in __getuserkey
> > > return crypto.aes_decrypt(userkey)
> > > File "/root/qiandao/libs/mcrypto.py", line 46, in aes_decrypt
> > > word, iv = umsgpack.unpackb(word)
> > > File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 1081, in _unpackb2
> > > return _unpack(io.BytesIO(s), options)
> > > File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 936, in _unpack
> > > code = _read_except(fp, 1)
> > > File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 707, in _read_except
> > > raise InsufficientDataException()
> > > InsufficientDataException
> > > [E 210110 19:46:25 web:1670] Uncaught exception POST /login (192.168.50.248)
> > > HTTPServerRequest(protocol='http', host='192.168.50.85', method='POST', uri='/login', version='HTTP/1.1', remote_ip='192.168.50.248')
> > > Traceback (most recent call last):
> > > File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
> > > result = method(*self.path_args, **self.path_kwargs)
> > > File "/root/qiandao/web/handlers/login.py", line 49, in post
> > > if self.db.user.challenge(email, password):
> > > File "/root/qiandao/db/user.py", line 72, in challenge
> > > password_hash = self.decrypt(user['id'], user['password'])
> > > File "/root/qiandao/db/user.py", line 109, in decrypt
> > > userkey = self.__getuserkey(id)
> > > File "/root/qiandao/libs/utils.py", line 45, in wrapper
> > > self._cache[key] = fn(self, *args, **kwargs)
> > > File "/root/qiandao/db/user.py", line 94, in __getuserkey
> > > return crypto.aes_decrypt(userkey)
> > > File "/root/qiandao/libs/mcrypto.py", line 46, in aes_decrypt
> > > word, iv = umsgpack.unpackb(word)
> > > File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 1081, in _unpackb2
> > > return _unpack(io.BytesIO(s), options)
> > > File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 936, in _unpack
> > > code = _read_except(fp, 1)
> > > File "/usr/local/lib/python2.7/dist-packages/umsgpack.py", line 707, in _read_except
> > > raise InsufficientDataException()
> > > InsufficientDataException
> > > [E 210110 19:46:25 web:2162] 500 POST /login (192.168.50.248) 10.20ms
> > > [E 210110 19:46:25 web:2162] 500 POST /login (192.168.50.248) 10.20ms
> 
> 打开/web/tpl/register.html 删除第34行 {% if regFlg %} 和36行{% endif %}，就有注册按钮了

感谢，确实可以了。done
