### ISSUE TITLE
[Bug] Outlook邮箱无法发送邮件

### ISSUE THREAD

**Issue by MuggleTan** [qd-today/qd#516]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20240210

### Bug on OS

Windows, Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

![image](https://github.com/qd-today/qd/assets/50989379/0f2e11c4-2239-4e35-afc9-d2c39e61e3ad)
![image](https://github.com/qd-today/qd/assets/50989379/931e2af6-f6fc-44a3-bb9e-86c4d820863c)

### Describe the Bug

配置好outlook邮箱之后无法发送邮件

### QD config

```shell
- MAIL_SMTP=smtp-mail.outlook.com
      - MAIL_PORT=587
      - MAIL_SSL=True
      - MAIL_STARTTLS=True
      - MAIL_USER=XXX@outlook.com
      - MAIL_PASSWORD=XXX
```

### QD log

```shell
[I 240325 13:43:54 QD.Web.Handler login:266] password reset: userid=5 email=XXXXX@qq.com
[I 240325 13:43:54 QD.Http.Util utils:454] send mail to XXXXX@qq.com
[E 240325 13:43:54 QD.Http.Util utils:481] send mail error: SMTP AUTH extension not supported by server.
```

### Expected behavior

可以用outlook邮箱发送邮件

### Screenshots

![image](https://github.com/qd-today/qd/assets/50989379/0f2e11c4-2239-4e35-afc9-d2c39e61e3ad)
![image](https://github.com/qd-today/qd/assets/50989379/931e2af6-f6fc-44a3-bb9e-86c4d820863c)

**Comment by a76yyyy** [comment]
duplicate qd-today/qd#424，fixed by https://github.com/qd-today/qd/commit/f11784544ed7319ed94b0f0b29a0c4aee3a6933e

**Comment by MuggleTan** [comment]
https://github.com/qd-today/qd/issues/424#issuecomment-1937117862
用这位大佬的测试代码是可以发送邮件的，但是配到QD里面就不行了，很奇怪，我把SSL关掉只用starttls也不行

**Comment by a76yyyy** [comment]
> https://github.com/qd-today/qd/issues/424#issuecomment-1937117862
> 用这位大佬的测试代码是可以发送邮件的，但是配到QD里面就不行了，很奇怪，我把SSL关掉只用starttls也不行

更新至dev版本了么

**Comment by MuggleTan** [comment]
开发版没问题了，我还以为已经更新到latest版本了
