### ISSUE TITLE
关于bark app推送签到内容详情问题

### ISSUE THREAD

**Issue by hecarli555** [qd-today/qd#52]
经过昨晚定时签到测试后，bark app的推动还是没有详细内容，附上2张图片，图1是签到框架的日志文件，图2是bark的推送内容
![image](https://user-images.githubusercontent.com/76683744/103987819-08548d00-51c8-11eb-88af-425e80eca3fe.png)
![image](https://user-images.githubusercontent.com/76683744/103987847-11455e80-51c8-11eb-8dee-90130b1ea92f.png)

**Comment by asdaragon** [comment]
想起来了，因为BARK使用的GET请求，日志这种富文本会显示不了，0107已经修改成POST，可以带日志

**Comment by hecarli555** [comment]
> 想起来了，因为BARK使用的GET请求，日志这种富文本会显示不了，0107已经修改成POST，可以带日志

docker平台上的版本更新过了，但是版本还是1222的。。。。

**Comment by asdaragon** [comment]
已经更新镜像
