### ISSUE TITLE
签到有302跳转的无法显示跳转后的页面

### ISSUE THREAD

**Issue by Ovler-Young** [qd-today/qd#53]
部分网站的签到在发送请求后会跳302转到新页面，这种的该如何处理。
![image](https://user-images.githubusercontent.com/44089074/103987817-07bbf680-51c8-11eb-887e-33f47a9c088c.png)
签到的成功与否是在跳转后的页面里，这种这么处理

**Comment by asdaragon** [comment]
下一个请求使用这个跳转链接不就行了
