### ISSUE TITLE
[Feature] Add ICP Filing Number Display Function 添加ICP备案号展示功能

### ISSUE THREAD

**Issue by aUsernameWoW** [qd-today/qd#535]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QD 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QD 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

Currently, the QD framework does not have the functionality to display the ICP filing number for websites. This feature would be highly beneficial for users who need to comply with regulatory requirements.

目前，QD框架没有展示网站ICP备案号的功能。对于需要遵守监管要求的用户来说，这个功能非常有用。

### Describe the solution

1. Configuration File: Add a new optional field in the configuration file where users can input their ICP filing number.
2. UI Update: Update the user interface to display the ICP filing number in a designated area. I suggest that the ICP filing number should be displayed everywhere, even if the user is not logged in. In addition, when the user clicks the filing number, it should redirect to https://beian.miit.gov.cn/.
</ol>

1. 配置文件: 在配置文件中添加一个新的可选字段，用户可以在其中输入他们的ICP备案号。
2. UI更新: 更新用户界面，在指定区域显示ICP备案号。我建议ICP备案号应在所有页面显示，即使用户未登录。此外，当用户点击备案号时，应跳转至https://beian.miit.gov.cn/。

### Describe alternatives

Not yet :(

暂无😭

### Additional context

Discussion regarding this feature request can be found [here](https://github.com/orgs/qd-today/discussions/533).

请从[此处](https://github.com/orgs/qd-today/discussions/533)访问关于此功能请求的讨论。

**Comment by a76yyyy** [comment]
当前框架代码框架重构中, 暂不添加新的 Features, 重构完成后重新展开 Feature 优先级评估和开发
