### ISSUE TITLE
[Bug] 公共仓库更新1005错误

### ISSUE THREAD

**Issue by xzdbadboy** [qd-today/qd#537]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

qdtoday/qd:dev

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

多次重新构建试了还是这样

### Describe the Bug

1、群晖设置的反代，配置了WebSocket。
2、通过`ip:port`的方式更新仓库跳1005错误，然后自动刷新成如下图2
3、通过`domain:port`的方式更新仓库跳1005错误，然后如图3

### QD config

```shell
version: "3"

services:
  qd:
    # image: qdtoday/qd:20240210
    # image: qdtoday/qd:lite-latest # 精简版
    image: qdtoday/qd:dev # 开发版
    container_name: qd
    depends_on:
      - redis
    ports:
      - "8923:80"
    volumes:
      - "/volume1/docker/qiandao/config:/usr/src/app/config"
    environment:
      - QD_DEBUG=True
      # - BIND=0.0.0.0
      # - PORT=80
      # - MULTI_PROCESS=False
      # - AUTO_RELOAD=False
      # - GZIP=True
      # - ACCESS_LOG=True
      # - DISPLAY_IMPORT_WARNING=True
      # - USER0ISADMIN=True
      # - STATIC_URL_PREFIX=/static/
      - DOMAIN=www.***.top:2082   # 该行注释与不注释都报同样的错误
      # - COOKIE_DAY=5
      # - COOKIE_SECURE_MODE=False
      - COOKIE_SECRET=binux
      - PBKDF2_ITERATIONS=400
      - AES_KEY=binux
      # - DB_TYPE=sqlite3
      # - JAWSDB_MARIA_URL=mysql://user:pass@localhost:3306/dbname?auth_plugin=
      # - QD_SQL_LOGGING_NAME=QD.sql
      # - QD_SQL_LOGGING_LEVEL=WARNING
      # - QD_SQL_POOL_LOGGING_NAME=QD.sql.pool
      # - QD_SQL_POOL_LOGGING_LEVEL=WARNING
      # - QD_SQL_POOL_SIZE=5
      # - QD_SQL_MAX_OVERFLOW=10
      # - QD_SQL_POOL_PRE_PING=True
      # - QD_SQL_POOL_RECYCLE=3600
      # - QD_SQL_POOL_TIMEOUT=30
      # - QD_SQL_POOL_USE_LIFO=True
      - REDISCLOUD_URL=redis://redis:6379
      # - REDIS_DB_INDEX=1
      # - QD_EVIL=1000
      # - EVIL_PASS_LAN_IP=True
      # - WORKER_METHOD=Queue
      # - QUEUE_NUM=50
      # - CHECK_TASK_LOOP=500
      # - TASK_MAX_RETRY_COUNT=8
      # - NEW_TASK_DELAY=1
      # - TASK_WHILE_LOOP_TIMEOUT=900
      # - TASK_REQUEST_LIMIT=1500
      # - DOWNLOAD_SIZE_LIMIT=5242880
      # - REQUEST_TIMEOUT=30.0
      # - CONNECT_TIMEOUT=30.0
      # - DELAY_MAX_TIMEOUT=29.9
      # - UNSAFE_EVAL_TIMEOUT=3.0
      # - USE_PYCURL=True
      # - ALLOW_RETRY=True
      # - DNS_SERVER=
      # - CURL_ENCODING=True
      # - CURL_CONTENT_LENGTH=True
      # - NOT_RETRY_CODE=301|302|303|304|305|307|400|401|403|404|405|407|408|409|410|412|415|413|414|500|501|502|503|504|599
      # - EMPTY_RETRY=True
      # - TRACEBACK_PRINT=False
      # - PUSH_PIC_URL=https://gitee.com/qd-today/qd/raw/master/web/static/img/push_pic.png
      # - PUSH_BATCH_SW=True
      # - PUSH_BATCH_DELTA=60
      # - WS_PING_INTERVAL=5
      # - WS_PING_TIMEOUT=30
      # - WS_MAX_MESSAGE_SIZE=10485760
      # - WS_MAX_QUEUE_SIZE=100
      # - WS_MAX_CONNECTIONS_SUBSCRIBE=30
      # - SUBSCRIBE_ACCELERATE_URL=jsdelivr_cdn
      # - PROXIES=
      # - PROXY_DIRECT_MODE=regexp
      # - PROXY_DIRECT=(?xi)\A([a-z][a-z0-9+\-.]*://)?(0(.0){3}|127(.0){2}.1|localhost|\[::([\d]+)?\])(:[0-9]+)?
      # - NOTEPAD_LIMIT=20
      # - EXTRA_ONNX_NAME=
      # - EXTRA_CHARSETS_NAME=
      # - MAIL_SMTP=
      # - MAIL_PORT=465
      # - MAIL_SSL=True
      # - MAIL_STARTTLS=False
      # - MAIL_USER=
      # - MAIL_PASSWORD=
      # - MAIL_FROM=${MAIL_USER}
      # - MAIL_DOMAIN_HTTPS=False
      # - MAILGUN_KEY=
      # - MAILGUN_DOMAIN=${DOMAIN}
      # - GA_KEY=

  redis:
    image: redis:alpine
    container_name: redis
    command: ["--loglevel warning"]
    # command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - /volume1/docker/qiandao-redis/data:/data:rw
```

### QD log

```shell
stream	content
stdout	[I 240614 10:17:34 tornado.access web:2348] 200 GET /subscribe/1/ (172.19.0.1) 15.12ms
stdout	[I 240614 10:17:33 tornado.access web:2348] 101 GET /subscribe/1/updating/ (172.19.0.1) 0.90ms
stdout	[D 240614 10:17:33 QD.Web.Handler subscribe:63] check_origin: 群晖IP:8923, host: 群晖IP:8923
stdout	    TimeoutError
stdout	        raise asyncio.TimeoutError from None
stdout	      File "/usr/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__
stdout	        with timer:
stdout	      File "/usr/lib/python3.11/site-packages/aiohttp/client.py", line 504, in _request
stdout	                     ^^^^^^^^^^^^^^^^
stdout	        self._resp = await self._coro
stdout	      File "/usr/lib/python3.11/site-packages/aiohttp/client.py", line 1194, in __aenter__
stdout	        async with session.get(hfile_link, verify_ssl=False, timeout=config.request_timeout, proxy=proxy) as res:
stdout	      File "/usr/src/app/web/handlers/subscribe.py", line 112, in update
stdout	    Traceback (most recent call last):
stdout	[E 240614 10:17:32 QD.Web.Handler subscribe:176] UserID: 1 update Subscribe failed! Reason: TimeoutError
stdout	[I 240614 10:17:01 tornado.access web:2348] 101 GET /subscribe/1/updating/ (172.19.0.1) 1.04ms
stdout	[D 240614 10:17:01 QD.Web.Handler subscribe:63] check_origin: 群晖IP:8923, host: 群晖IP:8923
stdout	[I 240614 10:17:01 tornado.access web:2348] 200 GET /subscribe/1/ (172.19.0.1) 25.96ms
stdout	[I 240614 10:17:01 tornado.access web:2348] 302 POST /subscribe/refresh/1/?op=refresh (172.19.0.1) 26.72ms
stdout	[I 240614 10:17:00 tornado.access web:2348] 304 GET /subscribe/1/ (172.19.0.1) 15.18ms
stdout	[I 240614 10:16:59 tornado.access web:2348] 304 GET /subscribe/1/ (172.19.0.1) 83.42ms
```

### Expected behavior

仓库能正常更新使用

### Screenshots

![微信图片_20240614104338](https://github.com/qd-today/qd/assets/30276489/2cd29046-f405-4a25-8700-efcf0721ddda)
![2](https://github.com/qd-today/qd/assets/30276489/54d76d6c-8a83-4f5b-a52a-733e9c77f131)
![3](https://github.com/qd-today/qd/assets/30276489/3692b311-c0d2-4b9e-b105-8f68b9561ef1)

**Comment by xzdbadboy** [comment]
重新安装了Python 3.11之后后台日志如下，但是错误还是跟之前一样

date | stream | content
2024/06/14 11:09:01 | stdout | [I 240614 11:09:01 tornado.access web:2348] 200 GET /subscribe/1/ (172.19.0.1) 11.17ms
2024/06/14 11:09:00 | stdout | [I 240614 11:09:00 tornado.access web:2348] 101 GET /subscribe/1/updating/ (172.19.0.1) 1.04ms
2024/06/14 11:08:59 | stdout | [E 240614 11:08:59 QD.Web.Handler subscribe:176] UserID: 1 update Subscribe failed! Reason: TimeoutError
2024/06/14 11:08:29 | stdout | [I 240614 11:08:29 tornado.access web:2348] 101 GET /subscribe/1/updating/ (172.19.0.1) 1.12ms
2024/06/14 11:08:29 | stdout | [I 240614 11:08:29 tornado.access web:2348] 200 GET /subscribe/1/ (172.19.0.1) 21.68ms
2024/06/14 11:08:29 | stdout | [I 240614 11:08:29 tornado.access web:2348] 302 POST /subscribe/refresh/1/?op=refresh (172.19.0.1) 83.03ms
2024/06/14 11:08:27 | stdout | [I 240614 11:08:27 tornado.access web:2348] 304 GET /subscribe/1/ (172.19.0.1) 9.39ms
2024/06/14 11:08:27 | stdout | [I 240614 11:08:27 tornado.access web:2348] 200 GET /static/img/icon.png?v=ac6331c027f3f1f1006c59f57df8b214176fd5dedbe69f681285cd2a294d4a1130e9389b236011a959764c92efd477e673fd5accb8d3dece91cf95b376eb7df4 (172.19.0.1) 1.03ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/Font-Awesome/webfonts/fa-solid-900.woff2 (172.19.0.1) 31.25ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/img/body.jpg (172.19.0.1) 17.23ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/img/header.jpg (172.19.0.1) 16.75ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff (172.19.0.1) 16.01ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/mutil_op.js?v=3e86750fd1d265d0c2ff3e8fe4c341fcfb3e10a5e012f49f0e4908e23a066b09ddd7fd1b0c563f5dd3cb53f2935aeb6530f54f5f562c4f1631e9e821e109e27c (172.19.0.1) 27.45ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/lunar-javascript/lunar.js?v=1ef4867dd8bcbc8a6505cedc361c63d47addb1f6ac368408f644637a4c04cb99f1d6e160488ddcd2e3ddf062af090d7601e7f1939c66ac4b30626fb6e8249396 (172.19.0.1) 26.33ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/clipboard/dist/clipboard.min.js?v=ecee695e9734a0246bc64f1151f0d81609f49ced6dfa32ee20e41d38c469e003c1eee678bd28eca73a79cba603b43b385735124db5b304567f2ca2619f214e2b (172.19.0.1) 5.14ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/blueimp-md5/js/md5.js?v=3697eb404833384c52d40c7c7e32132ab80114af3b9596c19af59d664e2cba2082e2db073eb4c2b2e960200ed9ffe09e5a10e910ffdfdfa98d5a06570cab5300 (172.19.0.1) 4.60ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/jquery.tablesorter/dist/js/jquery.tablesorter.widgets.min.js?v=763ffd2b919120466ef88826f6d0b5e973ce4f3d1174f93d146c5f6714a159feb9249354d938db1251a3b8ea37121c002513e1271c042796fefceba8f95a9975 (172.19.0.1) 4.62ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/misc.js?v=c3b830413637aa4a24640c88fe4462860edc5d7fb15d0633e133a9b74d95b5b21c16e01387b52f88c593b07e41fe912761c620e4c7f04e2fed4ded871541f872 (172.19.0.1) 4.45ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/nprogress/nprogress.js?v=fc2cdc3cb3aa52775324a95627e3e4bc587611346d92b9f1c2650bafd2ec514f9c14b97b4c0391e60c300fc0d12efb4ce21e647bf19092796a41b5ae4fd04a74 (172.19.0.1) 3.60ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/bootstrap/dist/js/bootstrap.min.js?v=3f1b46e9ea0fb6be507605a2783af406c6b4f885dedaa4401bff204b0fe9056656717411021594e2512e98a4e398e3238267a7deafeba1b57e443decab0477ea (172.19.0.1) 2.71ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/select2/dist/js/select2.full.min.js?v=65ab44d85b09e8f383f00c298239a1ae944b9b452dea7e450889dfa4a1aee11861b380d51ff5551b56b526f86f14f856becf1537d1afc005e0c09a3d3e2b5090 (172.19.0.1) 13.64ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/jquery/dist/jquery.min.js?v=de027062931edd07b01842eff24fc15fdbdcaa1af245dcd133155faba9e0c965f0a34dc6144ce3b149bc43b4597073c792cb6dabbfc6168c63095523923bcf77 (172.19.0.1) 9.17ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/jquery.tablesorter/dist/js/jquery.tablesorter.min.js?v=ab381de5c61265ca2caa9ce99fbcc5d9921df1fffc087985299f23ee65383945d335177983e64704fb20284c28ab10ad750bc4c44e4ba6bc303c082889c82e36 (172.19.0.1) 4.27ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/css/my.css?v=f03b49dfa00295685d9a9436d498608bce24526e0a0cdd58f0a41795346722c348da8a3a144dd2ee44ea59b27bded197e328faebf1f07bd4671212f3314a110b (172.19.0.1) 1.50ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/Font-Awesome/css/all.min.css?v=89e71d2e66ac925ec2564aa45cd43f647fd72e5bd664e2728fb632eed71e9e6a43d72a404a8ce9993fc4d223ed985201e3a66676d01cf5e341bc7d07fd9a6207 (172.19.0.1) 5.38ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/css/base.css?v=7a308851c611db7709f298432da16f6ad7694b7539dc8aeef03aae55adb064a9c569c32e013508236c5716caeb354da6f4c6f8c485c891358cc355b1d26de0c1 (172.19.0.1) 5.11ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/seajs/dist/sea.js?v=9aa0c0ac1ef4607ada5ebd1e7c3118ad06ad06f91a261296be907ec8fa057ea1e81ff754bb2841979a0e4ae5ab410e0f7be7705feb86a108e84784a2f7660ea6 (172.19.0.1) 4.63ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/jquery.tablesorter/css/theme.bootstrap_3.css?v=4401edef542ea392d36d224ef9e3fa4754e6251625e1c0d4cdd4c65d147df2516190f95d9a1e00f575ed5c9b98df6483047bc18b3ae5b0af81c3a7a4d70b80ce (172.19.0.1) 3.74ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/select2/dist/css/select2.min.css?v=9cc365a6e6833ebaa5125b37217fd0e7a1f7eaabc1012c1bde2a6ea373317966ec401d7cf35a31d1c46fed43d380196b8aaa329eddf92a313080651e51720f9f (172.19.0.1) 3.17ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/nprogress/nprogress.css?v=0da9dfc5605ab10b6af91b643401034dd5f843a04f08943f91ec62fd17ed70fd01700e0d2093d28bb8b7d5597e625e4e09f81991d2660aacfe6f24ce20845ba1 (172.19.0.1) 2.60ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /static/components/bootstrap/dist/css/bootstrap.min.css?v=ef14562e5768b4786d9d072b0b8e3268c511b3770c1f1829adc9afb6f7d98f0165d5b2bf19a82b55b50f6390d8ee844cb4954f1d47c7ab1d11497d4fa7618309 (172.19.0.1) 6.31ms
2024/06/14 11:08:26 | stdout | [I 240614 11:08:26 tornado.access web:2348] 200 GET /my/ (172.19.0.1) 14.71ms
2024/06/14 11:08:23 | stdout | [I 240614 11:08:23 tornado.access web:2348] 304 GET /my/ (172.19.0.1) 158.72ms
2024/06/14 11:08:23 | stdout | [I 240614 11:08:23 tornado.access web:2348] 304 GET /subscribe/1/ (172.19.0.1) 100.36ms
2024/06/14 11:08:12 | stdout | [I 240614 11:08:12 QD.Run run:87] Http Server started on 0.0.0.0:80
2024/06/14 11:08:12 | stdout | [I 240614 11:08:12 QD.Worker worker:329] Queue Worker start...
2024/06/14 11:08:10 | stderr | get_mempolicy: Function not implemented

**Comment by a76yyyy** [comment]
> ### QD log
> 
> ```shell
> stream	content
> stdout	[I 240614 10:17:34 tornado.access web:2348] 200 GET /subscribe/1/ (172.19.0.1) 15.12ms
> stdout	[I 240614 10:17:33 tornado.access web:2348] 101 GET /subscribe/1/updating/ (172.19.0.1) 0.90ms
> stdout	[D 240614 10:17:33 QD.Web.Handler subscribe:63] check_origin: 群晖IP:8923, host: 群晖IP:8923
> stdout	    TimeoutError
> stdout	        raise asyncio.TimeoutError from None
> stdout	      File "/usr/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__
> stdout	        with timer:
> stdout	      File "/usr/lib/python3.11/site-packages/aiohttp/client.py", line 504, in _request
> stdout	                     ^^^^^^^^^^^^^^^^
> stdout	        self._resp = await self._coro
> stdout	      File "/usr/lib/python3.11/site-packages/aiohttp/client.py", line 1194, in __aenter__
> stdout	        async with session.get(hfile_link, verify_ssl=False, timeout=config.request_timeout, proxy=proxy) as res:
> stdout	      File "/usr/src/app/web/handlers/subscribe.py", line 112, in update
> stdout	    Traceback (most recent call last):
> stdout	[E 240614 10:17:32 QD.Web.Handler subscribe:176] UserID: 1 update Subscribe failed! Reason: TimeoutError
> stdout	[I 240614 10:17:01 tornado.access web:2348] 101 GET /subscribe/1/updating/ (172.19.0.1) 1.04ms
> stdout	[D 240614 10:17:01 QD.Web.Handler subscribe:63] check_origin: 群晖IP:8923, host: 群晖IP:8923
> stdout	[I 240614 10:17:01 tornado.access web:2348] 200 GET /subscribe/1/ (172.19.0.1) 25.96ms
> stdout	[I 240614 10:17:01 tornado.access web:2348] 302 POST /subscribe/refresh/1/?op=refresh (172.19.0.1) 26.72ms
> stdout	[I 240614 10:17:00 tornado.access web:2348] 304 GET /subscribe/1/ (172.19.0.1) 15.18ms
> stdout	[I 240614 10:16:59 tornado.access web:2348] 304 GET /subscribe/1/ (172.19.0.1) 83.42ms
> ```

这里显示是timeouterror超时了

**Comment by xzdbadboy** [comment]
> > ### QD log
> > ```shell
> > stream	content
> > stdout	[I 240614 10:17:34 tornado.access web:2348] 200 GET /subscribe/1/ (172.19.0.1) 15.12ms
> > stdout	[I 240614 10:17:33 tornado.access web:2348] 101 GET /subscribe/1/updating/ (172.19.0.1) 0.90ms
> > stdout	[D 240614 10:17:33 QD.Web.Handler subscribe:63] check_origin: 群晖IP:8923, host: 群晖IP:8923
> > stdout	    TimeoutError
> > stdout	        raise asyncio.TimeoutError from None
> > stdout	      File "/usr/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__
> > stdout	        with timer:
> > stdout	      File "/usr/lib/python3.11/site-packages/aiohttp/client.py", line 504, in _request
> > stdout	                     ^^^^^^^^^^^^^^^^
> > stdout	        self._resp = await self._coro
> > stdout	      File "/usr/lib/python3.11/site-packages/aiohttp/client.py", line 1194, in __aenter__
> > stdout	        async with session.get(hfile_link, verify_ssl=False, timeout=config.request_timeout, proxy=proxy) as res:
> > stdout	      File "/usr/src/app/web/handlers/subscribe.py", line 112, in update
> > stdout	    Traceback (most recent call last):
> > stdout	[E 240614 10:17:32 QD.Web.Handler subscribe:176] UserID: 1 update Subscribe failed! Reason: TimeoutError
> > stdout	[I 240614 10:17:01 tornado.access web:2348] 101 GET /subscribe/1/updating/ (172.19.0.1) 1.04ms
> > stdout	[D 240614 10:17:01 QD.Web.Handler subscribe:63] check_origin: 群晖IP:8923, host: 群晖IP:8923
> > stdout	[I 240614 10:17:01 tornado.access web:2348] 200 GET /subscribe/1/ (172.19.0.1) 25.96ms
> > stdout	[I 240614 10:17:01 tornado.access web:2348] 302 POST /subscribe/refresh/1/?op=refresh (172.19.0.1) 26.72ms
> > stdout	[I 240614 10:17:00 tornado.access web:2348] 304 GET /subscribe/1/ (172.19.0.1) 15.18ms
> > stdout	[I 240614 10:16:59 tornado.access web:2348] 304 GET /subscribe/1/ (172.19.0.1) 83.42ms
> > ```
> 
> 这里显示是timeouterror超时了

但是家里面网络都是通的。
网络环境是：路由器+Mac的surge做得网关，surge开了 HTTP&SOCKS5代理，没有接管群晖，但是群晖里面设置的是通过代理服务器连接，但是对于本底值不适用代理服务器

**Comment by a76yyyy** [comment]
> > > ### QD log
> > > ```shell
> > > stream	content
> > > stdout	[I 240614 10:17:34 tornado.access web:2348] 200 GET /subscribe/1/ (172.19.0.1) 15.12ms
> > > stdout	[I 240614 10:17:33 tornado.access web:2348] 101 GET /subscribe/1/updating/ (172.19.0.1) 0.90ms
> > > stdout	[D 240614 10:17:33 QD.Web.Handler subscribe:63] check_origin: 群晖IP:8923, host: 群晖IP:8923
> > > stdout	    TimeoutError
> > > stdout	        raise asyncio.TimeoutError from None
> > > stdout	      File "/usr/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__
> > > stdout	        with timer:
> > > stdout	      File "/usr/lib/python3.11/site-packages/aiohttp/client.py", line 504, in _request
> > > stdout	                     ^^^^^^^^^^^^^^^^
> > > stdout	        self._resp = await self._coro
> > > stdout	      File "/usr/lib/python3.11/site-packages/aiohttp/client.py", line 1194, in __aenter__
> > > stdout	        async with session.get(hfile_link, verify_ssl=False, timeout=config.request_timeout, proxy=proxy) as res:
> > > stdout	      File "/usr/src/app/web/handlers/subscribe.py", line 112, in update
> > > stdout	    Traceback (most recent call last):
> > > stdout	[E 240614 10:17:32 QD.Web.Handler subscribe:176] UserID: 1 update Subscribe failed! Reason: TimeoutError
> > > stdout	[I 240614 10:17:01 tornado.access web:2348] 101 GET /subscribe/1/updating/ (172.19.0.1) 1.04ms
> > > stdout	[D 240614 10:17:01 QD.Web.Handler subscribe:63] check_origin: 群晖IP:8923, host: 群晖IP:8923
> > > stdout	[I 240614 10:17:01 tornado.access web:2348] 200 GET /subscribe/1/ (172.19.0.1) 25.96ms
> > > stdout	[I 240614 10:17:01 tornado.access web:2348] 302 POST /subscribe/refresh/1/?op=refresh (172.19.0.1) 26.72ms
> > > stdout	[I 240614 10:17:00 tornado.access web:2348] 304 GET /subscribe/1/ (172.19.0.1) 15.18ms
> > > stdout	[I 240614 10:16:59 tornado.access web:2348] 304 GET /subscribe/1/ (172.19.0.1) 83.42ms
> > > ```
> > 
> > 
> > 这里显示是timeouterror超时了
> 
> 但是家里面网络都是通的。 网络环境是：路由器+Mac的surge做得网关，surge开了 HTTP&SOCKS5代理，没有接管群晖，但是群晖里面设置的是通过代理服务器连接，但是对于本底值不适用代理服务器

可以参考这里

https://github.com/qd-today/qd/blob/cac1aaadd75a7ee24e7a7603ec7bbe5d314859f2/config.py#L146-L150

配置框架容器环境变量如下:

```
SUBSCRIBE_ACCELERATE_URL=https://mirror.ghproxy.com/https://raw.githubusercontent.com/
```

**Comment by xzdbadboy** [comment]
> https://raw.githubusercontent.com/

添加了这个环境变量，这个问题解决了！感谢大佬！

**Comment by yinhanghang** [comment]
???
我也出现这个问题了
yaml文件中添加了环境变量
    environment:
      - PORT=80
      - SUBSCRIBE_ACCELERATE_URL=https://ghfast.top/https://raw.githubusercontent.com/
     注册仓库
https://ghfast.top/https://github.com/qd-today/templates
master
不加速
但是还是更新不了

**Comment by yinhanghang** [comment]
> ??? 我也出现这个问题了 yaml文件中添加了环境变量 environment:  环境： - PORT=80  - 端口 = 80 - SUBSCRIBE_ACCELERATE_URL=https://ghfast.top/https://raw.githubusercontent.com/ 注册仓库 https://ghfast.top/https://github.com/qd-today/templates master  主人 不加速 但是还是更新不了

解决了，添加  - SUBSCRIBE_ACCELERATE_URL= 网上找的github加速地址/https://raw.githubusercontent.com/
官网里给的那个加速链接不能用，直接百度找了一个

**Comment by dongjinl** [comment]
@yinhanghang 除了添加环境变量SUBSCRIBE_ACCELERATE_URL外，还要修改注册仓库么？

**Comment by dongjinl** [comment]
> [@yinhanghang](https://github.com/yinhanghang) 除了添加环境变量SUBSCRIBE_ACCELERATE_URL外，还要修改注册仓库么？

原来还要把注册仓库的加速勾选上
