### ISSUE TITLE
1222开始启动报错

### ISSUE THREAD

**Issue by ixmu** [qd-today/qd#54]
使用mysql数据库，测试1204正常，1222开始报错
![QQ截图20210108172421.png](https://i.loli.net/2021/01/08/3SFernXZc4d89am.png)

**Comment by asdaragon** [comment]
重启一下docker

**Comment by ixmu** [comment]
不是docker，debian9+python2.7+mysql+nginx

**Comment by AragonSnow** [comment]
执行 ALTER TABLE `site` ADD `logDay`  INT UNSIGNED NOT NULL DEFAULT 365

**Comment by asdaragon** [comment]
执行
```ALTER TABLE `site` ADD `logDay`  INT UNSIGNED NOT NULL DEFAULT 365```

**Comment by ixmu** [comment]
完美解决
