### ISSUE TITLE
[Bug] 为什么过几天就要重新登录账户密码？非常不方便，不能一直保持吗

### ISSUE THREAD

**Issue by wzgrx** [qd-today/qd#548]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

2024

### Bug on OS

Windows, Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

[Bug] 为什么过几天就要重新登录账户密码？非常不方便，不能一直保持吗

### Describe the Bug

[Bug] 为什么过几天就要重新登录账户密码？非常不方便，不能一直保持吗

### QD log

```shell
wu
```

### Expected behavior

wu

**Comment by Yuukiy** [comment]
从配置文件来猜测，可以给docker设置环境变量来设置登录有效期（默认的应该是5天）
`COOKIE_DAY=90`

**Comment by crossgg** [comment]
cookie默认是5天，可以自行通过环境变量设置COOKIE_DAY为需要保存的天数，

更多设置请参考
https://github.com/qd-today/qd/issues/547#issuecomment-2367684446
