### ISSUE TITLE
[Bug] 添加第三方库后无法删除及编辑

### ISSUE THREAD

**Issue by Volundio** [qd-today/qd#554]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20240210

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

添加了错误的第三方库信息后，无法进一步编辑或修改或删除已添加的错误第三方库
![QQ_1730119037727](https://github.com/user-attachments/assets/89e20156-7d2f-471b-bdaa-2a2754112e97)

### Describe the Bug

无法进一步编辑或修改或删除已添加的错误第三方库

### QD log

```shell
无法进一步编辑或修改或删除已添加的错误第三方库
```

### Expected behavior

添加错误的第三方库后可以编辑或删除

### Screenshots

![QQ_1730119072185](https://github.com/user-attachments/assets/ef094da9-34fc-4630-b1e5-c3750c6f7aff)

**Comment by a76yyyy** [comment]
只有管理员账号有权限编辑，你这个是管理员账号么？

**Comment by Volundio** [comment]
> Contributor

是的，我这总共就一个用户
![QQ_1730218428970](https://github.com/user-attachments/assets/ce99e5a2-e198-4f03-8882-1f81397f8346)

**Comment by a76yyyy** [comment]
> > Contributor
> 
> 是的，我这总共就一个用户
> ![QQ_1730218428970](https://github.com/user-attachments/assets/ce99e5a2-e198-4f03-8882-1f81397f8346)
> 

重新登陆框架或者重启容器试试

**Comment by Volundio** [comment]
> > > Contributor
> > 
> > 
> > 是的，我这总共就一个用户
> > ![QQ_1730218428970](https://private-user-images.githubusercontent.com/37572185/381214394-ce99e5a2-e198-4f03-8882-1f81397f8346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MjUxMjAsIm5iZiI6MTczMDYyNDgyMCwicGF0aCI6Ii8zNzU3MjE4NS8zODEyMTQzOTQtY2U5OWU1YTItZTE5OC00ZjAzLTg4ODItMWY4MTM5N2Y4MzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDA5MDcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YmQ2YjRmNjdlM2YzNDFkMWIzNmMxOGRjN2I4ZmQxMzUzZmYzYzZjYmZmMWRjNjE2YmM3NTNlZmE3Nzc5YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rEzuuP2dhgEBSvf0aJ_jeoy6xK3ki_H01pmLZkg6LNw)
> 
> 重新登陆框架或者重启容器试试

清cookie登出框架重新登录后问题解决
