### ISSUE TITLE
请问如何修改管理员密码?

### ISSUE THREAD

**Issue by fyngd** [qd-today/qd#56]
私有签到框架 20210107

**Comment by asdaragon** [comment]
@fyngd 
方法1：
配置邮箱，点忘记密码，点击链接重置密码
方法2：
新建一个用户，使用你要使用的密码。导出database.db,使用SQLite Expert Personal 5直接在数据库修改密码

**Comment by fyngd** [comment]
> @fyngd
> 方法1：
> 配置邮箱，点忘记密码，点击链接重置密码
> 方法2：
> 新建一个用户，使用你要使用的密码。导出database.db,使用SQLite Expert Personal 5直接在数据库修改密码

方法1：提示：如果用户存在，会将发送密码重置邮件到您的邮箱，请注意查收。（如果您没有收到过激活邮件，可能无法也无法收到密码重置邮件）

**Comment by asdaragon** [comment]
你配置了邮箱就能收到邮件

**Comment by fyngd** [comment]
> 你配置了邮箱就能收到邮件

昨晚到现在都收不到，我163的邮箱。

**Comment by asdaragon** [comment]
配置邮箱
```
docker run -d --name qiandao -p 12345:80 -v $(pwd)/qiandao/config:/usr/src/app/config --env MAIL_SMTP=STMP服务器 --env MAIL_PORT=邮箱服务器端口 --env MAIL_USER=用户名 --env MAIL_PASSWORD=密码 --env MAIL_PASSWORD=密码 --env DOMAIN=域名 asdaragon/qiandao
```

**Comment by Luxuslaerm** [comment]
> @fyngd
> 方法1：
> 配置邮箱，点忘记密码，点击链接重置密码
> 方法2：
> 新建一个用户，使用你要使用的密码。导出database.db,使用SQLite Expert Personal 5直接在数据库修改密码

小白又学会一项技能用SQLite Expert修改数据库，搞了半天发现是自己注册邮箱把qq.com打错成qqc.om，怪不得死活登录不进去了

**Comment by asdaragon** [comment]
@fyngd 0122已经添加了管理员修改密码的功能

**Comment by fyngd** [comment]
> @fyngd 0122已经添加了管理员修改密码的功能

谢谢！已经更新，请问如何验证管理员邮箱？

**Comment by if1y** [comment]
今天尝试修改密码，提交修改后报错 `管理员邮箱/密码错误`，反复尝试无果。 @AragonSnow

**Comment by asdaragon** [comment]
@if1y 那就是密码错误了呗。20210222更换成md5验证，需要注销重新登录一次生成md5密码。20210122之前的是明文密码验证

**Comment by if1y** [comment]
> @if1y 那就是密码错误了呗。20210222更换成md5验证，需要注销重新登录一次生成md5密码。20210122之前的是明文密码验证

验证密码确认是无误的。估计是验证模式更改导致的，我通过配置smtp解决了。
