### ISSUE TITLE
备份后恢复数据提示 no JSON object cloud be decoded

### ISSUE THREAD

**Issue by loveqianool** [qd-today/qd#57]
![chrome_JbFFoR0hc7.png](https://cdn.jsdelivr.net/gh/sbough1/z/images/2021/01/18/bcf53a39e5126336299ee3c695b461b6.png)

**Comment by asdaragon** [comment]
@loveqianool 不支持直接恢复db文件，恢复的是点击备份后生成的json文件

**Comment by loveqianool** [comment]
![chrome_GknBaBTYqW.png](https://cdn.jsdelivr.net/gh/sbough1/z/images/2021/01/18/8299e1adfc4a2e4abef79596e6ba1aa9.png)
我点击备份出现这个，所以才会点击备份数据库。
docker hub 能实装一下十七号的更新吗？我想用企业微信推送。
谢谢你的工作。

**Comment by asdaragon** [comment]
permission denied 应该是你浏览器没有给写入权限之类的。
dockerhub 需要有人测试才能更新，着急的话可以通过以下命令更新：
```
docker exec -it 容器名 /bin/sh
git fetch --all
git reset --hard origin/master
exit
docker restart 容器名
```

**Comment by loveqianool** [comment]
我换了几个浏览器都是同样的报错。
可能是我 nginx 配置有问题，看到有几个三零四，算了不管了，能用就行，谢谢你。

**Comment by loveqianool** [comment]
刚刚进去手动更新发现没有权限才想到，
我执行 docker 都是使用非 root 运行的所以才报这个错误。
