### ISSUE TITLE
邮件发送中连接的http ssl

### ISSUE THREAD

**Issue by gkl1368** [qd-today/qd#58]
发送邮件里面的连接如何可以带https？

**Comment by asdaragon** [comment]
@gkl1368  环境变量 ENABLE_HTTPS=True

**Comment by gkl1368** [comment]
> @gkl1368 环境变量 ENABLE_HTTPS=True

已经设置了
![image](https://user-images.githubusercontent.com/12904884/104980156-e9b08a80-5a40-11eb-84ee-5b9902cf8124.png)

发送邮件还是这样
![image](https://user-images.githubusercontent.com/12904884/104980198-00ef7800-5a41-11eb-9ef7-909694f710b9.png)
![image](https://user-images.githubusercontent.com/12904884/104980212-06e55900-5a41-11eb-859b-945fc5a4b6ed.png)

**Comment by asdaragon** [comment]
好吧，原作者定死是http了，下一版修改。着急的话你直接强制http跳转https就行了

**Comment by gkl1368** [comment]
> 好吧，原作者定死是http了，下一版修改。着急的话你直接强制http跳转https就行了

好的 明白了。原来是原作者程序里写死http了，加了环境变量也无效。谢谢了。

**Comment by gkl1368** [comment]
> 好吧，原作者定死是http了，下一版修改。着急的话你直接强制http跳转https就行了

22号的版本这个问题解决了吗？

**Comment by asdaragon** [comment]
@gkl1368 改好了
