### ISSUE TITLE
docker 20210122 新建我的签到500

### ISSUE THREAD

**Issue by kayleyang** [qd-today/qd#63]
[E 210203 14:11:55 web:1591] Uncaught exception GET /task/new (172.16.187.220)
    HTTPServerRequest(protocol='http', host='172.16.162.211:12345', method='GET', uri='/task/new', version='HTTP/1.1', remote_ip='172.16.187.220', headers={'Accept-Language': 'zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7', 'Accept-Encoding': 'gzip, deflate', 'X-Requested-With':'XMLHttpRequest', 'Host': '172.16.162.211:12345', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://172.16.162.211:12345/my/', 'Cookie': '_ga=GA1.1.1472373559.1591753654; _xsrf=2|fd4ddc97|32b1861a66a357556e476bcc91577d45|1611200948; user="2|1:0|10:1612332710|4:user|64:hMQEcm9sZcDECG5pY2tuYW1lwMQCaWQBxAVlbWFpbLA2MjcxMzQwMDBAcXEuY29t|72ed1ffc913fcc1e8a24d84d474482c151c300d47bc8693d341459e5ffe774c3"'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1510, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/src/app/web/handlers/task.py", line 57, in get
        tplid = int(tplid)
    TypeError: int() argument must be a string or a number, not 'NoneType'
[E 210203 14:11:55 web:1591] Uncaught exception GET /task/new (172.16.187.220)
    HTTPServerRequest(protocol='http', host='172.16.162.211:12345', method='GET', uri='/task/new', version='HTTP/1.1', remote_ip='172.16.187.220', headers={'Accept-Language': 'zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7', 'Accept-Encoding': 'gzip, deflate', 'X-Requested-With':'XMLHttpRequest', 'Host': '172.16.162.211:12345', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://172.16.162.211:12345/my/', 'Cookie': '_ga=GA1.1.1472373559.1591753654; _xsrf=2|fd4ddc97|32b1861a66a357556e476bcc91577d45|1611200948; user="2|1:0|10:1612332710|4:user|64:hMQEcm9sZcDECG5pY2tuYW1lwMQCaWQBxAVlbWFpbLA2MjcxMzQwMDBAcXEuY29t|72ed1ffc913fcc1e8a24d84d474482c151c300d47bc8693d341459e5ffe774c3"'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1510, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/src/app/web/handlers/task.py", line 57, in get
        tplid = int(tplid)
    TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by asdaragon** [comment]
@kayleyang 没有模板直接创建任务？
