### ISSUE TITLE
没有注册功能 

### ISSUE THREAD

**Issue by huangcan5421** [qd-today/qd#65]
试了 最近几个版本  都没有的注册功能  注册页面 只有登录按钮。。。 201222版本才成功注册 。。。。

**Comment by asdaragon** [comment]
201222是什么版本

**Comment by huangcan5421** [comment]
> 201222是什么版本

docker tag 里面的版本号 201222是有注册功能的 是最近的几个版本没有；实际表现为注册页面 输入注册的账号密码后 没有注册按钮 而是一个登录 无法进行注册

**Comment by asdaragon** [comment]
那就用20210122呗

**Comment by huangcan5421** [comment]
> 那就用20210122呗

额... 我说的能注册的版本是20201222  
20210122并不能成功注册 然后去取tag号 依次提前一个版本 直到20201222才能注册 看更新历史貌似一月份改过登录bug 可能就是那里影响了

**Comment by asdaragon** [comment]
试了一下，2021注册并没有问题呀，点击注册后跳转到/register 本来就不会有注册按钮，这时候你直接输入账号密码登录不久行了

**Comment by huangcan5421** [comment]
> 试了一下，2021注册并没有问题呀，点击注册后跳转到/register 本来就不会有注册按钮，这时候你直接输入账号密码登录不久行了

输入后提示没有此账号密码  （大意非原文）

**Comment by huangcan5421** [comment]
。。。懂了 原来 register是多余的？   直接在 login页面 输入账号密码后能就注册 

我是新用户  进到登录页面 没有输账号密码（因为我还没有） 看到有注册就点注册 进入 register页面  但是 这个页面 只能登录  并不能注册 
然后就卡到这里 感觉 稍稍有点误导

总之现在已经注册成功了   感谢

**Comment by flysailor** [comment]
> 。。。懂了 原来 register是多余的？ 直接在 login页面 输入账号密码后能就注册
> 
> 我是新用户 进到登录页面 没有输账号密码（因为我还没有） 看到有注册就点注册 进入 register页面 但是 这个页面 只能登录 并不能注册
> 然后就卡到这里 感觉 稍稍有点误导
> 
> 总之现在已经注册成功了 感谢

原来是这样注册的，一塌糊涂，我也折腾了半天……

**Comment by asdaragon** [comment]
@huangcan5421 @flysailor  已经修复
