### ISSUE TITLE
无法签到，显示超时

### ISSUE THREAD

**Issue by justincnn** [qd-today/qd#67]
试了下好几个签到，都是这个问题：

failed at 1/2 request, error:HTTP 599: Timeout while connecting, http://music.163.com/api/point/dailyTask?type=0

http://192.168.68.88:12345/subscribe/这个链接打开非常的慢，要好几十秒，估计也是和上面同样的问题

docker的网络链接没有问题，因为其他容器都可以正常上网

**Comment by asdaragon** [comment]
@justincnn 试试这个启动命令
```
docker run -d --name qiandao -e PORT=12345 --net=host -v $(pwd)/qiandao/config:/usr/src/app/config asdaragon/qiandao
```

**Comment by Troray** [comment]
> @justincnn 试试这个启动命令
> 
> ```
> docker run -d --name qiandao -e PORT=12345 --net=host -v $(pwd)/qiandao/config:/usr/src/app/config asdaragon/qiandao
> ```

host模式创建后，提示如下
`failed at 1/4 request, , https://www.52pojie.cn/home.php?mod=task&do=apply&id=2`
只是不提示error:HTTP 599了。

**Comment by Ovler-Young** [comment]
> > @justincnn 试试这个启动命令
> > ```
> > docker run -d --name qiandao -e PORT=12345 --net=host -v $(pwd)/qiandao/config:/usr/src/app/config asdaragon/qiandao
> > ```
> 
> host 模式创建后，提示如下
> `failed at 1/4 request, , https://www.52pojie.cn/home.php?mod=task&do=apply&id=2`
> 只是不提示 error:HTTP 599 了。

52pojie的问题应该是不能重复签到的原因吧，去编辑模板那里测试一下看看网页返回内容

**Comment by Troray** [comment]
> > > @justincnn 试试这个启动命令
> > > ```
> > > docker run -d --name qiandao -e PORT=12345 --net=host -v $(pwd)/qiandao/config:/usr/src/app/config asdaragon/qiandao
> > > ```
> > 
> > 
> > host 模式创建后，提示如下
> > `failed at 1/4 request, , https://www.52pojie.cn/home.php?mod=task&do=apply&id=2`
> > 只是不提示 error:HTTP 599 了。
> 
> 52pojie的问题应该是不能重复签到的原因吧，去编辑模板那里测试一下看看网页返回内容

52pojie每天都是这样，而且我没有手动弄过。
另外，还有其他的签到也都不行，例如v2ex。每天都是如下：
`
<html>
<body>


2021-9-1 12:58:25 | 失败 | failed at 5/5 request, , http://localhost/util/string/replace?r=text&t=%C2%A0&p=%C2%A0&s=%E9%93%9C%E5%B8%81%E5%A5%96%E5%8A%B1%3A{{log_value\|urlencode}}%C2%A0%20%E6%80%BB%E5%A4%A9%E6%95%B0%3A{{log_days\|urlencode}}复制
-- | -- | --
2021-9-1 5:01:49 | 失败 | failed at 5/5 request, , http://localhost/util/string/replace?r=text&t=%C2%A0&p=%C2%A0&s=%E9%93%9C%E5%B8%81%E5%A5%96%E5%8A%B1%3A{{log_value\|urlencode}}%C2%A0%20%E6%80%BB%E5%A4%A9%E6%95%B0%3A{{log_days\|urlencode}}
2021-9-1 4:35:54 | 失败 | failed at 5/5 request, , http://localhost/util/string/replace?r=text&t=%C2%A0&p=%C2%A0&s=%E9%93%9C%E5%B8%81%E5%A5%96%E5%8A%B1%3A{{log_value\|urlencode}}%C2%A0%20%E6%80%BB%E5%A4%A9%E6%95%B0%3A{{log_days\|urlencode}}
2021-9-1 4:35:20 | 失败 | failed at 5/5 request, , http://localhost/util/string/replace?r=text&t=%C2%A0&p=%C2%A0&s=%E9%93%9C%E5%B8%81%E5%A5%96%E5%8A%B1%3A{{log_value\|urlencode}}%C2%A0%20%E6%80%BB%E5%A4%A9%E6%95%B0%3A{{log_days\|urlencode}}


</body>
</html>`


其他签到也都是卡在最后一部。如下：
`failed at 5/5 request, , http://localhost/util/string/replace?r=text&t=%C2%A0&p=%C2%A0&s=%E4%BB%8A%E6%97%A5%E7%AD%BE%E5%88%B0%E5%A5%96%E5%8A%B1%20%E8%8A%B1%E7%93%A3%20{{log_value|urlencode}}`

我的部署方式是N1-docker。docker run时，试过常规的12345:80，试过--net=host，也加入过--privileged=true，但是好像都不行

**Comment by Troray** [comment]
> > > @justincnn 试试这个启动命令
> > > ```
> > > docker run -d --name qiandao -e PORT=12345 --net=host -v $(pwd)/qiandao/config:/usr/src/app/config asdaragon/qiandao
> > > ```
> > 
> > 
> > host 模式创建后，提示如下
> > `failed at 1/4 request, , https://www.52pojie.cn/home.php?mod=task&do=apply&id=2`
> > 只是不提示 error:HTTP 599 了。
> 
> 52pojie的问题应该是不能重复签到的原因吧，去编辑模板那里测试一下看看网页返回内容

经过多次测试，发现所有提示类似下面这个错误的签到，其实是有成功签到的，但是都是返回错误，然后就会自动多次尝试，直到多次错误后自动禁用。请问这个该怎么排查解决。
`failed at 4/4 request, , http://localhost/util/string/replace?r=text&t=%C2%A0&p=%C2%A0&s=%E6%82%A8%E7%9B%AE%E5%89%8D%E8%8E%B7%E5%BE%97%E7%9A%84%E6%80%BB%E5%A5%96%E5%8A%B1%E4%B8%BA%3A%E6%B4%BB%E8%B7%83%20{{log_value|urlencode}}`

只单独检查常用API的话，每个API都是正常的。
![图片](https://i.imgur.com/otDiKqP.png)
