### ISSUE TITLE
为什么docker版，更新了镜像打开还是旧的？

### ISSUE THREAD

**Issue by mjyhj** [qd-today/qd#70]
测试了好几次，更新镜像完全没用，打开还是旧的版本。
必须把整个docker删除重新部署打开才会更新。
直接拉取镜像部署，打开还是旧的版本，已清空缓存

**Comment by b911ss** [comment]
> 测试了好一次，更新完全完全没用，打开还是旧的版本。
> 必须把整个docker删除重新部署打开打开更新。直接
> 拉取替换部署，打开还是旧的版本，已清空缓存

因为这个作者没有更新docker镜像。。。可能没空

**Comment by asdaragon** [comment]
@mjyhj 你更新镜像了当然要重新部署容器呀。。。

**Comment by if1y** [comment]
容器要删除重建

**Comment by mjyhj** [comment]
> @mjyhj 你更新镜像了当然要重新部署容器呀。。。

你没懂我意思，我直接用watchtower自动升级或者手动拉取新镜像直接部署，还是变成旧的
必须得直接删除再部署才可以
