### ISSUE TITLE
ipv6主机搭建使用问题

### ISSUE THREAD

**Issue by kroyoo** [qd-today/qd#72]
`PRETTY_NAME="Debian GNU/Linux 10 (buster)"`
服务器只有ipv6，docker启动并配置域名https，使用的是cloudflare cdn加速，注册ip，无论是ipv6还是ipv4，都会出现`500: Internal Server Error`
看日志：
![image.png](https://i.loli.net/2021/03/03/JEZl2zG59k4daKq.png)
初步看/usr/src/app/libs/utils.py，应该是还没支持ipv6
![image.png](https://i.loli.net/2021/03/03/EQ1On9afcJAxh2T.png)

**Comment by asdaragon** [comment]
@kroyoo 不适配ipv6，也没计划适配ipv6.没机器，没地址。

**Comment by kroyoo** [comment]
奇奇怪怪😂，已解决

**Comment by jiebiantiaoqu** [comment]
> 奇奇怪怪😂，已解决

怎么解决的
