### ISSUE TITLE
问题1:如何套域名并配置cdn? 

### ISSUE THREAD

**Issue by Yxue-1906** [qd-today/qd#73]
第一个问题在于,套了cdn之后,通过域名访问无法注册和登录,都会出现500错误,
三天前的ipv6的issue查看之后感觉应该不是IP问题,这个主机只有v4地址.

~~第二个问题就是进入内部执行脚本时出现标题所示错误
![image](https://user-images.githubusercontent.com/20736038/110194181-22ca8000-7e72-11eb-9a2c-b70f8c91ee5f.png)~~
(已解决,需要带上python执行)

请问应该如何解决? 十分感谢

**Comment by asdaragon** [comment]
@xueshao 500问题需要提供docker日志才能知道。运行docker logs 容器名获取

**Comment by Yxue-1906** [comment]
> @xueshao 500问题需要提供docker日志才能知道。运行docker logs 容器名获取

最近没有上github,差点忘了..
![image](https://user-images.githubusercontent.com/20736038/110464037-9b993880-810d-11eb-996e-12d7c0912baa.png)
日志关键出错信息应该如图.

**Comment by asdaragon** [comment]
@xueshao 从日志上看，你通过ipv6访问了页面（remote_ip=2001：），所以报错了。
