### ISSUE TITLE
自定义推送——钉钉

### ISSUE THREAD

**Issue by jiusiwan** [qd-today/qd#74]
1. 请求方法：post
2. url中填https://oapi.dingtalk.com/robot/send?access_token=8xxxxxxxcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx9
 //access_token改成自己的
3. application/json
4. post data中填入  {"msgtype":"markdown","markdown":{"title":"Tips{t}","text":"{log}"}}   
5. //其中Tips是我自己设置的关键字。也可以在机器人中设置关键字“签到”，就不用加入Tip关键字。

**Comment by superfat1988** [comment]
good one!太需要这个了， 现在serverchan收费了， 企业微信也不好申请， 还是钉钉机器人都好用，感谢！

**Comment by a76yyyy** [comment]
最新源码已支持钉钉推送，请基于a76yyyy/qiandao容器，通过源码更新方式更新至最新版后尝试
