### ISSUE TITLE
企业微信推送添加图片无效，测试推送是空白的

### ISSUE THREAD

**Issue by zivencn** [qd-today/qd#76]
企业微信，用;来分割，企业ID;应用ID;应用密钥;自定推送图片(非必需)

按照上面的方式添加了图片进去，但是推送后没有图片，是对图片链接或者图片格式有什么要求吗？

**Comment by zivencn** [comment]
> 企业微信，用;来分割，企业ID;应用ID;应用密钥;自定推送图片(非必需)
> 
> 按照上面的方式添加了图片进去，但是推送后没有图片，是对图片链接或者图片格式有什么要求吗？

**Comment by chwl66** [comment]
> 企业微信，用;来分割，企业ID;应用ID;应用密钥;自定推送图片(非必需)
> 
> 按照上面的方式添加了图片进去，但是推送后没有图片，是对图片链接或者图片格式有什么要求吗？

你好，你的推送图片问题解决了吗？
