### ISSUE TITLE
serverchan推送建议升级到 Turbo版 sct.ftqq.com

### ISSUE THREAD

**Issue by xydche** [qd-today/qd#77]
升级说明 见http://sc.ftqq.com/9.version
“因为微信发布公告将在4月底下线模板消息，Server酱开发了以企业微信为主的多通道新版（ Turbo版 sct.ftqq.com ）。旧版将在4月后下线，请尽快完成配置的更新。”
只需要更换域名和 sendkey 即可，建议更新。

**Comment by a76yyyy** [comment]
目前server酱已经不怎么好用了，有需要的话可以设置自定义推送

**Comment by a76yyyy** [comment]
已升级，请更新至最新版源码使用，docker镜像几天内发布
