### ISSUE TITLE
Docker 容器中代理的设置

### ISSUE THREAD

**Issue by isbzx** [qd-today/qd#79]
原因是 v2ex网站 从前几日开始不科学上网无法直连访问 被SNI阻断 用hosts也不行

所以想问下 docker下是否有命令或变量控制能够设置 某一签到模板的使用代理连接和发送请求

**Comment by billypon** [comment]
可以的，单个签到任务中有代理那项，输入http://127.0.0.1:8080即可，ip和端口替换成自己的
