### ISSUE TITLE
在公共模板中单击“订阅”无法获取到模板

### ISSUE THREAD

**Issue by djhdj1** [qd-today/qd#8]
在公共模板中单击“订阅”无法获取到模板，且“追加”、“上传”按钮始终为loading，还有个小问题应该是我没用明白，就是6月14新增的功能用户管理界面在哪里，我登录之后直接就是签到页面，docker已更新到6月14日

**Comment by asdaragon** [comment]
@djhdj1 
我测试订阅并没有什么问题，请使用chrome浏览器并关闭其他插件。旧版的镜像可能会有这个问题，20200606以后的版本已经修复。
管理员界面需要先设置账号为管理员身份。docker命令：
```
docker exec -it 容器名 /bin/bash
python ./chrole.py 邮箱 admin
```
