### ISSUE TITLE
代理要怎么使用呢

### ISSUE THREAD

**Issue by zlhdd108** [qd-today/qd#81]
想问一下，proxies的代理支持什么类型的呢，http代理么，socks5这种可以么？
具体格式是什么样的呢？

**Comment by asdaragon** [comment]
还没开发好

**Comment by billypon** [comment]
@AragonSnow 我不是发PR了吗，代理我一直都在用呀，有什么问题吗

**Comment by billypon** [comment]
@zlhdd108 支持http/https/socks5代理，格式为http://127.0.0.1:8080或https://127.0.0.1:8080或socks5://127.0.0.1:1080，其中的ip和端口替换成自己的

**Comment by ckx000** [comment]
> @zlhdd108 支持http/https/socks5代理，格式为[http://127.0.0.1:8080或https://127.0.0.1:8080或socks5://127.0.0.1:1080，其中的ip和端口替换成自己的](http://127.0.0.1:8080%E6%88%96https://127.0.0.1:8080%E6%88%96socks5://127.0.0.1:1080%EF%BC%8C%E5%85%B6%E4%B8%AD%E7%9A%84ip%E5%92%8C%E7%AB%AF%E5%8F%A3%E6%9B%BF%E6%8D%A2%E6%88%90%E8%87%AA%E5%B7%B1%E7%9A%84)

添加任务那里是添加了 但是貌似并没有生效，因为不论我填正确的代理和还是错误的代理 成功的照样成功 ，失败的同样失败
另外编辑模板里能不能也添加个使用代理的设置呢？

**Comment by billypon** [comment]
> > @zlhdd108 支持http/https/socks5代理，格式为[http://127.0.0.1:8080或https://127.0.0.1:8080或socks5://127.0.0.1:1080，其中的ip和端口替换成自己的](http://127.0.0.1:8080%E6%88%96https://127.0.0.1:8080%E6%88%96socks5://127.0.0.1:1080%EF%BC%8C%E5%85%B6%E4%B8%AD%E7%9A%84ip%E5%92%8C%E7%AB%AF%E5%8F%A3%E6%9B%BF%E6%8D%A2%E6%88%90%E8%87%AA%E5%B7%B1%E7%9A%84)
> 
> 添加任务那里是添加了 但是貌似并没有生效，因为不论我填正确的代理和还是错误的代理 成功的照样成功 ，失败的同样失败
> 另外编辑模板里能不能也添加个使用代理的设置呢？

@ckx000 @AragonSnow 任务设置的代理没有生效是因为docker镜像中没有安装pycurl这个依赖，只要这个依赖安装好代理就会生效。

@AragonSnow 模板那里设置代理，整体复杂度就提升了，建议还是先使用任务代理

**Comment by ckx000** [comment]
> > > @zlhdd108 支持http/https/socks5代理，格式为[http://127.0.0.1:8080或https://127.0.0.1:8080或socks5://127.0.0.1:1080，其中的ip和端口替换成自己的](http://127.0.0.1:8080%E6%88%96https://127.0.0.1:8080%E6%88%96socks5://127.0.0.1:1080%EF%BC%8C%E5%85%B6%E4%B8%AD%E7%9A%84ip%E5%92%8C%E7%AB%AF%E5%8F%A3%E6%9B%BF%E6%8D%A2%E6%88%90%E8%87%AA%E5%B7%B1%E7%9A%84)
> > 
> > 
> > 添加任务那里是添加了 但是貌似并没有生效，因为不论我填正确的代理和还是错误的代理 成功的照样成功 ，失败的同样失败
> > 另外编辑模板里能不能也添加个使用代理的设置呢？
> 
> @ckx000 @AragonSnow 任务设置的代理没有生效是因为docker镜像中没有安装pycurl这个依赖，只要这个依赖安装好代理就会生效。
> 
> @AragonSnow 模板那里设置代理，整体复杂度就提升了，建议还是先使用任务代理

~~感谢大佬解惑，但是好像AragonSnow大大的docker中不能直接用pip安装pycurl？？我试了下直接报错，稍微搜了下 说是要更新到py3才行？但是目前docker中似乎是用的py2.7？还是说缺了啥前置依赖？~~
通过排查错误发现是似乎是没有libcurl 依赖的问题？
我后来使用apk add curl-dev装好了依赖 再重新pip install pycurl就成功安装上了。。

进签到主页测试。貌似是成功实现了特定任务走代理，，然而其他任务却大量出现了599链接错误（之前备份了一版docker，发现没问题）
查看docker日志 发现报错是 
`CurlError: HTTP 599: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to xxx.yyy:443`

还有不少任务出错提示是
`failed at 1/8 request, error:HTTP 599: Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.,`

**Comment by billypon** [comment]
@ckx000 
对于第一个问题，你要确保代理设置是否正确，同时要保证这个代理可以访问xxx.yyy
对于第二个问题，可能是服务器返回的结果有问题

**Comment by ckx000** [comment]
> @ckx000
> 对于第一个问题，你要确保代理设置是否正确，同时要保证这个代理可以访问xxx.yyy
> 对于第二个问题，可能是服务器返回的结果有问题

应该都不上述2个原因
因为这是直接使用了原版0628的映像和使用上述命令安装pycurl和libcurl后的docker进行对比后的结果，我互相切换这2个版本的容器均能复现

**Comment by billypon** [comment]
@ckx000 如果这两个问题存在，不管你用哪个版本都不会正常的

**Comment by ckx000** [comment]
> @ckx000 如果这两个问题存在，不管你用哪个版本都不会正常的

使用原本就没有curl库和libcurl的0628版 和自己安装libcurl打上pycurl之后 就是这个错误，毕竟其他会影响的因素变量都是相同的
其中具体原理和机制因为水平有限我也找不出。
还是说我自动安装的pycurl和libcurl和佬你安装的不一样造成的？

只是换用另一位大佬用py3写的qiandao版本就没问题。可能是libcurl哪里有冲突吧

**Comment by billypon** [comment]
那就不清楚了，现在我用0621的镜像安装pycurl后，代理工作正常

**Comment by a76yyyy** [comment]
> > @ckx000 如果这两个问题存在，不管你用哪个版本都不会正常的
> 
> 使用原本就没有curl库和libcurl的0628版 和自己安装libcurl打上pycurl之后 就是这个错误，毕竟其他会影响的因素变量都是相同的 其中具体原理和机制因为水平有限我也找不出。 还是说我自动安装的pycurl和libcurl和佬你安装的不一样造成的？
> 
> 只是换用另一位大佬用py3写的qiandao版本就没问题。可能是libcurl哪里有冲突吧

因为py3版本的容器添加了完整的curl环境，并且针对代理问题进行了大量的修复和优化，如果需要使用代理请尝试py3版本的签到框架，而不是py2的0628版本
