### ISSUE TITLE
签到脚本无法绕过cloudflare验证，请教如何解决

### ISSUE THREAD

**Issue by justin0705** [qd-today/qd#86]
签到某V/P*N时经常因为cloudflare验证导致签到失败，测试时也有发现这个问题，请假如何解决
![image](https://user-images.githubusercontent.com/38656632/118564592-3021b600-b7a3-11eb-88eb-f00bbb9035ed.png)

![image](https://user-images.githubusercontent.com/38656632/118564694-5a737380-b7a3-11eb-8818-dd39856cab1c.png)

**Comment by asdaragon** [comment]
1,  有的只要 user-agent 和 cookie一致就不会出现5秒盾
2.  借助第三方工具，如 https://github.com/FlareSolverr/FlareSolverr

**Comment by 15cm** [comment]
我用 https://github.com/FlareSolverr/FlareSolverr 做了个绕过 m-team CF 墙的例子 https://github.com/qiandao-today/templates/pull/228

**Comment by 7161457** [comment]
> 我用https://github.com/FlareSolverr/FlareSolverr做了个墙m-team CF的例子[qiandao-today/templates#228](https://github.com/qiandao-today/templates/pull/228)

你好，请问签到的代理怎么编辑，我的FlareSolverr部署成功了，输入8191地址可以看到，但是我在签到代理里添加，一直都是Proxy CONNECT aborted，我在远程服务器部署FlareSolverr也是一样不行，包括127.0.0.1  内网地址，外网地址都实验了。不行。
![1666860422049](https://user-images.githubusercontent.com/113887555/198239537-b4ebd306-8a77-4de4-94ef-44ef82aee91e.png)
![1666860457843](https://user-images.githubusercontent.com/113887555/198239546-4a6fb264-8e18-4ad7-bb21-60d27be6d0af.jpg)
![1666860628009](https://user-images.githubusercontent.com/113887555/198239549-25f02a1e-00a2-4ba7-ac4b-eeb133fa0cb2.jpg)

**Comment by 7161457** [comment]
![1666860929309](https://user-images.githubusercontent.com/113887555/198239832-bee3fda6-8ff8-4e96-9ee4-443d5f944058.jpg)
