### ISSUE TITLE
支持自定义模板库

### ISSUE THREAD

**Issue by shuosiw** [qd-today/qd#87]
希望能支持自定义额外的模板库，而不仅仅只是从 https://gitee.com/qiandao-today/templates 同步，比如允许在模板库中填入一个第三方的模板库地址：

* 可以是一个 github 仓库地址
* 又或者是 github 仓库中的某个目录

这样就可以由其他人来维护提供一些 Har 模板仓库，当前一些存在 GitHub 的 Har 模板，只能下载下来，一个一个添加，有点不够优雅。

**Comment by asdaragon** [comment]
@shuosiw 无计划添加。私有的服务器建议使用自带的模板发布功能。

**Comment by shuosiw** [comment]
@AragonSnow 又或者能否提供批量上传 har 来添加签到模板的功能呢？现在如果需要上传多个 har 的话，成本还是挺高的.

前面提的第三方模板仓库其实就是参考 unraid 的功能：

![image](https://user-images.githubusercontent.com/2578976/120132561-1ea5c880-c1fd-11eb-8add-74ee7a3d23d6.png)

**Comment by asdaragon** [comment]
@shuosiw 这想法可以，下一版给加上
