### ISSUE TITLE
收不到签到提醒邮件

### ISSUE THREAD

**Issue by raycao-git** [qd-today/qd#88]
设置好了env关于邮件的值，可以收到密码重置的邮件，但收不到签到成功或失败的邮件（微信可收到推送），有点神奇，该怎么办呢？
![image](https://user-images.githubusercontent.com/60532594/120099154-a0014a80-c16c-11eb-98d5-7a8655781e64.png)
![image](https://user-images.githubusercontent.com/60532594/120099143-8bbd4d80-c16c-11eb-8be9-de0b0ad3dace.png)

**Comment by asdaragon** [comment]
@raycao-git  邮箱的不支持手动测试的推送，用自动推送的试试
