### ISSUE TITLE
设置wxpusher推送后出现500错误

### ISSUE THREAD

**Issue by Eao-Kind** [qd-today/qd#89]
环境：群晖docker
设置wxpusher消息推送后，手动执行签到提示 Fail 500 error
容器日志如下：
    HTTPServerRequest(protocol='http', host='127.0.0.1:5880', method='POST', uri='/task/1/run', version='HTTP/1.1', remote_ip='172.17.0.1', headers={'Origin': 'http://127.0.0.1:5880', 'Content-Length': '0', 'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': '127.0.0.1:5880', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://127.0.0.1:5880/my/', 'Cookie': 'KEEP_LOGIN=8Zg%3Acd938ff6fbac1edcf5f516bd6ff03be027757c412e3fd6cf7c623ca7da719614358e93d3e69711715dbab9b16f6b6e7b8696af8b1a239cea5ea7e0902f1ca5033d9b0b7f016ca6b664500e13399dfbbeb16bfbf18c9a887%3A1621602487; _xsrf=2|4d520dbd|7782dc17a2139d81ecdeb914d12d092a|1622608698; remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6ImRSTElQTWJEeU1vQWt1cTBVb1wvUmFRPT0iLCJ2YWx1ZSI6Ik9tMUJvSldHRmlwb3p6TFM0WkxuRmt4ZWJYc2g1bmVncHl3K1U0OEFEWGxaT1Noc0x3aHQ0ejE0KzljazFSUlJZc25yblwvNENJNVwvOCtyOVdyQ3N6elNsZXUxWnNOMjhKUGhWSHpPbXo5dVJBYjNxV05ENFEzeXE4bHgwY3ozV0FEMVlOQnl5ZmRJZHR6N3pHOXlQNklBandNaTJQTEZ5Q2J4T3lcLzUxS0w0ND0iLCJtYWMiOiIxMmZhZmUxZmEyNDJmODg0N2ZkOTE3NThlYTBhNTJmODE3MjQxNjFmYWRlYjU3MDE3Zjk5NjE0NDZlMzk4OTAxIn0%3D; stay_login=0; smid=NzW6QBg4Lx3J-tod_R-0odIKd5vMBCn1kyRM83aEe9U909PKzH9M2iiiSf2wDciFfbuP62rnEw1DW8Ili6E-gg; user="2|1:0|10:1622624165|4:user|60:hKRyb2xlwKhuaWNrbmFtZcCiaWQBpWVtYWlssTE3NzI0MDA4OTFAcXEuY29t|ba421ba7038f224019099834e0074d91a54c1b06575075aadc9f945c56bd8438"; XSRF-TOKEN=eyJpdiI6IjM1RnRTQUJXRGxWMzRGOGZmcjZiVXc9PSIsInZhbHVlIjoiaFc2WU56UUFOenBLRnh0bWZiQTB1bzFBb091V0xrZ2tzQUJyOTI3R2R0V2RPaUllTzFXOXMzN2h0Qk9LUE0reCIsIm1hYyI6IjNiOTEyYTQ2ZGE5MDEyYTdjZjlhNzM0NzAyZThhODJhYWVkMWUwMWI4ZGFmZWJhMmQ0ZjgyNWUwMjE0MmQ1YTgifQ%3D%3D; heimdall_session=eyJpdiI6IjdXV1wvNDBZNDU1MVduc29pdHFwbG13PT0iLCJ2YWx1ZSI6IkQyKzBPUUlZc2RGdDVCQTY1MkJBYTZ0amt5KzdxWDJHQzFsSUdPTmgrM3BHNnVSbGt0bUxLWVNxcU1cL2xMb0htIiwibWFjIjoiZWQwMmNmNjdkYThkNjRiOGMzYjkzMmFkZTc2M2NmOWRhNjlhZDE4YTA0NGFiOWVlZGJhMGYzN2FmNDk5ZGFjZCJ9; ph_mqkwGT0JNFqO-zX2t0mW6Tec9yooaVu7xCBlXtHnt5Y_posthog=%7B%22distinct_id%22%3A%22179bd6ad617677-05369c37a6a6e6-f7f1939-144000-179bd6ad6184f3%22%2C%22%24device_id%22%3A%22179bd6ad617677-05369c37a6a6e6-f7f1939-144000-179bd6ad6184f3%22%7D'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
        yielded = self.gen.send(value)
      File "/usr/src/app/web/handlers/task.py", line 185, in post
        pushertool.pusher(user['id'], pushsw, 0x8, title, logtmp)
      File "/usr/src/app/funcs.py", line 38, in pusher
        if (notice['noticeflg'] & flg != 0):
    TypeError: 'NoneType' object has no attribute '__getitem__'
[E 210603 01:53:15 web:2064] 500 POST /task/1/run (172.17.0.1) 752.12ms
[E 210603 01:53:15 web:2064] 500 POST /task/1/run (172.17.0.1) 752.12ms

而签到过程是正常的。 关闭推送后手动执行签到仍然报错。
进入数据库 user表中手动删除对应wxpusher值后正常，可能是wxpusher那边代码更新了导致出错吗？

**Comment by Eao-Kind** [comment]
大佬可以考虑一下添加电报的推送吗，，

**Comment by a76yyyy** [comment]
最新源码已支持tg推送，请通过源码更新方式更新至最新版尝试
