### ISSUE TITLE
第一次搭建，没有公共模板

### ISSUE THREAD

**Issue by love2wind** [qd-today/qd#90]
![image](https://user-images.githubusercontent.com/11996852/122018505-82cbad80-cdf5-11eb-91ea-91e7bbc76a6f.png)

**Comment by love2wind** [comment]
公共模板是要导入还是项目自带就有呢？

**Comment by asdaragon** [comment]
@love2wind 公共模板今天被封了，下一版再修复。可以先加QQ群642842749 看看有没有你要的模板

**Comment by love2wind** [comment]
> @love2wind 公共模板今天被封了，下一版再修复。可以先加QQ群642842749 看看有没有你要的模板

这么点背？刚搭建就被封了
![image](https://user-images.githubusercontent.com/11996852/122019925-dee30180-cdf6-11eb-8b11-36cedc22bc27.png)
我这就加群试试。谢谢
