### ISSUE TITLE
打开公共模板提示如下，docker部署

### ISSUE THREAD

**Issue by ghost** [qd-today/qd#95]
Traceback (most recent call last):
  File "/usr/src/app/web/handlers/subscribe.py", line 66, in get
    self.db.pubtpl.add(har)
  File "/usr/src/app/db/pubtpl.py", line 31, in add
    return self._insert(**insert)
  File "/usr/src/app/db/basedb.py", line 102, in _insert
    dbcur = self._execute(sql_query, values.values())
  File "/usr/src/app/db/basedb.py", line 40, in _execute
    dbcur.execute(sql_query, values)
OperationalError: table pubtpl has no column named commenturl

**Comment by asdaragon** [comment]
@c939984606  😂添加新功能，添加新bug。今晚修复。

**Comment by acooler15** [comment]
> @c939984606 😂添加新功能，添加新bug。今晚修复。

怎么添加第三方库呀？

**Comment by asdaragon** [comment]
@c939984606 更新一下
``` 
docker exec -it 容器名 /bin/sh
git config --global credential.helper store
git fetch --all
git reset --hard origin/master
exit
docker restart 容器名
```

**Comment by asdaragon** [comment]
@acooler15   参考 https://github.com/qiandao-today/template。
自己创建一个github仓库，也可以fork https://github.com/qiandao-today/templates  。填写 tpls_history.json，点开公共仓库注册github链接和分支就可以了

**Comment by xuexiangbing** [comment]
> @c939984606 😂添加新功能，添加新bug。今晚修复。
@AragonSnow 
问题依旧，何时修复啊。。执行上面的命令git fetch --all 还需要账号密码的，。

**Comment by yoyoweb1** [comment]
@xuexiangbing 我也遇到一样的情况，你那行了吗？
@AragonSnow 请问怎么解决？谢谢！

**Comment by asdaragon** [comment]
@xuexiangbing @yoyoweb1  更新一下镜像

**Comment by xuexiangbing** [comment]
> @xuexiangbing @yoyoweb1 更新一下镜像

@AragonSnow 已OK。
