### ISSUE TITLE
更新0628版本后，签到大规模出现error104.。。。。这是什么回事？

### ISSUE THREAD

**Issue by hecarli555** [qd-today/qd#99]
更新0628版本后，签到大规模出现error104.。。。。这是什么回事？

**Comment by asdaragon** [comment]
@hecarli555 104应该是网络错误，跟qiandao本身应该关系不大。如果签的是境外网站，可以部署在境外服务器试试。

**Comment by hecarli555** [comment]
就国内的春天，我抓饼干的时候发现他饼干怪怪的…大佬可以去看看，填进去后执行签到提示104connection Reset by peer



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: AragonSnow ***@***.***&gt;
发送时间: 2021年7月16日 12:02
收件人: AragonSnow/qiandao ***@***.***&gt;
抄送: hecarli555 ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[AragonSnow/qiandao] 更新0628版本后，签到大规模出现error104.。。。。这是什么回事？ (#99)





 
@hecarli555 104应该是网络错误，跟qiandao本身应该关系不大。如果签的是境外网站，可以部署在境外服务器试试。

**Comment by asdaragon** [comment]
@hecarli555 测试一下，是不是被5秒盾了
